<?php
	$frontController = Zend_Controller_Front::getInstance();
	$module = $frontController->getRequest()->getModuleName();
	$controller = $frontController->getRequest()->getControllerName();
	$action = $frontController->getRequest()->getActionName();
	$group_id = $frontController->getRequest()->getParam('group_id');
	$grp_id_link = ($group_id)? '/group_id/'.$group_id : '';
	$approve = $frontController->getRequest()->getParam('approve');
	$grp_id_link .= ($approve != '')? '/approve/'.$approve : '';
	$room_type = $frontController->getRequest()->getParam('room_type');
	$grp_id_link .= ($room_type != '')? '/room_type/'.$room_type : '';
	$entry_by = $frontController->getRequest()->getParam('entry_by');
	$grp_id_link .= ($entry_by != '')? '/entry_by/'.$entry_by : '';
	$hotel_id = $frontController->getRequest()->getParam('hotel_id');
	$grp_id_link .= ($hotel_id != '')? '/hotel_id/'.$hotel_id : '';
	$max_people = $frontController->getRequest()->getParam('max_people');
	$grp_id_link .= ($max_people != '')? '/max_people/'.$max_people : '';
	$descount_price_min = $frontController->getRequest()->getParam('descount_price_min');
	$grp_id_link .= ($descount_price_min != '')? '/descount_price_min/'.$descount_price_min : '';
	$descount_price_max = $frontController->getRequest()->getParam('descount_price_max');
	$grp_id_link .= ($descount_price_max != '')? '/descount_price_max/'.$descount_price_max : '';
	$room_type_id = $frontController->getRequest()->getParam('room_type_id');
	$grp_id_link .= ($room_type_id != '')? '/room_type_id/'.$room_type_id : '';
	$room_name = $frontController->getRequest()->getParam('room_name');
	$grp_id_link .= ($room_name != '')? '/room_name/'.$room_name : '';
	$translator = Zend_Registry::get('translator');
?>
<?php echo $translator->translator('pagination_total'); ?> <?php echo $this->numbers($this->totalItemCount); ?> <?php echo $translator->translator('pagination_records_found'); ?> &nbsp; | &nbsp; <?php echo $translator->translator('pagination_Page'); ?> <?php echo $this->numbers($this->current); ?> <?php echo $translator->translator('pagination_of'); ?> <?php echo $this->numbers($this->last); $sessions = Eicra_Global_Variable::getSession(); ?></td>
	<div class="page-no">
		  <?php echo $translator->translator('pagination_jump_page'); ?> <select name="PageNum" id="PageNum" style="width:50px;" onChange="document.location.href='<?php echo $this->baseUrl().'/'.$module.'/'.$controller.'/'.$action.$grp_id_link.'/page/';?>'+this.options[this.selectedIndex].value">
                    <?php
                        for($i=1;$i<=$this->pageCount;$i++)
                        {
                    ?>
                    <option value="<?php echo $i; ?>" <?php if($this->current == $i){ ?>selected="selected"<?php } ?>><?php echo $this->numbers($i); ?></option>
                    <?php
                        }
                    ?>							
                </select>
                                                  
        <form id="form1" name="form1" method="post" action="<?php echo $this->url(array('module' => $module,'controller' => $controller,'action' => $action,'group_id' => $group_id, 'approve' => $approve, 'room_type' => $room_type, 'entry_by' => $entry_by, 'hotel_id' => $hotel_id, 'max_people' => $max_people, 'descount_price_min' => $descount_price_min, 'descount_price_max' => $descount_price_max, 'room_type_id' => $room_type_id, 'room_name' => $room_name),'adminrout',true);?>" style="margin:0px;">
          <?php echo $translator->translator('pagination_view_result_per_page'); ?> <select name="viewPageNum" id="viewPageNum" style="width:50px;" onChange="form.submit();">
                    <option value="1" <?php if($sessions->viewPageNum == '1'){ ?>selected="selected"<?php } ?>><?php echo $this->numbers(1); ?></option>
                    <option value="5" <?php if($sessions->viewPageNum == '5'){ ?>selected="selected"<?php } ?>><?php echo $this->numbers(5); ?></option>
                    <option value="10" <?php if($sessions->viewPageNum == '10'){ ?>selected="selected"<?php } ?>><?php echo $this->numbers(10); ?></option>
                    <option value="30" <?php if($sessions->viewPageNum == '30'){ ?>selected="selected"<?php } ?>><?php echo $this->numbers(30); ?></option>
                    <option value="100" <?php if($sessions->viewPageNum == '100'){ ?>selected="selected"<?php } ?>><?php echo $this->numbers(100); ?></option>
                </select>
         </form> 			                              
	</div>