<?php
$tab_base_link = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
?>
<script type="text/javascript">
$(function() {
		$("#tabs").tabs().find(".ui-tabs-nav").sortable({axis:'xy'});
		
		$('#full_payment').change(function() {
			var self = this;
			if($(self).val() != null && $(self).val() != '')
			{
				var data = 	$(self).val();
				var data_arr = 		data.split('_');	
				$.ajax({
						url: "<?php echo $this->url( array('module'=> 'Hotels', 'controller' => 'backendexpedia', 'action'     => 'itinerary' ), 'adminrout',    true) ?>",
						type: 'POST',
						data: { payment_id: data_arr[0], invoice_id: data_arr[1]},
						beforeSend: function(){
							$('#full_payment_link').html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');
						 },
						success: function(response) 
						{
							//alert(response);
							var json_arr = eval("("+response+")");
							if(json_arr.status == 'ok')
							{
								var payment_link	=	json_arr.payment_data;
								var payment_logo	=	json_arr.payment_info.logo;
								var input_type		=	json_arr.input_type;
								//alert(payment_logo);
								var	html_data	=	(input_type == 'link') ? '<a href="'+payment_link+'" target="_blank"><img src="data/frontImages/gateway/gateway_logo/'+payment_logo+'" width="140" /></a>' : payment_link;
								$('#full_payment_link').html(html_data);
								UPay_Pay();
							}
							else
							{
								openMsgDialog(json_arr.msg);
								$('#full_payment_link').html('');
							}							
						},
						error: function(xhr, status, error){
							closeLoaderDialog();
							$('#full_payment_link').html('');
							var msg = "Error! " + xhr.status + " " + error;
							openMsgDialog(msg);
						}
				});			
			}
			else
			{
				$('#full_payment_link').html('');
			}
			
		});
		
		
		$('#now_payment').change(function() {
			var self = this;
			if($(self).val() != null && $(self).val() != '')
			{
				var data = 	$(self).val();
				var data_arr = 		data.split('_');	
				$.ajax({
						url: "<?php echo $this->url( array('module'=> 'Hotels', 'controller' => 'backendexpedia', 'action'     => 'delete' ), 'adminrout',    true) ?>",
						type: 'POST',
						data: { payment_id: data_arr[0], invoice_id: data_arr[1]},
						beforeSend: function(){
							$('#now_payment_link').html('<img src="application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif" height="16" border="0" />');
						 },
						success: function(response) 
						{
							//alert(response);
							var json_arr = eval("("+response+")");
							if(json_arr.status == 'ok')
							{
								var payment_link	=	json_arr.payment_data;
								var payment_logo	=	json_arr.payment_info.logo;
								var input_type		=	json_arr.input_type;
								//alert(payment_logo);
								var	html_data	=	(input_type == 'link') ? '<a href="'+payment_link+'" target="_blank"><img src="data/frontImages/gateway/gateway_logo/'+payment_logo+'" width="140" /></a>' : payment_link;
								$('#now_payment_link').html(html_data);
								UPay_Pay();
							}
							else
							{
								openMsgDialog(json_arr.msg);
								$('#now_payment_link').html('');
							}							
						},
						error: function(xhr, status, error){
							closeLoaderDialog();
							$('#now_payment_link').html('');
							var msg = "Error! " + xhr.status + " " + error;
							openMsgDialog(msg);
						}
				});			
			}
			else
			{
				$('#now_payment_link').html('');
			}
			
		});
		
		
	});
function openMsgDialog(msg)
{
$('#dialog_container').html(msg).dialog({
			autoOpen: true,
			modal: false,
			show: 'fade',
			resizable: 'false',				
			buttons: { "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>": function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } },
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 10000);
				  }
		});
}
</script>

<div id="container">
<?php 

if (!$this->allow('view')) : 

?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php 
	else : 
	//print_r($this->itinerary_arr);
	$mem_db = new Members_Model_DbTable_MemberList();
	$country_db = new Eicra_Model_DbTable_Country();
	$mem_info = $mem_db->getMemberInfo($this->itinerary_arr['user_id']);

	$global_conf = Zend_Registry::get('global_conf');
	$currency = new Zend_Currency($global_conf['default_locale']);
	$currencySymbol = $currency->getSymbol();
	$currencyShort = $currency->getShortName();
	$permission_arr = array('edit_enable' => $this->allow('edit','backendexpedia','Hotels'));
?>

<div class="title-container">
	<div class="invoice-details"><h1><?php echo $this->translator->translator('hotels_itinerary_details_invoice_page_name'); ?></h1></div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Hotels','controller' => 'backendexpedia', 'action'     => 'itinerary' ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        
        <?php if ($permission_arr['edit_enable']) : ?>
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Hotels','controller' => 'backendexpedia', 'action'     => 'delete', 'id' => $this->itinerary_arr['id'] ), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon edit"><?php echo $this->translator->translator('common_edit_title'); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<div id="button_top_bar"></div>
<div class="content-container">
	<div id="actionMessage"></div>
	<form name="formInvoice" id="formInvoice" method="post">        
    	
        <div id="tabs">
        	<div class="itinerary-price">
            	<?php echo $this->translator->translator('hotels_api_expedia_backend_view_grand_total'); ?> <?php echo $this->itinerary_arr['rateCurrencyCode'] . ' '.$this->itinerary_arr['price'] ; ?>
           	</div>
            
            <div class="itinerary-status-cont">
            	<?php 
					switch($this->itinerary_arr['cancel'])
					{
						case '0' :
							echo '<h3 class="itinerary-status active">'.$this->translator->translator('hotels_api_expedia_backend_view_itinerary_status_active').'</h3>';
						break;
						case '1' :
							echo '<h3 class="itinerary-status inactive">'.$this->translator->translator('hotels_api_expedia_backend_view_itinerary_status_cancel').'</h3>';	
						break;
						
					}
				?>
            </div>
            
        	<ul>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-1"><?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_info'); ?></a></li>

            </ul>
            
            <div id="tabs-1">
            	<!-- Client Info Srart -->
                <div class="client-info">
                    <fieldset class="fieldset">
                    <legend class="legend"><?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_info'); ?></legend>
                    <div class="form">
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_first_name_title'); ?>
                            </div>
                            
                            <div class="field">
                               	<?php echo $this->escape($mem_info['firstName']); ?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_last_name_title'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php echo $this->escape($mem_info['lastName']); ?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_company_name_title'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php echo $this->escape($mem_info['companyName']); ?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_email_address_title'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php echo $this->escape($mem_info['username']); ?>	
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_address_title'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php echo $this->escape($mem_info['address']); ?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_postalCode_title'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php echo $this->escape($mem_info['postalCode']); ?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_city_title'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php echo $this->escape($mem_info['city']); ?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_state_title'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php echo $this->escape($mem_info['state']); ?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_country_title'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php $country_info = $country_db->getInfo($mem_info['country']); echo $this->escape($country_info['value']); ?>
                            </div>
                        </div>
                        
                      
                    </div>
                    </fieldset>
                </div>
                <!-- Client Info End -->
                
                <!-- Invoice Info Srart -->
                <div class="invoice-info">
                    <fieldset class="fieldset last">
                    <legend class="legend"><?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_billing_info'); ?></legend>
                    <div class="form">
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_invoice_id_title'); ?>
                            </div>
                            
                            <div class="field">
                               	<span class="label"><?php echo '#'.$this->escape($this->itinerary_arr['itineraryId']); ?></span>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_itinerary_status'); ?>
                            </div>
                            
                            <div class="field">
                            	<span class="label">
								<?php 
									switch($this->itinerary_arr['cancel'])
									{
										case '0' :
											echo $this->translator->translator('hotels_api_expedia_backend_view_itinerary_status_active');	
										break;
										case '1' :
											echo $this->translator->translator('hotels_api_expedia_backend_view_itinerary_status_cancel');	
										break;
										
									}
								?>
                                </span>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_confirmation_id'); ?>
                            </div>
                            
                            <div class="field">
                               	<span class="label"><?php echo $this->escape($this->itinerary_arr['confirmationNumbers']); ?></span>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_number_adult_pax'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php 					  
									 
									echo  '2' ;
								?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                                <?php echo $this->translator->translator('hotels_api_expedia_backend_view_number_child_pax'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php 
									echo  '0' ;
								?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                              	<?php echo $this->translator->translator('hotels_api_expedia_backend_view_hotel_id' ); ?>
                            </div>
                            
                            <div class="field">
                              	<?php 
									echo $this->itinerary_arr['hotelId']; 
								?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                            	<?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_invoice_arrival_date'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php echo $this->escape($this->itinerary_arr['arrivalDate']); ?>
                            </div>
                        </div>
                        
                        <div class="form-row">
                            <div class="label">
                            	<?php echo $this->translator->translator('hotels_api_expedia_backend_view_client_invoice_departure_date'); ?>
                            </div>
                            
                            <div class="field">
                              	<?php echo $this->escape($this->itinerary_arr['departureDate']); ?>
                            </div>
                        </div>
                        
                   	</div>
                    </fieldset>
             	</div>
                <!-- Invoice Info End-->
                
                <!-- Invoice Items Start -->
                <div class="clr"></div>
            	<fieldset class="fieldset last">
                <legend class="legend">Payment Details</legend>
                	<?php
					try {
						$responseValue_arr = Zend_Json::decode($this->itinerary_arr['resultSetObject'] , Zend_Json::TYPE_ARRAY);
						$itineraryInfo = $responseValue_arr['HotelRoomReservationResponse'];
					}
					catch (Exception $e){
						echo 'NOT A READABLE FORMAT';
						goto error; 
					}
					?>
                	<div class="itinerary">
                    	<div class="itinerary-row caption">
                       		<div class="itinerary-col-1">
                            	<?php echo $this->translator->translator('hotels_api_expedia_itinerary_view_itinerary_fields');?>
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $this->translator->translator('hotels_api_expedia_itinerary_view_itinerary_values');?>
                            </div>
                        </div>
                        
                        <?php
						if($itineraryInfo)
						{
                        	foreach ($itineraryInfo  as $key => $value)
							{									
								if (is_array($value)){
									continue;		
								}
								else if ($key == 'nonRefundable'){
									
									if (empty($value)){
										continue;	
									}
									
									else {
										$value =  $this->translator->translator('hotels_api_expedia_details_tbl_nonrefundable'); 	
									}
										
								}
								
								else if (empty($value)){
									
										continue;	
								}
							?>
							<div class="itinerary-row">
								<div class="itinerary-col-1">
									<?php echo ucfirst($key) ?>
								</div>
								<div class="itinerary-col-2">
									<?php echo $value ?>
								</div>
							</div>
						<?php									
							}
						}
						?>
                    </div>
                    
                    <div class="itinerary">
                    	<pre><?php $cancellationPolicy 	=	$itineraryInfo ['CancelPolicyInfoList']['CancelPolicyInfo']; ?></pre>
                        
                    	<div class="itinerary-row caption">
                       		<div class="itinerary-col-1">
                            	<?php echo $this->translator->translator('hotels_api_expedia_itinerary_view_itinerary_cancel_fields');?>
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $this->translator->translator('hotels_api_expedia_itinerary_view_itinerary_cancel_values');?>
                            </div>
                        </div>
                        <?php
							for ($i = 0; $i< count($cancellationPolicy); $i++ )
							{
								
								$policyArray = 	$cancellationPolicy[$i];
								
								foreach ($policyArray as $key => $value)
								{							
						?>
                        <div class="itinerary-row">
                        	<div class="itinerary-col-1">
                            	<?php echo ucfirst($key) ?> 
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $value ?>
                            </div>
                        </div>
                        <?php 
								
								}
								//echo "joel";
						?>
                        
                        <div class="itinerary-row">
                        	<div class="itinerary-col-1">
                            	<hr />
                            </div>
                            <div class="itinerary-col-2">
                            	<hr />
                            </div>
                        </div>
                        <?php
							}
						?>
                  	</div>
                    
                    <div class="itinerary">
                    	<pre><?php $roomGroup 	=	$itineraryInfo ['RateInfos']['RateInfo']['RoomGroup']; ?></pre>
                        
                    	<div class="itinerary-row caption">
                       		<div class="itinerary-col-1">
                            	<?php echo $this->translator->translator('hotels_api_expedia_itinerary_view_itinerary_room_fields');?>
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $this->translator->translator('hotels_api_expedia_itinerary_view_itinerary_room_values');?>
                            </div>
                        </div>
                        
                        <?php	
						if($roomGroup)
						{								
							foreach ($roomGroup  as  $roomArray)
							{
								
								foreach ($roomArray  as  $key=>$value)
								{
						?>
                        <div class="itinerary-row">
                        	<div class="itinerary-col-1">
                            	<?php echo ucfirst($key) ?>
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $value ?> 
                            </div>
                        </div>
                        <?php 
											
								}
						?>
                        <div class="itinerary-row">
                        	<div class="itinerary-col-1">
                            	<hr />
                            </div>
                            <div class="itinerary-col-2">
                            	<hr />
                            </div>
                        </div>
                        <?php
							}
						}
						?>
                 	</div>
                    
                    <div class="itinerary">
                    	<pre><?php $ChargeableRateInfo 	=	$itineraryInfo ['RateInfos']['RateInfo']['ChargeableRateInfo']; ?></pre>
                        
                    	<div class="itinerary-row caption">
                       		<div class="itinerary-col-1">
                            	<?php echo $this->translator->translator('hotels_api_expedia_itinerary_view_itinerary_price_fields');?>
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $this->translator->translator('hotels_api_expedia_itinerary_view_itinerary_price_values');?>
                            </div>
                        </div>
                        
                      	<div class="itinerary-row">
                        	<div class="itinerary-col-1">
                            	<?php echo 'Surcharge Total' ?>
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $ChargeableRateInfo['@surchargeTotal'] ?>
                            </div>
                        </div>
                        
                        <div class="itinerary-row">
                        	<div class="itinerary-col-1">
                            	<?php echo 'Nightly Rate Total' ?>
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $ChargeableRateInfo['@maxNightlyRate'] ?>
                            </div>
                        </div>
                        
                        <div class="itinerary-row">
                        	<div class="itinerary-col-1">
                            	<?php echo 'Currency Code' ?>
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $ChargeableRateInfo['@currencyCode'] ?>
                            </div>
                        </div>
                        
                        <div class="itinerary-row">
                        	<div class="itinerary-col-1">
                            	<?php echo 'Total' ?>
                            </div>
                            <div class="itinerary-col-2">
                            	<?php echo $ChargeableRateInfo['@total'] ?>
                            </div>
                        </div>
                  	</div>
                    
                    <?php error: ?>			
                
          		</fieldset>
            	<!-- Invoice Items End -->
          	</div>
        </div>
  	</form>
</div>

<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('invoice_details_invoice_page_name')); ?>"></div>
<div id="dialog-confirm" title="<?php echo $this->translator->translator('common_confirmation',$this->translator->translator('common_delete')); ?>"></div>
<?php endif; ?>
</div>