<?php 
$this->headTitle()->headTitle($this->translator->translator('members_dashboard_block_header_title', '', 'Members'),'SET');
?>
<!-- Content Start-->
<article class="member-dashboard">	
  	<h1>My Dashboard</h1>
    <br />
    <?php echo $this->partial('blocks/members_content_info.phtml'); ?>
    <?php echo $this->partial('blocks/members_content_controlPanel.phtml'); ?>
	
    <div class="clear"></div>
    <?php echo $this->partial('blocks/news_content_latest.phtml'); ?>
</article>
<!-- Content End -->