<?php
if(!empty($this->group_datas['meta_keywords'])) { $this->headMeta()->setName('keywords',$this->group_datas['meta_keywords']);}
if(!empty($this->group_datas['meta_desc'])) { $this->headMeta()->setName('description',$this->group_datas['meta_desc']); }
if(!empty($this->group_datas['group_name'])) { $this->headTitle()->headTitle($this->group_datas['group_name'],'SET')->setSeparator(' - ')->headTitle($this->group_datas['meta_title']); }

$version = Zend_Registry::get('version');   
$front_template = Zend_Registry::get('front_template');
$business_type_db = new Hotels_Model_DbTable_BusinessType();
$cat_Info = new Hotels_Model_DbTable_Category();
$mem_db = new Members_Model_DbTable_MemberList();
$state_db = new Hotels_Model_DbTable_State();
$area_db = new Hotels_Model_DbTable_Area();
$country_db = new Hotels_Model_DbTable_Country();
$hotels_db = new Hotels_Model_DbTable_Hotels();
$room_type_db = new Hotels_Model_DbTable_RoomType();
$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);
$review_helper = new Review_View_Helper_Review();
$room_db = new Hotels_Model_DbTable_Room();

function hotel_truncate($phrase,$start_words, $max_words)
{
   $phrase_array = explode(' ',$phrase);
   if(count($phrase_array) > $max_words && $max_words > 0)
	  $phrase = implode(' ',array_slice($phrase_array, $start_words, $max_words)).'...';  
   return $phrase;
}


function getNights($sStartDate, $sEndDate)
{		
	$sStartDate =strtotime($sStartDate);
	$sEndDate = strtotime($sEndDate);
	
	$datediff = $sEndDate - $sStartDate;
	$aDays	= floor($datediff/(60*60*24));
	
	return $aDays;
}
?>
<script type="text/javascript">

$(document).ready(function() {

		calender('check_in_book', 'check_out_book');
		calender('check_out_book', 'check_in_book');
		
		<?php if(!empty($this->post_search_info) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT])){ ?>
	  		$('div.room-chart-details').show();
	  <?php } ?>
			
		$('a.toggle_desc').click(function() {
			var self = this;
			var id = $(self).attr('rel');			
			$('#room_type_desc'+id).slideToggle(500,function () { });
				return false;
		  });
		  
		  $('#book_button').click(function() {
		  	if($('#check_in_book').val() == '' || $('#check_out_book').val() == '' )
			{
				var msg = "<?php echo $this->translator->translator('hotels_check_in_out_selected_err'); ?>";
				openMsgDialog(msg);
				$('#check_in_book').focus();
			}
			else
			{				
				var tmp  = false;
				$.each($('#formBook').serializeArray(), function(i, field) {	
					if(field.name.match(/\[\]$/))
					{
						if($('select[name="'+field.name+'"]').hasClass('apartments_no'))
						{							
							if(field.value != '0' && field.value != '')
							{
								tmp = true;
							}
						}				
					}
				});
				if(tmp == true)
				{
					$('#formBook').submit();
				}
				else
				{
					var msg = "<?php echo $this->translator->translator('hotels_selected_err'); ?>";
					openMsgDialog(msg);
				}
			}
		  });	
		  
		  $('#check_availability_btn').click(function() {
		  	if($('#check_in_book').val() == '' || $('#check_out_book').val() == '' )
			{
				var msg = "<?php echo $this->translator->translator('hotels_check_in_out_selected_err'); ?>";
				openMsgDialog(msg);
				$('#check_in_book').focus();
			}
			else
			{				
				$('#formBook').attr('action', "<?php echo $this->url(array('module' => 'Hotels','controller' =>'book', 'action' => 'booking','hotels_title' => $this->escape($this->hotels_title) ),'Book-Hotel/:hotels_title',true); ?>");
				$('#formBook').submit();
			}
		  });	
		
			
});

function openMsgDialog(msg)
{
$('#dialog_container').html(msg).dialog({
			autoOpen: true,
			modal: false,
			show: 'explode',
			resizable: true,				
			buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 10000);
				  }
		});
}

function stripslashes(str) 
{
	str=str.replace(/\\'/g,'\'');
	str=str.replace(/\\"/g,'"');
	str=str.replace(/\\0/g,'\0');
	str=str.replace(/\\\\/g,'\\');
	return str;
}

function calender(id,second_id)
{
	$("#"+id).datepicker({
		showOn: 'button',
		buttonImage: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_hotel_img/calendar.png',
		buttonImageOnly: true,		
		monthNamesShort:<?php echo $this->translator->translator("common_calender_monthNamesShort"); ?>,
		monthNames:<?php echo $this->translator->translator("common_calender_monthNames"); ?>,
		dayNamesMin:<?php echo $this->translator->translator("common_calender_dayNamesMin"); ?>,
		showAnim: 'slide',
		buttonText: 'Calender',
		dateFormat:'yy-mm-dd',
		autoSize:false,
		showButtonPanel:false,
		changeMonth: true,
		changeYear: true,
		onSelect: function(dateText, inst) {
			var id_type_arr = id.split('_');
			var true_id = 		id_type_arr[0] + id_type_arr[1];			
			var currentTime = new Date();
			var currentDay = (currentTime.getDate() < 10) ? '0' + currentTime.getDate() : currentTime.getDate();
			var currentMonth = ((currentTime.getMonth() + 1) < 10) ? '0' + (currentTime.getMonth() + 1) : (currentTime.getMonth() + 1);
			var today = currentTime.getFullYear() + '-' + currentMonth + '-' + currentDay;				
			if(true_id == 'checkin')
			{
				if( (dateText != '') && ( (toTimestamp(dateText) >= toTimestamp($('#'+second_id).val())) || (toTimestamp(dateText) < toTimestamp(today)) )  )
				{					
					var msg = "<?php echo $this->translator->translator('hotels_front_page_checkin_date_err'); ?>";
					openMsgDialog(msg);					
					$('#'+id).val('');
				}
				if(!is_30dayDiff(dateText, $('#'+second_id).val()))
				{
					var msg = "<?php echo $this->translator->translator('hotels_front_page_date_difference_err'); ?>";
					openMsgDialog(msg);					
					$('#'+id).val('');
				}
			}
			else if(true_id == 'checkout')
			{
				if( (dateText != '') && ( (toTimestamp(dateText) <= toTimestamp($('#'+second_id).val())) || (toTimestamp(dateText) < toTimestamp(today)) )  )
				{
					var msg = "<?php echo $this->translator->translator('hotels_front_page_checkout_date_err'); ?>";
					openMsgDialog(msg);
					$('#'+id).val('');
				}
				if(!is_30dayDiff($('#'+second_id).val(), dateText))
				{
					var msg = "<?php echo $this->translator->translator('hotels_front_page_date_difference_err'); ?>";
					openMsgDialog(msg);					
					$('#'+id).val('');
				}
			}
		}
	});
	$("img[class='ui-datepicker-trigger']").each(function(){ 
			$(this).attr('style', '');
		 });
}

function is_30dayDiff(checkin, checkout)
{
	if(checkin != '' && checkout != '')
	{
		var checkin_arr = checkin.split('-');
		var checkout_arr = checkout.split('-');
		var checkin_obj =new Date(checkin_arr[0], (checkin_arr[1] - 1), checkin_arr[2]);
		var checkout_obj =new Date(checkout_arr[0], (checkout_arr[1] - 1), checkout_arr[2]);		
		var one_day=1000*60*60*24;
		var diff = Math.ceil((checkout_obj.getTime()-checkin_obj.getTime())/(one_day));	
		if(diff > 30)
		{
			return false;
		}	
	}
	return true;	
}

function toTimestamp(strDate){
	 var datum = Date.parse(strDate);
	 return datum/1000;
}

</script>

<div class="mod">
	<div class="booking-icon">
        <h1><?php echo $this->translator->translator('hotels_front_page_booking_change'); ?></h1>
    </div>   
    
    <div class="social">
      	<!-- AddThis Button BEGIN -->
        <div class="addthis_toolbox addthis_default_style">
        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
        <a class="addthis_button_tweet"></a>
        <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
        <a class="addthis_counter addthis_pill_style"></a>
        </div>
        <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4e89660c7edb029a"></script>
    	<!-- AddThis Button END -->
    </div>

	<div class="clear"></div>

 	<form id="formBook" name="formBook" method="post" action="<?php echo $this->url( array('module' => 'Hotels', 'controller' => 'book', 'action'     => 'invoice' ), 'Hotel-Invoice',    true); ?>">
    <?php
	if($global_conf['payment_system'] != 'On')
	{
		echo '<h1>'.$this->translator->translator('common_payment_system_disable').'</h1>';
	
	}
	else
	{
      
      if($this->view_datas)
      {
   	?>
    <div>
    	<?php 
			if(!empty($this->view_datas))
			{				
				foreach($this->view_datas as $entry)
				{
					$hotels_image_val_arr = explode(',',$entry['hotels_image']);
					$hotels_image_no = count($hotels_image_val_arr);
					
					if($this->escape($entry['hotels_primary_image']))
					{ 
						$thumb_image = 'data/frontImages/hotels/hotels_image/'.$this->escape($entry['hotels_primary_image']); 
					}
					else
					{ 
						if($this->escape($entry['hotels_image']))
						{
							
							$thumb_image = 'data/frontImages/hotels/hotels_image/'.$this->escape($hotels_image_val_arr[0]); 
						}
						else
						{
							$thumb_image = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/no_image.png'; 
						}		
					}
					if($this->group_datas['file_thumb_width'] && ($this->group_datas['file_thumb_resize_func'] == 'resizeToWidth' || $this->group_datas['file_thumb_resize_func'] == 'resize'))
					{ 
						$width = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
					}
					else
					{
						$width = '';
					} 
					if($this->group_datas['file_thumb_height'] && ($this->group_datas['file_thumb_resize_func'] == 'resizeToHeight' || $this->group_datas['file_thumb_resize_func'] == 'resize'))
					{ 
						$height = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
					} 
					else
					{
						$height = '';
					}
		?>
        <!-- Booking Option Start -->
        <div class="mod-container">
        	<h3><?php echo $this->translator->translator('hotels_list_page_book_title',$this->escape($entry['hotels_name'])); ?></h3>
            
            <div class="col">
                  <p><?php echo $this->translator->translator('hotels_list_page_search_check_in'); ?></p>
                  <input name="check_in" type="text" id="check_in_book" value="<?php echo $this->check_in_date; ?>" size="20" />
           	</div>
            
            <div class="col">
                  <p><?php echo $this->translator->translator('hotels_list_page_search_check_out'); ?></p>
                  <input name="check_out" type="text" id="check_out_book" value="<?php echo $this->check_out_date; ?>" size="20" />
            </div>
          	<input type="button" name="check_availability" id="check_availability_btn" value="<?php echo $this->translator->translator('hotels_front_page_check_availability_btn'); ?>" /> &nbsp;
        </div>
    	<!-- Booking Option End -->
        
		<div class="products-list">
        	<!-- list Header Start -->
            <div class="list-header">
            	<div class="header-row">
                	<div class="header-left">
                        <span class="title-small"><?php echo $this->escape($entry['hotels_name']); ?></span><br />
                        <span class="info"><?php if(!empty($entry['feature_distance_from_airport'])){ echo $this->escape($entry['feature_distance_from_airport']).' '.$this->translator->translator('hotels_front_page_distance'); }  ?></span>  
                    </div>
                
                	<div class="header-middle">
                        <span class="products-mark"><?php  echo $this->escape($entry['hotels_status']); ?></span>&nbsp;<span class="products-type"><?php $business_type_info = $business_type_db->getBusinessTypeInfo($entry['hotels_type']); echo $this->escape($business_type_info['business_type']); ?></span>
                    </div>
                
                	<div class="header-right">                                                
						<?php 
                            if(!empty($this->group_datas['review_id'])){ 
                            $review_no = $review_helper->getNumOfReviews($entry['id'], $this->escape($this->group_datas['review_id']));
                        ?><span class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $entry['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></span> &nbsp; <span class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($entry['hotels_title']),'tab' => 10 ),'Hotels-details/:hotels_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',htmlentities($review_no)); ?></a></span> 
                        <?php } ?>
                    </div>
                </div>
            </div>
            <!-- list Header End -->
            
            <!-- list Body Start -->
            <div class="body-container <?php echo $featured_class; ?>">
                    <div class="left-content">
                            <div class="img-wrapper">
                            	<a href="<?php echo $this->url(array('module' => 'hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($entry['hotels_title']) ),'Hotels-details/:hotels_title',true); ?>" class="preview" link="<?php echo $thumb_image; ?>" title="<?php echo $this->escape($entry['hotels_name']); ?>"><img src="<?php echo $thumb_image; ?>" <?php echo $width; ?> <?php echo $height; ?> border="0" class="thumb" /></a>

                                <div class="photo-count-container">
                                    <div class="photo-count">
                                        <a href="<?php echo $this->url(array('module' => 'hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($entry['hotels_title']),'tab' => 1 ),'Hotels-details/:hotels_title/:tab',true); ?>" title="<?php echo $this->translator->translator('hotels_front_page_hotels_click_view_listing'); ?>"><?php echo $this->translator->translator('hotels_front_page_hotels_photo_no',$hotels_image_no); ?></a>
                                    </div>
                                </div>                                            
                            </div>
                            
                            <h2>
                                <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($entry['hotels_title']) ),'Hotels-details/:hotels_title',true); ?>" class="preview" link="" title="<?php echo $this->escape($entry['hotels_name']); ?>"> <?php echo $this->escape($entry['hotels_name']); ?></a>
                            </h2>
                            
                            <div class="products-stars">
                            	<?php
										for($i = 1; $i < 6; $i++)
										{
											$hotel_stars = ($i <= $this->escape($entry['hotels_grade'])) ? '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/star-active.png" />' : '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/star-inactive.png" />';
											echo $hotel_stars.'&nbsp;';
										}
								 ?>
                            </div>
                            
                            <div class="products-desc jTruncate">
                               <?php echo hotel_truncate($this->escape(strip_tags($entry['hotels_desc'])),0,50); ?>
                            </div>
                    </div>
                         
                    <div class="right-content">
                        <ul class="products-options">	
                            <li class="availability"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($entry['hotels_title']),'tab' => 9 ),'Hotels-details/:hotels_title/:tab',true); ?>" title="Check Calendar for reservation"><?php echo $this->translator->translator('hotels_front_page_hotels_check_availability'); ?></a></li>
                            <?php
								$feature_facilities_arr = explode(',',$entry['feature_facilities']);
								if(in_array('airport transfer',$feature_facilities_arr))
								{
							?>
                            
                            <li class="airport-transfer"><?php echo $this->translator->translator('hotels_front_page_hotels_airport_transfer'); ?></li>
                            
                            <?php
								}
								$feature_sports_recreations_arr = explode(',',$entry['feature_sports_recreations']);															
								if(in_array('indoor pool',$feature_sports_recreations_arr))
								{
							?>
                            
                            <li class="swimming"><?php echo $this->translator->translator('hotels_front_page_hotels_swwimming_pool_availability'); ?></li>
    
                            <?php
								}
								if($entry['feature_pet'] == 'Pets are allowed')
								{
							?>
                            
                            <li class="pet"><?php echo $this->translator->translator('hotels_front_page_hotels_pet_allow'); ?></li>
    
                            <?php
								}															
								if(in_array('Internet Available',$feature_facilities_arr))
								{
							?>
                            
                            <li class="internet" title="<?php echo $this->translator->translator('hotels_front_page_hotels_internet_availability'); ?>"><?php echo $this->translator->translator('hotels_front_page_hotels_internet_availability'); ?></li>
                            
                            <?php
								}
								if(!empty($entry['hotels_phone']))
								{ 
							?>
                            
                            <div>
                            	<span class="products-call"><?php if(!empty($entry['hotels_phone'])){ ?><span><?php  echo $this->escape($entry['hotels_phone']); ?></span><?php } ?></span>
                            </div>
                            <?php 
                                } 
                            ?>
                        </ul>                              
                    </div>
                    
                    <!--  Availability Chart Start-->
                    <div class="room-chart-container">
            		<div class="room-chart">
                            <!-- Header Start -->
                            <div class="room-chart-row">
                                <div class="room-chart-header-col-1 details-header-col-1">
                                    <?php echo $this->translator->translator('hotels_front_page_list_head_room_type'); ?>
                                </div>
                                
                                <div class="room-chart-header-col-1 room-chart-header-col-2">
                                    <?php echo $this->translator->translator('hotels_front_page_list_head_people_per_room'); ?>
                                </div>
                                
                                <div class="room-chart-header-col-1 room-chart-header-col-3 details-header-col-3">
                                    <?php echo $this->translator->translator('hotels_front_page_list_head_price_per_room'); ?>
                                </div>
                                
                                <div class="room-chart-header-col-1 room-chart-header-col-4 details-header-col-4">
                                    <?php echo $this->translator->translator('hotels_front_page_list_head_no_apartments'); ?>
                                </div> 
                            </div>
                        	<!-- Header End -->
                    </div>
                    <?php														
						$room_type_id_arr = explode(',', $entry['room_type_id']);	
						$count = 0;												
						foreach($room_type_id_arr as $key=>$value)
						{
							$row_class = ($key % 2 == 0) ? 'room-chart-row2' : 'room-chart-row2 room-chart-row3';
							$room_type_info = $room_type_db->getRoomTypeInfo($value);
							$room_available_information_arr = explode(',', $room_type_info['room_available_information']);
							$today = date('Y-m-d');																													
							$booked = (in_array($today.';;2;;'.$this->escape($room_type_info['descount_price']),$room_available_information_arr)) ? true : false;
							$height_style = (!empty($this->post_search_info) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]))	? 'style="height:70px"' : '';
					?>
                    
                            <!-- Row-2 & Row-3 Start -->
                            <div class="room-chart chart-border">
                                    <div class="<?php echo $row_class ?>" <?php echo $height_style; ?>>
                                        <div class="room-chart-c1 details-col-1">
                                            <span><a href="javascript: void(0);" class="toggle_desc preview chart-link" rel="<?php echo $this->escape($room_type_info['id']); ?>" link="" title="<?php echo $this->escape($room_type_info['room_condition']); ?>"><?php echo $this->escape($room_type_info['room_type']); ?></a></span>
                                        </div>
                                        
                                        <div class="room-chart-c1 room-chart-c2" <?php echo $height_style; ?>>
                                            <a class="preview" link="" title="<?php echo $this->translator->translator('hotels_front_page_list_title_people',$this->escape($room_type_info['max_people'])); ?>">
                                                <?php 
                                                    if($this->escape($room_type_info['max_people']) <= 4)
                                                    {
                                                        for($i = 1; $i <= $this->escape($room_type_info['max_people']); $i++)
                                                        {
                                                            echo '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/people.png" border="0" />';
                                                        }
                                                    } 
                                                    else
                                                    {
                                                        for($i = 1; $i <= 3; $i++)
                                                        {
                                                            echo '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/people.png" border="0" />';
                                                        }
                                                        echo '<span class="person-count">'.$this->escape($room_type_info['max_people']).'</span>';
                                                    }
                                                ?>
                                            </a>
                                        </div>
                                        
                                        <div class="room-chart-c1 room-chart-c3 details-col-3" <?php echo $height_style; ?>>
                                            <span class="hotel-old-price"><?php echo $currency->getShortName().'&nbsp;'.$this->escape($room_type_info['basic_price']); ?></span>
                                            <span class="hotel-price"><?php echo $currency->getShortName().'&nbsp;'.$this->price($this->escape($room_type_info['descount_price'])); ?></span>
                                        </div>
                                        
                                        <div class="room-chart-c1 room-chart-c4 details-col-4" <?php echo $height_style; ?>>
                                            <?php																
                                                if(!empty($this->check_in_date) && !empty($this->check_out_date))
                                                {																	
                                                    $room_info = $room_db->getAvailableRooms($room_type_info['id'], $this->post_search_info);																
                                                ?>
                                                <select name="apartments_no<?php echo $count; ?>[]" id="apartments_no" class="apartments_no multi-hotel-room" multiple="multiple" size="4">
                                                    <option value="0">0</option>
                                                    <?php
														if($room_info)
														{
															foreach($room_info as $room_info_key => $room_info_arr )
															{
																$price_sum = $this->price($this->escape($room_type_info['descount_price']));
																$selected = ($this->postValues['apartments_no'.$count] && in_array($room_info_arr['room_id'], $this->postValues['apartments_no'.$count])) ? 'selected="selected"' : '';
																echo '<option value="'.$room_info_arr['room_id'].'" '.$selected.'>'.$this->escape($room_info_arr['room_name'])/*.' ('.$currency->getShortName().'&nbsp;'.$price_sum.') '.$this->translator->translator('hotels_front_page_list_head_no_apartments_per_night')*/.'</option>';
															}
														}
                                                    ?>
                                                </select><input type="hidden" name="room_type_id[]" id="room_type_id" value="<?php echo $this->escape($room_type_info['id']); ?>" /><input type="hidden" name="hotel_id[]" id="hotel_id" value="<?php echo $this->escape($entry['id']); ?>" /><br />
                                                <?php
                                                } 
                                                else
                                                {
                                                    $room_info = $room_db->getAvailableRooms($room_type_info['id'], array(Eicra_File_Constants::HOTELS_CHECK_IN => date("Y-m-d"), Eicra_File_Constants::HOTELS_CHECK_OUT => date("Y-m-d")));
                                                }
                                                    $total_room_number = $room_db->getTotalRooms($room_type_info['id']);
                                                    if((count($room_info) == $total_room_number) && $total_room_number != '0')
                                                    {
                                                        echo $this->translator->translator('hotels_front_page_list_available_type_yes');
                                                    }
                                                    else if(count($room_info) == '0' || $total_room_number == '0')
                                                    {
                                                        echo $this->translator->translator('hotels_front_page_list_available_type_no');
                                                    }
                                                    else if(count($room_info) == '1')
                                                    {
                                                        echo '<a class="preview" link="" title="'.$this->translator->translator('hotels_front_page_list_available_type_last_desc', $currency->getShortName().'&nbsp;'.$this->price($this->escape($room_type_info['descount_price']))).'">'.$this->translator->translator('hotels_front_page_list_available_type_llast',  count($room_info)).'</a>';
                                                    }
                                                    else if(count($room_info) > '1' && count($room_info) <= $total_room_number)
                                                    {
                                                        echo $this->translator->translator('hotels_front_page_list_available_type_left',  count($room_info));
                                                    }
                                            ?>
                                        </div>                                                                       
                                    </div>
                            </div>      
                            <div class="room-chart chart-border">
                                <div id="room_type_desc<?php echo $room_type_info['id']; ?>"  class="room-chart-details">
                                        <?php
                                            if(!empty($room_type_info['room_type_image']))
                                            {
                                                $room_type_im_arr = explode(',', $room_type_info['room_type_image']);
                                                foreach($room_type_im_arr as $key=>$value)
                                                {
                                        ?>
                                                    <a href="javascript:void(0)" link="data/frontImages/hotels/room_type_image/<?php echo $value; ?>" class="change_img preview" title="<?php echo $this->escape($room_type_info['room_type']); ?>" width="250" ><img src="data/frontImages/hotels/room_type_image/<?php echo $value; ?>" width="90" border="0" class="thumb"/></a> &nbsp;
                                        <?php
                                                }
                                            }
                                            echo '<div class="clear"><p>'.nl2br($this->escape($room_type_info['room_desc'])).'</p></div>';
                                        	if(!empty($this->post_search_info) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]) && $room_type_info['price_setting_type'] == '2')
											{
												if($room_info)
												{
													$totalNights = getNights($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN] , $this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]) + 1;
													foreach($room_info as $room_infos_key => $room_infos_arr )
													{	
										?>
														<div>
										<?php																
														$roomCalendar_info = $this->roomCalendar_db->getCalendarInfo($room_infos_arr['room_id'], $this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN] , $this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]);
														
														if($roomCalendar_info && ($totalNights == count($roomCalendar_info)))
														{
															
										?>	
                                        				<fieldset class="room-types">
                                                        	<legend><?php  echo $this->escape($room_infos_arr['room_name']).' ----------------- '.$currency->getShortName().'&nbsp;'.$price_sum.'&nbsp;'.$currency->getSymbol(); ?></legend>
														
																<div class="price-container">
                                                                	<div class="room-per-day">
                                                                   		<span class="mod-label"><?php echo $this->translator->translator('hotels_details_room_day'); ?></span>
                                                                   	</div>
                                                                    
                                                                    <div class="price-per-day">
                                                                    	<span class="mod-label"><?php echo $this->translator->translator('hotels_details_room_price'); ?></span>
                                                                    </div>
                                                                    
																	<?php
																		foreach($roomCalendar_info	as $roomCalendar_info_key	=> $roomCalendar_info_arr)
																		{
																	?>
																	<div class="room-per-day"><?php echo $roomCalendar_info_arr['calendar_date']; ?></div>
                                                                    <div class="price-per-day"><?php echo $currency->getShortName().'&nbsp;'.$this->price($roomCalendar_info_arr['room_price']).'&nbsp;'.$currency->getSymbol(); ?></div>
																	<?php	
																		}
																	?>
                                                               	</div>
                                                        </fieldset>
										<?php	
															/*echo '<pre>';
															print_r($roomCalendar_info);
															echo '</pre>';*/
														}
														else
														{
										?>
															<div class="room-types">
                                                            	<h6><?php  echo $this->escape($room_infos_arr['room_name']).' ----------------- '.$currency->getShortName().'&nbsp;'.$price_sum.'&nbsp;'.$currency->getSymbol(); ?></h6>
															</div>				
										<?php
														}
										?>
														</div>
										<?php
													}
												}
											}
										?>
                                </div>      
                            </div>
                            <!-- Row-2 & Row-3 End -->
						<?php
                            $count++;
                            }
                        ?>	    
                    </div>
                    <!--  Availability Chart Start-->
                                 
            </div>
            <!-- list Body End -->
               
        </div>    
	</div>
	<?php
            }
        }
    ?>

  	<?php
  	}
		if(!empty($this->check_in_date) && !empty($this->check_out_date))
		{	
	?>
		<div class="btn-container"><input type="button" name="button" id="book_button" value="<?php echo $this->translator->translator('hotels_invoice_book_now'); ?>" /></div>
	<?php
		}
	}
	?>
	</form>
</div>
<div>&nbsp;</div>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('hotels_front_page_dialog_name')); ?>"></div>