<?php
$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);
?>

<script type="text/javascript">
var settingObj = {
						form_action : {
											form_id: 'MemberForm',
											hasTinyMCE: false,
											common_msg_field_id: 'actionMessage',
											dialog_container_id:	'dialog_container',
											dialog_progressbar_id:	'progressbar'
									},
						calendar:	{
										calendar_include_time: true,	
										calendar_img_link: 'application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/calendar-small.png',
										monthNamesShort: <?php echo $this->translator->translator("common_calender_monthNamesShort"); ?>,
										monthNames:		<?php echo $this->translator->translator("common_calender_monthNames"); ?>,
										dayNamesMin:		<?php echo $this->translator->translator("common_calender_dayNamesMin"); ?>,
										buttonText:		'calendar',
										dateFormat:		'yy-mm-dd',
										dateTimeFormat:     "yyyy-MM-dd HH:mm:ss tt"
						},
						messages: {
										display				: 	'<?php echo $this->translator->translator("portfolio_pagination_messages_display", '', 'Portfolio'); ?>',
										empty				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_empty", '', 'Portfolio'); ?>',
										page				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_page", '', 'Portfolio'); ?>',
										of					:	'<?php echo $this->translator->translator("portfolio_pagination_messages_of", '', 'Portfolio'); ?>',
										itemsPerPage		:	'<?php echo $this->translator->translator("portfolio_pagination_messages_items_per_page", '', 'Portfolio'); ?>',
										first				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_first", '', 'Portfolio'); ?>',
										previous			:	'<?php echo $this->translator->translator("portfolio_pagination_messages_previous", '', 'Portfolio'); ?>',
										next				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_next", '', 'Portfolio'); ?>',
										last				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_last", '', 'Portfolio'); ?>',
										refresh				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_refresh", '', 'Portfolio'); ?>',
										
										common_msg_dialog_id 		:	'dialog_msg',
										common_confirn_dialog_id	:	'dialog-confirm',
										common_ok					:	"<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>",
										common_delete_selected		:	"<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, 'UTF-8'); ?>",
										common_cancel				:	"<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, 'UTF-8'); ?>",
										common_delete_confirm		:	"<?php echo $this->translator->translator("member_list_delete_confirm"); ?>",
										common_publish_title		:	"<?php echo $this->translator->translator("common_publish_title"); ?>",
										common_unpublish_title		:	"<?php echo $this->translator->translator("common_unpublish_title"); ?>",										
										common_publish_selected		:	"<?php echo $this->translator->translator("common_publish_selected"); ?>",
										common_unpublish_selected	:	"<?php echo $this->translator->translator("common_unpublish_selected"); ?>",
										common_publish_perm	 		:	"<?php echo $this->translator->translator("common_publish_perm"); ?>",
										common_selected_err	 		:	"<?php echo $this->translator->translator("member_selected_err"); ?>"
									}
						};
$(document).ready(function() {
	floatingbar('#floatingbar',"#button_top_bar",null);
	/********************FOR DYNAMIC COUNTRY STATE SELECTION**********************************/	
	
	$('a.reset_btn').click(function() {			
		 commonResetFormFields(settingObj);	
		 commonRemoveFormError(settingObj);	
	});
	
	$('a.add_user_btn').click(function() {
			var formData = commonGetFormData(settingObj.form_action.form_id, settingObj.form_action.hasTinyMCE);
			if(!formData.role_id){ 	formData.role_id = '<?php echo $this->selected_role_id; ?>'; }
		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Members','controller' => 'Index', 'action'     => 'add' ), 'adminrout',    true) ?>",
			  	type: 'POST',
			  	data: formData,
				beforeSend: function(){
					commonOpenLoaderDialog(settingObj);
					commonRemoveFormError(settingObj);	
				 },
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");	
					commonRefreshCaptcha(json_arr, 'div')				
					commonCloseLoaderDialog(settingObj);					
					if(json_arr.status == 'ok')
					{						
						$('#actionMessage').html(succMsgDesign(json_arr.msg));						
						commonResetFormFields(settingObj);							
					}
					else if(json_arr.status == 'errV')
					{						
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							focusFirst(json_arr.msg[i].key, json_arr.msg[i].value, i);
							commonAddFormError(json_arr.msg[i].key,json_arr.msg[i].value);							
						}
					}
					else if(json_arr.status == 'errP')
					{						
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
						commonAddFormError('confirmPassword',json_arr.msg);
					}
					else
					{						
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
				},
				error: function(xhr, status, error){
					commonCloseLoaderDialog(settingObj);	
					var msg = "Error! " + xhr.status + " " + error;
					$('#'+settingObj.form_action.common_msg_field_id).html(errMsgDesign(msg));
				}
		});
	});
	
});


/***********************************************************************UPLOAD FUNCTIONS START********************************************************/

function languageArray()
{
	var language_array = [];
	language_array['portfolio_upload_dy_text_select'] 					= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_dy_text_select", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_cancel'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_cancel", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_dropFilesHere'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_dropFilesHere", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_remove'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_remove", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_retry'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_retry", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusFailed'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusFailed", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusUploaded'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusUploaded", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusUploading'] 			= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusUploading", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_uploadSelectedFiles'] 		= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_uploadSelectedFiles", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_file_extension_dy_support'] 				= "<?php echo $this->translator->translator("portfolio_file_extension_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_no_ext_dy_support'] 					= "<?php echo $this->translator->translator("portfolio_file_no_ext_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_extension_dy_not_supportable_ext1'] 	= "<?php echo $this->translator->translator("portfolio_file_extension_dy_not_supportable_ext1", '', 'Portfolio'); ?>";
	language_array['portfolio_file_extension_dy_not_supportable_ext2']  = "<?php echo $this->translator->translator("portfolio_file_extension_dy_not_supportable_ext2", '', 'Portfolio'); ?>";
	language_array['portfolio_file_size_dy_support'] 					= "<?php echo $this->translator->translator("portfolio_file_size_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_upload_err'] 						= "<?php echo $this->translator->translator("portfolio_file_upload_err", '', 'Portfolio'); ?>";
	return language_array;
}


function successFileDecoretion(fileObj, serverData, upload_field, upload_value_field)
{
		var extension = fileObj.extension;
		var ext = extension.replace('.','');	
		
		var img_path = commonFilePath(serverData.file_path, fileObj.name);
				
		var img_code = '<div class="thumb"><img src="'+img_path+'" title="'+fileObj.name+'" width="20" height="10" /></div>';		 
		var down_link = (!isImage(fileObj)) ? '<br /><a href="'+serverData.file_path+'/'+fileObj.name+'"><?php echo $this->translator->translator("common_download", "", "Projects"); ?></a>' : '';
		
		var checked = '';
		var primary = '&nbsp;&nbsp;&nbsp;';	
		var block = 'selected_file_'+upload_value_field;
		var img_type = '';			
		switch(upload_value_field)
		{
			case 'product_thumb':	
					checked = ($('#'+upload_value_field).val() == '') ? ' checked="checked" ' : '';	
					img_type = 	($('#'+upload_value_field).val() == '') ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span><br />" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span><br />";				
					primary = '<input class="radio_style" type="radio" name="product_thumb_primary" id="product_thumb_primary" '+checked+' value="'+fileObj.name+'" title="<?php echo $this->translator->translator("gallery_primary", '', 'Gallery'); ?>" />';
				break;
			case 'product_file':
					checked = ($('#'+upload_value_field).val() == '') ? ' checked="checked" ' : '';		
					img_type = 	($('#'+upload_value_field).val() == '') ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span><br />" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span><br />";		
					primary = '<input class="radio_style" type="radio" name="product_file_primary" id="product_file_primary" '+checked+' value="'+fileObj.name+'" title="<?php echo $this->translator->translator("gallery_primary", '', 'Gallery'); ?>" />';
				break;
		}
		
		var del_link = '<a href="javascript:void(0)" class="delete_uploaded_image_link" field_name="'+upload_value_field+'" file_name="'+fileObj.name+'" file_path="'+serverData.file_path+'"><?php echo $this->translator->translator("common_delete_title"); ?></a>'+primary+down_link;
				
		if(serverData.multi)
		{		
			$('#'+block).append('<div class="upload-img box">'+img_type+'<span>'+img_code+'<br /><br />&nbsp;'+del_link+'&nbsp;</span></div>');				 
			var file_val = ($('#'+upload_value_field).val() == '') ? fileObj.name :  $('#'+upload_value_field).val()+','+fileObj.name;
		}
		else
		{
			$('#'+block).html('<div class="upload-img box">'+img_type+'<span>'+img_code+'<br /><br />&nbsp;'+del_link+'&nbsp;</span></div>');				 
			var file_val = fileObj.name;	
		}		
		$('#'+upload_value_field).val(file_val);
		deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");	
		commonImageThumbnil();	
}

function onComplete(e) {
			
}

function onCancel(e) {
	
}

function onProgress(e) {
					
}

/***********************************************************************UPLOAD FUNCTIONS END********************************************************/
</script>
<div id="container">
<?php if (!$this->allow()) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>

<div class="title-container">
	<div class="add-user"><h1><?php echo $this->translator->translator('Member_add_page_name'); ?></h1></div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Members','controller' => 'index', 'action'     => 'list' ), 'adminrout',    true) ?>"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_user_btn"><span class="icon user"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
    
</div>

<div class="content-container">
	<div id="sidebar-inner">
    	<?php echo $this->partial('index/member_menu.phtml');  ?>
    </div>
    
    <div id="content-inner">
    	<form name="MemberForm" id="MemberForm">
				<?php 
                    $file_type_arr = explode(',',$this->form_info['attach_file_type']);
                    $j= 0;
                    foreach($file_type_arr as $key => $value)
                    {
                        $file_type_arr[$j] = '*.'.$value;
                        $j++;
                    } 
                    $file_format = implode(';',$file_type_arr);	
                    $staticGroupsObj = $this->registrationForm->getDisplayGroups(); 
                    $i=1;									
                    foreach($staticGroupsObj as $staticGroup)
                    {
                        $elementsObj = $staticGroup->getElements();
                ?>
                
                <div id="actionMessage"></div>
                <div id="button_top_bar"></div>
                <fieldset class="fieldset">
                	<legend class="legend"><?php echo $this->translator->translator($staticGroup->getLegend()); ?></legend>                    
                    <div class="form">
					<?php	
						$new_file_info = new Portfolio_Controller_Helper_File();															
						foreach($elementsObj as $element)
						{
							if($element->getAttrib('admin') == '1')
							{	
								$e_name_arr = explode('_',$element->getName());																				
								$sumbol = (in_array('price',$e_name_arr,true)) ? '&nbsp;'.$currency->getSymbol() : '';	
								switch($element->getType())
								{
									case 'Zend_Form_Element_File':
												
												$image_file_arr = array();	
																							
											?>
											
											<div class="form-row">
												<div class="label <?php echo $this->escape($this->form_info['label_class']); ?>" style="<?php echo $this->escape($this->form_info['label_style']); ?>">
													<?php echo $element->getLabel(); if($element->isRequired() ){ ?><span class="required <?php echo $this->escape($this->form_info['required']); ?>" style="<?php echo $this->escape($this->form_info['star_style']); ?>">*</span><?php } ?>
												</div>
									
												<div class="field">
													<script type="text/javascript">
													$(function(){
														/**************************FILE UPLOAD START******************************/																					
														dynamicUploader("<?php echo $element->getName().'_upload'; ?>", "<?php echo $element->getName(); ?>", <?php echo $this->settings_json_info; ?>, languageArray(), "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'upload'), 'adminrout',    true) ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove'), 'adminrout',    true) ?>", false);
														/**************************FILE UPLOAD END*********************************/
													});
													</script>
													<div class="upload"><input type="file" name="<?php echo $element->getName(); ?>_upload" id="<?php echo $element->getName(); ?>_upload" /><input type="hidden" name="<?php echo $element->getName(); ?>" id="<?php echo $element->getName(); ?>" class="<?php echo $element->getName(); ?>_class empty_class" value="<?php echo $this->productInfo[$element->getName()]; ?>" /></div>
													<?php if($element->getAttrib('info')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
													
													<div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>									
												</div>
											</div>
											
											<div class="form-row">
												<div class="label"></div>
												<div class="field">	
													<span id="selected_file_<?php echo $element->getName(); ?>">
														<?php
															$dynamic_image_view = '';
															if(!empty($image_file_arr[0]))
															{													
																foreach($image_file_arr as $key => $value)
																{	
																	$show_file_path  =		$new_file_info->getFilePath($value, $this->settings_info);										
																	$img_code = ($new_file_info->isImage($value)) ? '<div class="thumb"><img src="'.$show_file_path.'" title="'.$value.'" width="20" height="10" /></div>' : '<div class="thumb"><img src="'.$show_file_path.'" title="'.$value.'" width="20" height="10" /></div>' ;
																	$del_link	=	'<a href="javascript:void(0)" class="delete_uploaded_image_link" field_name="'.$element->getName().'" file_name="'.$value.'" file_path="'.$this->settings_info[$this->settings_info['file_path_field']].'">'.$this->translator->translator("common_delete_title").'</a>';
																	$dynamic_image_view .= '<div class="upload-img box"><span>'.$img_code.'<br /><br />&nbsp;&nbsp;'.$del_link.'&nbsp;&nbsp;&nbsp;</span></div>';
																}															
															}
															echo $dynamic_image_view;
													 	?>
													</span>
												</div>
											</div>
											<?php	
								
										break;
									case 'Zend_Form_Element_MultiCheckbox':
									case 'Zend_Form_Element_Radio':
											
										?>
												<div class="form-row">
													<div class="label <?php echo $this->escape($this->form_info['label_class']); ?>" style="<?php echo $this->escape($this->form_info['label_style']); ?>">
														<?php echo $element->getLabel(); if($element->isRequired() ){ ?><span class="required <?php echo $this->escape($this->form_info['star_class']); ?>" style="<?php echo $this->escape($this->form_info['star_style']); ?>">*</span><?php } ?>
													</div>
										
													<div class="field">
														<div class="autos-features"><?php  echo $element; ?></div>
														<?php if($element->getAttrib('info')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
														<div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
													</div>
												</div>
										<?php	
											
										break;
									default:
																										
										?>
										
										<div class="form-row">
											<div class="label <?php echo $this->escape($this->form_info['label_class']); ?>" style="<?php echo $this->escape($this->form_info['label_style']); ?>" >
												<?php echo $element->getLabel(); if($element->isRequired() ){ ?><span class="required <?php echo $this->escape($this->form_info['star_class']); ?>" style="<?php echo $this->escape($this->form_info['star_style']); ?>">*</span><?php } ?>
											</div>
								
											<div class="field">
												<?php 										
														$id_f = $element->getAttrib('id');
														$id_arr = explode('_',$id_f);
														if(in_array('date',$id_arr))
														{
														?>
														<script type="text/javascript">
															$(function() {
																commonCalendar('<?php echo $id_f; ?>', settingObj, settingObj.calendar.calendar_include_time);
															});
														</script>
														<?php
														}
														if($element->getType() == 'Zend_Form_Element_MultiCheckbox')
														{
															echo '<div class="upload">'.$element.$sumbol.'</div>';
														}
														else
														{
															echo $element.$sumbol;
														}															
												?>
											
												<?php if($element->getAttrib('info')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($element->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>	
												<div class="input-errors" id="<?php echo $element->getName().'_err'; ?>"></div>
											</div>
										</div>
										
										<?php
													
										break;										
								}
							}
						}
					?>
                    </div>
                </fieldset>
                
                <?php
                    $group_no = ($this->escape($this->form_info['group_no'])) ? (int)$this->escape($this->form_info['group_no']) : 1;
                        
                        $i++;
                    }
                ?>
		</form>
    </div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Members','controller' => 'index', 'action'     => 'list' ), 'adminrout',    true) ?>"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_user_btn"><span class="icon user"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
    
</div>

<div  id="floatingbar">
	<h1><?php echo $this->translator->translator('Member_add_page_name'); ?></h1>
	<div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Members','controller' => 'index', 'action'     => 'list' ), 'adminrout',    true) ?>"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_user_btn"><span class="icon user"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

<div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('Member_add_page_name')); ?>"></div>
<div id="dialog_container" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>"><div id="progressbar" ></div></div>
<?php endif; ?>
</div>