<!DOCTYPE html>
<?php 
$locale = (Eicra_Global_Variable::getSession()->sess_lang) ? Eicra_Global_Variable::getSession()->sess_lang : 'en_US';
$locale_arr = explode('_', $locale);
$locale_direction = Eicra_Global_Variable::getSession()->site_direction;
?>
<html dir="<?php echo $locale_direction; ?>" lang="<?php echo $locale_arr[0]; ?>"> 
<head>  
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<base href="<?php echo $this->serverUrl().$this->baseUrl(); ?>/"  />
<link rel="shortcut icon" href="<?php $global_conf = Zend_Registry::get('global_conf'); echo $global_conf['admin_favicon']; ?>" />
<?php echo $this->headMeta(); ?>
<?php  $this->headTitle()->set($this->translator->translator('administrator_control_title'));
  $front = Zend_Controller_Front::getInstance(); 
  $auth = Zend_Auth::getInstance ();
   if ($auth->hasIdentity ())
	{
		$globalIdentity = $auth->getIdentity ();
		$role_id = $globalIdentity->role_id;
		$role_info = new Members_Model_DbTable_Role();
		$roleName =  $role_info->getRoleInfo($role_id);						
		$role = $roleName['role_name'];
		$this->headTitle()->headTitle($this->translator->translator('administrator_controls_title',$role), 'SET');			
	}
  
echo html_entity_decode( $this->headTitle(), ENT_QUOTES, "UTF-8");
echo $this->partial('head/headscript.phtml'); 
?>      
</head>
<body>
<div id="wrapper">
	<?php if($this->popup != 'popup'){echo $this->layout()->render('header'); }  ?>			
    <section id="main-container">
		<?php
         if ($auth->hasIdentity () && $front->getRequest()->getModuleName() == 'Administrator' && $front->getRequest()->getActionName() == 'index')
        {
            if($this->popup != 'popup')
            {
        ?>
            <div id="sidebar"><?php echo $this->partial('partial/vertical_menu_tree.phtml'); ?></div>
        <?php
            }
        }
        ?>
                      
        <div class="<?php if($this->popup != 'popup' && $front->getRequest()->getModuleName() == 'Administrator' && $front->getRequest()->getActionName() == 'index'){ ?>use-sidebar sidebar-at-right<?php } ?>" id="main_layout">
        	<?php echo $this->layout()->content; ?>
        </div>
  	</section>
	<div><?php if($this->popup != 'popup'){ echo $this->layout()->render('footer'); } ?></div>
</div>
</body>
</html>