<?php
$version = Zend_Registry::get('version');  
$menu_db_class = new Menu_Model_DbTable_Menu(); $menu_name = ($this->menu_id)? $menu_db_class->getMenuName($this->menu_id) : 'Frontend-Login';  
$this->headTitle()->headTitle($menu_name,'SET');
$front_template = Zend_Registry::get('front_template');
$returnLink = Eicra_Global_Variable::getSession()->returnLink;
$redirect_msg = $this->translator->translator("member_loggin_redirecting");
Eicra_Global_Variable::getSession()->returnLink = '';
$this->logindetails->username->setAttrib('class', 'icon user-icon');
$this->logindetails->password->setAttrib('class', 'icon pass-icon');
$global_conf = Zend_Registry::get('global_conf');
?>
<script type="text/javascript">
$(document).ready(function() {

	$('a.reset_btn').click(function() {			
		 resetFields();	
		 removeError();	
	});
	
	function openMsgDialog(msg)
	{
		$('#dialog_msg').html(msg).dialog({
			autoOpen: true,
			modal: true,
			show: 'explode',
			resizable: true,				
			buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
			open: function(event, ui)
				 {
					setTimeout(function() 
					{									
						if($('#' + event.target.id).dialog('isOpen'))
						{
							$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
						}
					}, 10000);
				  }
		});
	}
	
	function openLoaderDialog()
	{
		$('#dialog_container').dialog({
					autoOpen: true,
					modal: true,
					show: 'explode',
					resizable: false,				
					open: function(event, ui)
						 {
						 	$("#progressbar").progressbar({
								value:100
				
							});							
						  }
				});
	}
	
	function closeLoaderDialog()
	{
		$('#dialog_container').dialog('option','hide','explode').dialog('close');
	}
	
	
	function resetFields()
	{
		$( "#AdminLogin" )[ 0 ].reset();
	}
		
	function removeError()
	{
		$('#actionMessage').html('');
		
		var filename = '';
		var filevalue = '';		
		$.each($('#AdminLogin').serializeArray(), function(i, field) {	
				if(field.name.match(/\[\]$/))
				{
					var filearr = field.name.split('[]');
					filename = filearr[0];					
				}
				else if(field.name.match(/\[input\]$/))
				{
					var filearr = field.name.split('[input]');
					filename = filearr[0];					
				}
				else
				{
					filename 	= 	field.name;
				} 			
				$('#'+filename).removeClass('ui-state-error');	
				$('#'+filename+'-input').removeClass('ui-state-error');			
				$('#'+filename+'_err').html('');
				$('span.input-errors').html('');							
		});				
	}
	
	function addError(key,errMsg)
	{
		var err_id = key+'_err';
		var field_name = key;
		$('#'+field_name+'-input').addClass('ui-state-error');
		$('#'+field_name).addClass('ui-state-error');
		$('#'+err_id).append(errMsg);
	}
	
	function getFormData()
	{
		var fieldObj = {};
		$.each($('#AdminLogin').serializeArray(), function(i, field) {		 					
				fieldObj[field.name] = field.value;										
		});
		return fieldObj;
	}
	
	$('input.logout_btn').click(function() {
		
		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Members','controller' => 'frontend', 'action'     => 'logout' ), 'default',    false) ?>",
			  	type: 'POST',
				beforeSend: function(){						
						removeError();
						openLoaderDialog();				
					 },
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");	
														
					if(json_arr.status == 'ok')
					{
						$('#actionMessage').html(succMsgDesign(json_arr.msg));	
						$('#login_box').css('display','');	
						$('#logout_box').css('display','none');																									
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							addError(json_arr.msg[i].key,json_arr.msg[i].value);							
						}
					}
					else
					{
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
					closeLoaderDialog();
					refreshCaptcha(json_arr);	
				}
		});
	});
	
	$('input.login_send_btn').click(function() {
		removeError();
		openLoaderDialog();
		var formData = getFormData();
		
		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Members','controller' => 'frontend', 'action'     => 'auth' ), 'default',    false) ?>",
			  	type: 'POST',
			  	data: formData,
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");	
					refreshCaptcha(json_arr);									
					if(json_arr.status == 'ok')
					{
						$('#actionMessage').html(succMsgDesign(json_arr.msg));	
						resetFields();
						var mem_link = 'Members-Dashboard';
						$('#mem_link').attr('href',mem_link);	
						$('#login_box').css('display','none');	
						$('#logout_box').css('display','');	
						<?php if(!empty($returnLink)){	?>
							$('#actionMessage').html(succMsgDesign(json_arr.msg+'<?php echo $redirect_msg; ?>'));	
							document.location.href='<?php echo $returnLink;  ?>';
						<?php } ?>															
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							addError(json_arr.msg[i].key,json_arr.msg[i].value);							
						}
					}
					else
					{
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
					closeLoaderDialog();
					
				}
		});
	});

	$('input.login_send_btn').keypress(function() {
		removeError();
		openLoaderDialog();
		var formData = getFormData();
		
		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Members','controller' => 'frontend', 'action'     => 'auth' ), 'default',    false) ?>",
			  	type: 'POST',
			  	data: formData,
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");
					refreshCaptcha(json_arr);										
					if(json_arr.status == 'ok')
					{
						$('#actionMessage').html(succMsgDesign(json_arr.msg));	
						resetFields();
						var mem_link = 'Members-Dashboard';
						$('#mem_link').attr('href',mem_link);	
						$('#login_box').css('display','none');	
						$('#logout_box').css('display','');	
						<?php if(!empty($returnLink)){	?>
							$('#actionMessage').html(json_arr.msg+'<?php echo $redirect_msg; ?>');	
							document.location.href='<?php echo $returnLink;  ?>';
						<?php } ?>															
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							addError(json_arr.msg[i].key,json_arr.msg[i].value);							
						}
					}
					else
					{
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
					closeLoaderDialog();
				}
		});
	});
	
	
	function refreshCaptcha(json_arr)
	{
		if(json_arr.captcha && json_arr.captcha.status && json_arr.captcha.status == 'ok')
		{
			var captcha_name = json_arr.captcha.captcha_name;
			$('input[name="'+captcha_name+'[id]"]').prev('img').attr('src', json_arr.captcha.ImgUrl+json_arr.captcha.id+json_arr.captcha.Suffix);
			$('input[name="'+captcha_name+'[id]"]').val(json_arr.captcha.id);
			$('#'+captcha_name+'_err').html('');		
		}
	}
	
	$('a.refresh_token').click(function() {		
		var self = this;
		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Members','controller' => 'frontend', 'action'     => 'token' ), 'default',    false) ?>",
			  	type: 'POST',
				beforeSend: function(){	
						var option = '<img src="data/adminImages/loginImages/token_ani.gif" border="0" width="24" height="24"  title="Refreshing Token" />';						
						$(self).html(option);			
					 },
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");										
					if(json_arr.status == 'ok')
					{
						$('#token').val(json_arr.token);
						$(self).html('<img src="data/adminImages/loginImages/token.png" border="0" width="24" height="24"  title="Click To Refresh Token" />');
					}
				}
		});
	});	
		
});
</script>
<div id="content-full-width" class="mod member-signup">
	<div class="signup-header">
        <h1><?php echo $this->escape($global_conf['site_name']); ?></h1>
        <div class="member-login">
            <div class="login-box">
                <h2><?php echo $this->translator->translator('Member_frontend_login_title'); ?></h2>
                <hr />
                <div class="clear">&nbsp;</div>
                <div id="actionMessage"><?php echo $this->logindetails->getDescription(); ?></div>
                <div id="login_box" style="display:<?php if(Zend_Auth::getInstance()->hasIdentity()){ ?>none;<?php }?>">
                    <form id="AdminLogin" name="AdminLogin" method="post" action="">                    
                        <p><?php  echo $this->logindetails->username->getLabel(); ?></p>
                        <?php  echo $this->logindetails->username;?>
                        <span class="input-errors" id="username_err"></span>
                        
                        <p class="label"><?php  echo $this->logindetails->password->getLabel(); ?></p>
                        <?php  echo $this->logindetails->password;?>
                        <span class="input-errors" id="password_err"></span>
                        
                        <?php if($this->logindetails->login_captcha){ ?><br />
                        <p><?php  echo $this->logindetails->login_captcha->getLabel();	?></p>
                        <div class="captcha">
                            <?php  echo $this->logindetails->login_captcha;?>
                            <div class="form-field-info"><div class="ui-widget ui-helper-clearfix"><div class="ui-state-default ui-corner-all info-class" title="<?php echo $this->escape($this->logindetails->login_captcha->getAttrib('info')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div></div>
                            <span class="input-errors" id="login_captcha_err"></span>
                        </div>
                        <?php } ?>
                        <?php echo $this->logindetails->token; ?>
                        
                        <div class="clear"><input type="button" name="login" value="<?php echo $this->translator->translator('Member_frontend_login_button'); ?>" class="login_send_btn"/></div>
                       	<hr />
						<div class="clear"></div>
                        <a href="Forget-Password"><?php echo $this->translator->translator('Member_frontend_forget_pass_link'); ?></a>
                    </form>
        		</div>
                
                <div id="logout_box" style="display:<?php if(!Zend_Auth::getInstance()->hasIdentity()){	?>none;<?php }?>">
            <input type="button" name="login" value="<?php echo $this->translator->translator('Member_frontend_logout_button'); ?>" class="logout-btn logout_btn" />
            <?php $globalIdentity = Zend_Auth::getInstance()->getIdentity (); $mem_link = 'Members-Dashboard'; ?>                
           	<div><a href="<?php echo $mem_link; ?>"  id="mem_link"><?php echo $this->translator->translator('Member_frontend_login_area'); ?></a></div>
        </div> 
            </div>
        </div>
    </div>
    
    <div class="signup-bottom-bar">
        <span><?php echo $this->translator->translator('members_login_page_header_title', $this->escape($global_conf['site_name'])); ?></span>
    </div>
    
	<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/login.jpg" border="0" class="lock">
    <div class="info">
        <p><?php echo $this->translator->translator('members_login_page_body_desc_title_1'); ?></p>
        <?php
			$members_login_page_body_list_1 = $this->translator->translator('members_login_page_body_list_1');
			$members_login_page_body_list_1_arr = explode('||', $members_login_page_body_list_1);
			if($members_login_page_body_list_1_arr && $members_login_page_body_list_1_arr[0])
			{
		?>
        <ul>
        	<?php				
				foreach($members_login_page_body_list_1_arr as $key => $value)
				{
					echo '<li>'.$this->escape($value).'</li>';
				}				
			?>
        </ul>
        <?php
			}
		?>
        <br>
        
        <p><?php echo $this->translator->translator('members_login_page_body_desc_title_2'); ?></p>
        <?php
			$members_login_page_body_list_2 = $this->translator->translator('members_login_page_body_list_2', $this->escape($global_conf['site_name']));
			$members_login_page_body_list_2_arr = explode('||', $members_login_page_body_list_2);
			if($members_login_page_body_list_2_arr && $members_login_page_body_list_2_arr[0])
			{
		?>
        <ul>
        	<?php				
				foreach($members_login_page_body_list_2_arr as $key => $value)
				{
					echo '<li>'.$this->escape($value).'</li>';
				}				
			?>
        </ul>
        <?php
			}
		?>
        
        <br />
        <div>
        <?php
			$members_login_page_body_list_3 = $this->translator->translator('members_login_page_body_list_3');
			$members_login_page_body_list_3_arr = explode('||', $members_login_page_body_list_3);
			if($members_login_page_body_list_3_arr && $members_login_page_body_list_3_arr[0])
			{
		?>
        
        	<?php				
				foreach($members_login_page_body_list_3_arr as $key => $value)
				{
					echo ''.$this->escape($value).'';
				}				
			?>
        
        <?php
			}
		?>
        </div>
        <a class="join" href="Register"><?php echo $this->translator->translator('members_login_page_register_btn'); ?></a>
    </div>
</div>

<div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg','Message'); ?>"></div>
<div id="dialog_container" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
	<div id="progressbar" ></div>	
</div>