<?php	
	echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/jquery.scrollTo.js');		
	$this->articleForms->setEditor($this->serverUrl().$this->baseUrl());
	$this->articleForms->getEditor();
	
	$auth = Zend_Auth::getInstance ();	
	$u_role_id = ($auth->hasIdentity ()) ? $auth->getIdentity()->role_id : '' ;
	$u_user_id = ($auth->hasIdentity ()) ? $auth->getIdentity()->user_id : '' ;							
?>
	
<style type="text/css">
	.CodeMirror, .codemirror-ui-clearfix{width:602px;}
</style>	

<script type="text/javascript">
var settingObj = {
						tab_base_link: '',
						form_action : {
											form_id: 'formArticle',
											hasTinyMCE: true,									
											common_msg_field_id: 'actionMessage',
											dialog_container_id:	'dialog_container',
											dialog_progressbar_id:	'progressbar',
											extra_field_for_reset: [],
											extra_function_for_reset: function(){												
												if(editor){ editor.mirror.setValue($('#article_content').val()); }	
											}
									},						
						messages: {
										display				: 	'<?php echo $this->translator->translator("portfolio_pagination_messages_display", '', 'Portfolio'); ?>',
										empty				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_empty", '', 'Portfolio'); ?>',
										page				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_page", '', 'Portfolio'); ?>',
										of					:	'<?php echo $this->translator->translator("portfolio_pagination_messages_of", '', 'Portfolio'); ?>',
										itemsPerPage		:	'<?php echo $this->translator->translator("portfolio_pagination_messages_items_per_page", '', 'Portfolio'); ?>',
										first				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_first", '', 'Portfolio'); ?>',
										previous			:	'<?php echo $this->translator->translator("portfolio_pagination_messages_previous", '', 'Portfolio'); ?>',
										next				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_next", '', 'Portfolio'); ?>',
										last				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_last", '', 'Portfolio'); ?>',
										refresh				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_refresh", '', 'Portfolio'); ?>',
										
										common_msg_dialog_id 		:	'dialog_msg',
										common_confirn_dialog_id	:	'dialog-confirm',
										common_ok					:	"<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>",
										common_delete_selected		:	"<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, 'UTF-8'); ?>",
										common_cancel				:	"<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, 'UTF-8'); ?>",										
										common_publish_title		:	"<?php echo $this->translator->translator("common_publish_title"); ?>",
										common_unpublish_title		:	"<?php echo $this->translator->translator("common_unpublish_title"); ?>",										
										common_publish_selected		:	"<?php echo $this->translator->translator("common_publish_selected"); ?>",
										common_unpublish_selected	:	"<?php echo $this->translator->translator("common_unpublish_selected"); ?>",
										common_publish_perm	 		:	"<?php echo $this->translator->translator("common_publish_perm"); ?>"
									}
						};
$(document).ready(function() {
	floatingbar('#floatingbar',"#button_top_bar",null);
	/**********Scrolling Tools Start****************/
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	
	$('#toc a').click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		$.scrollTo( this.hash, 1500, { easing:'swing' });
		$(this.hash).find('span.message').text( this.title );
		return false;
	});
	
	$('span.top-go a').click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen		
		$.scrollTo( this.hash, 1500, { easing:'swing' });
		return false;
	});	
	/**********Scrolling Tools END****************/
	
	$('a.reset_btn').click(function() {
		commonResetFormFields(settingObj);	
		commonRemoveFormError(settingObj);	
	});		
		
	$('a.edit_article_btn').click(function() {	
			
			var formData = commonGetFormData(settingObj.form_action.form_id, settingObj.form_action.hasTinyMCE);
			formData.article_id = '<?php echo $this->article_id; ?>';
			formData.article_content	=	(tinyMCE.get('article_content')) ? tinyMCE.get('article_content').getContent() :  editor.mirror.getValue();					
			var menu_list	=	$("select[name='menu_list']").val();
			
			if(menu_list != null && menu_list != '')
			{
				formData.menu_list = menu_list;	
				confirmFunction(formData);
			}
			else
			{
				editFunction(formData);
			}
	});
	
	function editFunction(formData)
	{
		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Articles','controller' => 'Backend', 'action'     => 'edit' ), 'adminrout',    true) ?>",
			  	type: 'POST',
			  	data: formData,
				beforeSend: function(){						
						commonRemoveFormError(settingObj);	
						commonOpenLoaderDialog(settingObj);				
					 },
				success: function(response){					
					var json_arr = eval("("+response+")");
					commonCloseLoaderDialog(settingObj);
					if(json_arr.status == 'ok')
					{						
						$('#actionMessage').html(succMsgDesign(json_arr.msg));						
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							focusFirst(json_arr.msg[i].key, json_arr.msg[i].value, i);
							commonAddFormError(json_arr.msg[i].key,json_arr.msg[i].value);
						}
					}
					else
					{
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
				},
				error: function(xhr, status, error){
					commonCloseLoaderDialog(settingObj);
					var msg = "Error! " + xhr.status + " " + error;
					$('#actionMessage').html(errMsgDesign(msg));
				}
		});
	}
	
	function confirmFunction(formData)
	{
		$("#dialog-confirm").html("<?php echo addslashes($this->translator->translator('article_list_save_confirm')); ?>").dialog({
						resizable: false,
						width:400,
						height:'auto',
						modal: true,
						show: 'fade',
						hide: 'explode',
						buttons: {
								'<?php echo html_entity_decode($this->translator->translator("common_ok"), ENT_QUOTES, "UTF-8"); ?>': function() {
								$(this).dialog('close');
								editFunction(formData);														
							},
						'<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, "UTF-8"); ?>': function() {
								$(this).dialog('close');							
							}
						}
					});	
	}
});
</script>
<div id="container">
<?php if (!$this->allow() || ($auth->getIdentity()->access_other_user_article != '1' && $u_user_id != $this->entry_by)) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : ?>

<div class="title-container">
	<div class="article-edit"><h1><?php echo $this->translator->translator('article_edit_page_name'); ?></h1></div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Articles','controller' => 'Backend', 'action'     => 'list' ), 'adminrout',    true) ?>"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="edit_article_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

<div class="content-container">
	<div id="sidebar-inner">
    	<?php echo $this->partial('backend/article_menu.phtml');  ?>
        
        <?php if($this->popup != 'popup'){ ?>
        <div>&nbsp;</div>
        <div id="nav-tree">
    		<div class="nav-header"><div class="nav-title"><?php echo $this->translator->translator('menu_list_selection','', "Menu"); ?></div></div>
    		<div id="categoryTree" class="nav-body treebody" >
           		<select name="menu_list" id="menu_list" multiple="multiple" size="35">
                    <option value="" style="font-style:italic;font-weight:bold;"><?php echo $this->translator->translator('articles_link_no_menu'); ?></option>
                    <?php echo Menu_View_Helper_SubMenu::getAllMenuList($this->article_id); ?>
                </select>
            </div>
       	</div>
        <?php } ?>
    </div>
    
    <div id="topGo">
    	<div id="content-inner">
    		<form name="formArticle" id="formArticle" method="post">
            	<div id="actionMessage"></div>
                <div id="button_top_bar"></div>
                <div id="generalInfo">
                    <fieldset class="fieldset">
                        <legend class="legend"><?php echo $this->translator->translator('article_menu_general_info'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                        <input type="hidden" id="last_id" name="last_id" value="" /><input type="hidden" id="article_name_field" name="article_name_field" value="" /><?php if($this->popup != 'popup'){ ?><span class="button ui-widget-content-1 create_menu_btn" style="visibility:hidden;"><a href=""><span class="icon add"><?php echo $this->translator->translator('article_page_create_menu_link'); ?></span></a></span><?php } ?>
                        <div class="form">
                            <div class="form-row">
                                <div class="label article-label">
                                    <?php echo $this->articleForms->article_name->getLabel(); if($this->articleForms->article_name->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field article-field">
                                    <?php  echo $this->articleForms->article_name;  ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->articleForms->article_name->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="article_name_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label article-label">
                                    <?php echo $this->articleForms->article_title->getLabel(); if($this->articleForms->article_title->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field article-field">
                                    <?php  echo $this->articleForms->article_title;  ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->articleForms->article_title->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="article_title_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label article-label">
                                    <?php echo $this->articleForms->article_content->getLabel(); if($this->articleForms->article_content->isRequired()){  ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field article-field">
                                    <div class="left-float"><?php echo $this->articleForms->article_content; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->articleForms->article_content->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink"><a href="javascript:void(0);" class="loaderLink_class" rel="wysiwyg,article_content"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" ></a></span>
                                    <div class="input-errors" id="article_content_err"></div>
                                </div>
                            </div>
						</div>
					</fieldset>
				</div>
                
                <div id="metadata">
                	<fieldset class="fieldset">
                        <legend class="legend"><?php echo $this->translator->translator('article_menu_meta_info'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                        <div class="form">
                            <div class="form-row">
                                <div class="label article-label">
                                    <?php echo $this->articleForms->article_meta_title->getLabel(); if($this->articleForms->article_meta_title->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field article-field">
                                    <?php echo $this->articleForms->article_meta_title; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->articleForms->article_meta_title->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="article_meta_title_err"></div>
                                </div>
                         	</div>
                            
                            <div class="form-row">
                                <div class="label article-label">
                                    <?php echo $this->articleForms->article_meta_key->getLabel();  if($this->articleForms->article_meta_key->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field article-field">
                                    <?php echo $this->articleForms->article_meta_key; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->articleForms->article_meta_key->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="article_meta_key_err"></div>
                                </div>
                         	</div>
                            
                            <div class="form-row">
                                <div class="label article-label">
                                    <?php echo $this->articleForms->article_meta_desc->getLabel();  if($this->articleForms->article_meta_desc->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field article-field">
                                    <?php echo $this->articleForms->article_meta_desc; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->articleForms->article_meta_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="article_meta_desc_err"></div>
                                </div>
                         	</div>
                      	</div>
                	</fieldset>
                </div>
			</form>
		</div>
	</div>
</div>

<div id="dialog_container" style="display:none;" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
	<div id="progressbar" ></div>	
</div>
<div id="dialog-confirm" title="<?php echo $this->translator->translator('common_confirmation',$this->translator->translator('common_save')); ?>"></div>

<div id="floatingbar">
	<h1><?php echo $this->translator->translator('article_edit_page_name'); ?></h1>
    <div class="button-container">
    	<span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Articles','controller' => 'Backend', 'action'     => 'list' ), 'adminrout',    true) ?>"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
      	<span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
      	<span class="button ui-widget-content-1"><a href="javascript: void(0);" class="edit_article_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>	
</div>
<?php endif; ?>	
</div>
<script type="text/javascript">
	openCodeMirror('article_content');
</script>