<?php
$permission_arr = array('preview_enable'	=>	$this->allow('preview','backend','Articles'), 'add_enable' => $this->allow('add','backend','Articles'), 'edit_enable' => $this->allow('edit','backend','Articles'), 'publish_enable' => $this->allow('publish','backend','Articles'), 'delete_enable' => $this->allow('delete','backend','Articles'));
echo $this->headLink()->setStylesheet($this->baseUrl().'/vendor/scripts/colorbox/example1/colorbox.css');
echo $this->headScript()->setFile($this->baseUrl().'/vendor/scripts/colorbox/jquery.colorbox.js', '');
?>
<script type="text/javascript">
$(document).ready(function() {
	
	floatingbar('#floatingbar',"#button_top_bar",null);
	
	var settingObj = {
						grid_id : 'grid',
						dest_url : "<?php echo $this->url(); ?>",
						pageSize : '<?php echo Eicra_Global_Variable::getSession()->viewPageNum; ?>',
						page: '<?php echo ($this->posted_data['page']) ? $this->posted_data['page'] : ''; ?>',	
						calendar: {
							culture: "<?php echo str_ireplace('_', '-', $locale); ?>",
							value: ''
						},					
						search_action: {
							search_form_id : 'searchForm',
							search_form_btn : 'search_btn',
							hasTinyMCE 	: false
						},
						common_action : {
								permission_arr : {
										publish_enable 	: 	'<?php echo $permission_arr['publish_enable']; ?>',
										delete_enable	:	'<?php echo $permission_arr['delete_enable']; ?>',
										featured_enable	:	'<?php echo $permission_arr['featured_enable']; ?>'
								},
								publish_dest_url			:	"<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'publish' ), 'adminrout',    true); ?>",
								publish_dest_data_field 	: 	['article_id', 'article_name', 'paction'],
								publish_active_icon_link	:	"application/modules/Administrator/layouts/scripts/images/tools/published.gif",
								publish_deactive_icon_link	:	"application/modules/Administrator/layouts/scripts/images/tools/unpublished.gif",
								
								delete_dest_url				:	"<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'delete' ), 'adminrout',    true); ?>",
								delete_dest_data_field 		: 	['article_id', 'article_name'],
																
								publish_multi_dest_url		:	"<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'publishall' ), 'adminrout',    true) ?>",
								delete_multi_dest_url		:	"<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'deleteall' ), 'adminrout',    true); ?>",
								
								toolbar_button_loader		:	'<span class="icon loader"></span>',
								ajax_loader_link			:	"application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif",
						
								multi_action	: [ ]
						},
						order_action: {
								order_dest_data_field		:	['article_id', 'order'],
								
								order_up_dest_url			:	"<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'up' ), 'adminrout',    true) ?>",
								order_up_ajax_loader_link	:	"application/modules/Administrator/layouts/scripts/images/tools/up-animation.gif",
								order_down_dest_url			:	"<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'down' ), 'adminrout',    true) ?>",
								order_down_ajax_loader_link	:	"application/modules/Administrator/layouts/scripts/images/tools/down-animation.gif",
								
								order_all_dest_data_field	:	['article_id_arr', 'order_arr'],
								order_all_dest_url			:	"<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'orderall' ), 'adminrout',    true) ?>",
								order_all_ajax_loader_link	:	"application/modules/Administrator/layouts/scripts/images/loader/order_all_loader.gif"
						},
						search_data : {},
						batch:		false,
						editable:	false,
						scrollable: false,
						detailInit:	false,
						dataBound: function(e) {									
								var self = this;		
								$("a[rel='preview_btn']").colorbox({width:"96%", height:"98%",slideshow:false, transition:"fade"});															
																								
								<?php if($this->auth->getIdentity()->allow_change_order_listing == '1') : ?>
								self.thead.find("th[data-field='order']").unbind('click');
								self.thead.find("th[data-field='order']>a").attr('href', 'javascript:void(0)');
								<?php endif; ?>								                      
                        },
						filterable:{
						  extra: true,
						  messages: {
							  info: "<?php echo $this->translator->translator("portfolio_filter_messages_info", '', 'Portfolio'); ?>", // sets the text on top of the filter menu
							  filter: "<?php echo $this->translator->translator("portfolio_filter_messages_filter", '', 'Portfolio'); ?>", // sets the text for the "Filter" button
							  clear: "<?php echo $this->translator->translator("portfolio_filter_messages_clear", '', 'Portfolio'); ?>", // sets the text for the "Clear" button
					  
							  // when filtering boolean numbers
							  isTrue: "<?php echo $this->translator->translator("portfolio_filter_messages_isTrue", '', 'Portfolio'); ?>", // sets the text for "isTrue" radio button
							  isFalse: "<?php echo $this->translator->translator("portfolio_filter_messages_isFalse", '', 'Portfolio'); ?>", // sets the text for "isFalse" radio button
					  
							  //changes the text of the "And" and "Or" of the filter menu
							  and: "<?php echo $this->translator->translator("portfolio_filter_messages_and", '', 'Portfolio'); ?>",
							  or: "<?php echo $this->translator->translator("portfolio_filter_messages_or", '', 'Portfolio'); ?>"
						  },
						  operators: {
							  string: {
								  startswith: "<?php echo $this->translator->translator("portfolio_filter_messages_operators_string_startswith", '', 'Portfolio'); ?>",
								  contains: "<?php echo $this->translator->translator("portfolio_filter_messages_operators_string_contains", '', 'Portfolio'); ?>",
								  doesnotcontain: "<?php echo $this->translator->translator("portfolio_filter_messages_operators_string_doesnotcontain", '', 'Portfolio'); ?>",
								  endswith: "<?php echo $this->translator->translator("portfolio_filter_messages_operators_string_endswith", '', 'Portfolio'); ?>",
								  eq: "<?php echo $this->translator->translator("portfolio_filter_messages_operators_string_eq", '', 'Portfolio'); ?>",
								  neq: "<?php echo $this->translator->translator("portfolio_filter_messages_operators_string_neq", '', 'Portfolio'); ?>"
							  },
							  number: {
								  eq:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_number_eq", '', 'Portfolio'); ?>",
								  neq:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_number_neq", '', 'Portfolio'); ?>",
								  gte:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_number_gte", '', 'Portfolio'); ?>",
								  gt:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_number_gt", '', 'Portfolio'); ?>",
								  lte:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_number_lte", '', 'Portfolio'); ?>",
								  lt:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_number_lt", '', 'Portfolio'); ?>"
							  },
							  date: {
								  gte:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_date_gte", '', 'Portfolio'); ?>",
								  gt:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_date_gt", '', 'Portfolio'); ?>",
								  lte:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_date_lte", '', 'Portfolio'); ?>",
								  lt:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_date_lt", '', 'Portfolio'); ?>",
							  	  eq:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_date_eq", '', 'Portfolio'); ?>",
								  neq:	"<?php echo $this->translator->translator("portfolio_filter_messages_operators_date_neq", '', 'Portfolio'); ?>"
							  },
							  enums: {
									eq: "<?php echo $this->translator->translator("portfolio_filter_messages_operators_enum_eq", '', 'Portfolio'); ?>",
									neq: "<?php echo $this->translator->translator("portfolio_filter_messages_operators_enum_neq", '', 'Portfolio'); ?>"
							  }
						  }
						},
						model: {
                                    fields: {
                                        article_id: { type: "number" },
                                        article_name: { type: "string" },
										full_name: { type: "string" },
                                        order: { type: "number", editable: false },
                                        article_date: { type: "date" },
										article_status: { type: "enums", editable: false },
										common_action: { editable: false }
                                    }
                                },					
						column_fields: [
											{ field:"checkAll", headerTemplate: '<input type="checkbox" name="checkAll" id="checkAll" class="checkAll_btn"  <?php if(!$permission_arr['publish_enable'] && !$permission_arr['delete_enable']) : ?>disabled="disabled"<?php endif; ?> />',	template: '<input type="checkbox" value="${article_id}" class="check_btn" <?php if(!$permission_arr['publish_enable'] && !$permission_arr['delete_enable']) : ?>disabled="disabled"<?php endif; ?> />' , width: 28, filterable: false, sortable: false, columnMenu: false},  // For Header : #= Selected ? checked="checked" : "" #       For Body :  # (checkAll) ? checked="checked" :  ""  #  # if(checkAll){ # checked # } #
											{ 
												field: "article_id", 		
												title: 	"<?php echo $this->translator->translator('common_id'); ?>", 
												width: 50, 
												filterable: { 
													ui: function(element) {
														element.kendoNumericTextBox({
															culture: "<?php echo str_ireplace('_', '-', $locale); ?>",
															format: "0",
															min: 1,															
															placeholder: "<?php echo html_entity_decode($this->translator->translator("portfolio_numeric_text_box_messages_placeholder", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>",
															upArrowText: "<?php echo html_entity_decode($this->translator->translator("portfolio_numeric_text_box_messages_upArrowText", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>",
															downArrowText: "<?php echo html_entity_decode($this->translator->translator("portfolio_numeric_text_box_messages_downArrowText", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>"
														});
													}
												}  
											},											
											{ field: "article_name",  title: "<?php echo $this->translator->translator('article_list_page_title'); ?>", template: '<?php if ($permission_arr['edit_enable']) : ?># if(edit_enable){ # <a href="<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'edit', 'article_id' => ''), 'adminrout',    true) ?>${article_id}">${article_name}</a> # }else{ # ${article_name} # } #<?php else : ?>${article_name}<?php endif; ?>' },
											{ field: "full_name",  title: "<?php echo $this->translator->translator('common_entry_by'); ?>" },
											{ 	
												field: "linked_menu",  
												title: "<?php echo $this->translator->translator('articles_join_with_menu'); ?>", 
												template: '#= linked_menu #',
												filterable: false, 
												sortable: false,
												columnMenu: false 
											},
											{ 
												field: "order", 		
												title:	"<?php echo $this->translator->translator('common_order'); ?>", 
												width: 110,												
												headerTemplate: '<?php echo html_entity_decode($this->translator->translator('common_order'), ENT_QUOTES, 'UTF-8'); if($this->auth->getIdentity()->allow_change_order_listing == '1') : ?>&nbsp;&nbsp;<a href="javascript: void(0);" class="all_order_btn"><img src="application/modules/Administrator/layouts/scripts/images/tools/save.png" border="0" /></a><?php endif; ?>',
												template: '<?php if($this->auth->getIdentity()->allow_change_order_listing == '1') : ?><input type="text" size="1" name="order" id="order" class="order_text" value="${order}" />&nbsp;<a href="javascript: void(0);" rel="${article_id}" class="up_btn"><img src="application/modules/Administrator/layouts/scripts/images/tools/up-arrow.gif" border="0" /></a>&nbsp;<a href="javascript: void(0);" rel="${article_id}" class="down_btn"><img src="application/modules/Administrator/layouts/scripts/images/tools/down-arrow.gif" border="0" /></a><?php else : ?>${order}<?php endif; ?>',
												attributes:{ 'align' : 'center' },
												filterable: { 
													ui: function(element) {
														element.kendoNumericTextBox({
															culture: "<?php echo str_ireplace('_', '-', $locale); ?>",
															format: "0",
															min: 0,															
															placeholder: "<?php echo html_entity_decode($this->translator->translator("portfolio_numeric_text_box_messages_placeholder", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>",
															upArrowText: "<?php echo html_entity_decode($this->translator->translator("portfolio_numeric_text_box_messages_upArrowText", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>",
															downArrowText: "<?php echo html_entity_decode($this->translator->translator("portfolio_numeric_text_box_messages_downArrowText", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>"
														});
													}
												} 
											},
											{ 
												field: "article_date", 	
												title:	"<?php echo $this->translator->translator('common_date'); ?>",  
												format: "{0:MM/dd/yyyy}", 
												template: '<div title="<strong><?php echo html_entity_decode($this->translator->translator('common_date'), ENT_QUOTES, 'UTF-8'); ?> : </strong>${article_date_format}<br /><strong><?php echo html_entity_decode($this->translator->translator('common_entry'), ENT_QUOTES, 'UTF-8'); ?> : </strong>${username}">#= kendo.toString(article_date,\'dd/MM/yyyy\') #</div>',
												width: 80, 
												filterable: { 
													ui: function(element) {
														kendoDateTimeCalendar(element, settingObj);
													}
												}
											},
											{ 	
												field: "article_status", 	
												title:	"<?php echo $this->translator->translator('common_status'); ?>", 
												width: 80,
												template: '<a href="javascript:void(0);" class="publish_btn"  rel="${article_id}_${publish_status_article_name}_#= (article_status == 1) ? \'unpublish\' : \'publish\' #"><img src="#= (article_status == 1) ? \'application/modules/Administrator/layouts/scripts/images/tools/published.gif\' : \'application/modules/Administrator/layouts/scripts/images/tools/unpublished.gif\' #" title="#= (article_status == 1) ? \'<?php echo html_entity_decode($this->translator->translator('common_unpublish_title'), ENT_QUOTES, 'UTF-8'); ?>\' : \'<?php echo html_entity_decode($this->translator->translator('common_publish_title'), ENT_QUOTES, 'UTF-8'); ?>\' #" alt="#= (article_status == 1) ? \'<?php echo html_entity_decode($this->translator->translator('common_unpublish_title'), ENT_QUOTES, 'UTF-8'); ?>\' : \'<?php echo html_entity_decode($this->translator->translator('common_publish_title'), ENT_QUOTES, 'UTF-8'); ?>\' #" border="0" /></a>',
												attributes:{ 'align' : 'center' } ,
												filterable: { 
													ui: function(element) {
														element.kendoDropDownList({
															dataSource: [ { Id: 0, Title: "<?php echo html_entity_decode($this->translator->translator("common_unpublished_language"), ENT_QUOTES, 'UTF-8'); ?>" }, { Id: 1, Title: "<?php echo html_entity_decode($this->translator->translator("common_published_language"), ENT_QUOTES, 'UTF-8'); ?>" } ],
															dataTextField: "Title",
    														dataValueField: "Id",
															optionLabel: "<?php echo html_entity_decode($this->translator->translator("common_select"), ENT_QUOTES, 'UTF-8'); ?>"
														});
													}
												}
											},
											{ 
												field: "common_action",	
												title:	"<?php echo $this->translator->translator('common_action'); ?>", 
												width: 120, 
												template:	'# if(link_menu){ # <a href="<?php echo $this->url(array('module'=> 'Menu','controller'=>'backend', 'action'=>'add', 'article_id' => ''),'adminrout',true) ?>${article_id}"><img src="application/modules/Administrator/layouts/scripts/images/tools/hotels/link.png" title="<?php echo $this->translator->translator('articles_link_to_menu'); ?>" alt="<?php echo $this->translator->translator('articles_link_to_menu'); ?>"  border="0" /></a>&nbsp;&nbsp; # } #'+
															'<?php if ($permission_arr['edit_enable']) : ?># if(edit_enable){ # <a href="<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'edit', 'article_id' => ''), 'adminrout',    true) ?>${article_id}"><img src="application/modules/Administrator/layouts/scripts/images/tools/edit.png" title="<?php echo html_entity_decode($this->translator->translator('common_edit_title'), ENT_QUOTES, 'UTF-8'); ?>" alt="<?php echo html_entity_decode($this->translator->translator('common_edit_title'), ENT_QUOTES, 'UTF-8'); ?>" border="0" /></a> # } #<?php endif; ?>'+
															'&nbsp;<?php if ($permission_arr['delete_enable']) : ?>&nbsp;<a href="javascript:void(0);" class="delete_btn"  rel="${article_id}_${publish_status_article_name}"><img src="application/modules/Administrator/layouts/scripts/images/tools/delete.png" title="<?php echo html_entity_decode($this->translator->translator('common_delete_title'), ENT_QUOTES, 'UTF-8'); ?>" alt="<?php echo html_entity_decode($this->translator->translator('common_delete_title'), ENT_QUOTES, 'UTF-8'); ?>"  border="0" /></a><?php endif; ?>'+
															'&nbsp;&nbsp;&nbsp;<?php if ($permission_arr['preview_enable']) : ?><a rel="preview_btn" href="<?php echo $this->url( array('module'=> 'Articles', 'controller' => 'backend', 'action'     => 'preview', 'article_id' => '' ), 'adminrout',    true) ?>${article_id}" ><img src="application/modules/Administrator/layouts/scripts/images/tools/preview.gif" border="0" title="<?php echo $this->translator->translator('common_preview_title'); ?>" /></a><?php endif; ?>', 
												attributes:{ 'align' : 'center' } ,
												filterable: false, 
												sortable: false,
												columnMenu: false 
											}
										],
						columnMenu:	{
							columns: true,
							messages: {
									sortAscending: "<?php echo html_entity_decode($this->translator->translator("portfolio_column_menu_messages_sort_ascending", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>",
									sortDescending: "<?php echo html_entity_decode($this->translator->translator("portfolio_column_menu_messages_sort_descending", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>",
									filter: "<?php echo html_entity_decode($this->translator->translator("portfolio_column_menu_messages_filter", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>",
									columns: "<?php echo html_entity_decode($this->translator->translator("portfolio_column_menu_messages_columns", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>"
								}
						},
						messages: {
										display				: 	'<?php echo $this->translator->translator("portfolio_pagination_messages_display", '', 'Portfolio'); ?>',
										empty				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_empty", '', 'Portfolio'); ?>',
										page				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_page", '', 'Portfolio'); ?>',
										of					:	'<?php echo $this->translator->translator("portfolio_pagination_messages_of", '', 'Portfolio'); ?>',
										itemsPerPage		:	'<?php echo $this->translator->translator("portfolio_pagination_messages_items_per_page", '', 'Portfolio'); ?>',
										first				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_first", '', 'Portfolio'); ?>',
										previous			:	'<?php echo $this->translator->translator("portfolio_pagination_messages_previous", '', 'Portfolio'); ?>',
										next				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_next", '', 'Portfolio'); ?>',
										last				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_last", '', 'Portfolio'); ?>',
										refresh				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_refresh", '', 'Portfolio'); ?>',
										
										common_msg_dialog_id 		:	'dialog_msg',
										common_confirn_dialog_id	:	'dialog-confirm',
										common_ok					:	"<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>",
										common_delete_selected		:	"<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, 'UTF-8'); ?>",
										common_cancel				:	"<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, 'UTF-8'); ?>",
										common_delete_confirm		:	"<?php echo $this->translator->translator("article_list_delete_confirm"); ?>",
										common_publish_title		:	"<?php echo $this->translator->translator("common_publish_title"); ?>",
										common_unpublish_title		:	"<?php echo $this->translator->translator("common_unpublish_title"); ?>",										
										common_publish_selected		:	"<?php echo $this->translator->translator("common_publish_selected"); ?>",
										common_unpublish_selected	:	"<?php echo $this->translator->translator("common_unpublish_selected"); ?>",
										common_publish_perm	 		:	"<?php echo $this->translator->translator("common_publish_perm"); ?>",
										common_perm_err				:	"<?php echo $this->translator->translator("common_perm_err"); ?>",
										common_selected_err	 		:	"<?php echo $this->translator->translator("article_selected_err"); ?>"
									}
					};
	commonGrid(settingObj);			
});
</script>
<script type="text/javascript">
$(document).ready(function() {
	$("a[rel='preview_btn']").colorbox({width:"98%", height:"98%",slideshow:false, transition:"fade"});	
});
</script>
<?php if (!$this->allow('list')) : ?>
<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
</div>
<?php else : ?>
<div id="container">

<div class="title-container">
	<div class="article"><h1><?php if($this->draft_page == '0'){ echo $this->translator->translator('article_list_draft_page_name'); }else{ echo $this->translator->translator('article_list_page_name'); } ?></h1></div>
    
    <div class="button-container">
        <?php if ($permission_arr['add_enable']) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url(array('module'=> 'Articles','controller'=>'Backend', 'action'=>'add'),'adminrout',true);?>"><span class="icon add"><?php echo $this->translator->translator('common_add'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($permission_arr['publish_enable']) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="publish_all" rel="publish"><span class="icon publish"><?php echo $this->translator->translator('common_publish_selected'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($permission_arr['publish_enable']) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="publish_all" rel="unpublish"><span class="icon unpublish"><?php echo $this->translator->translator('common_unpublish_selected'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($permission_arr['delete_enable']) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
<div id="button_top_bar"></div>

<div class="content-container">
	<p>
		<?php echo $this->translator->translator('article_list_tips_desc'); ?>
    </p>
    <br />
	      
    <div class="chart">
        <div <?php if($locale_direction == 'rtl'){ ?> class="k-rtl" <?php } ?>>
           <div id="grid"></div>  
       </div>
    </div>  
 	
</div>

<div id="floatingbar">
	<h1><?php if($this->draft_page == '0'){ echo $this->translator->translator('article_list_draft_page_name'); }else{ echo $this->translator->translator('article_list_page_name'); } ?></h1>
    
    <div class="button-container">
        <?php if ($permission_arr['add_enable']) : ?>
        <span class="button  ui-widget-content-1"><a href="<?php echo $this->url(array('module'=> 'Articles','controller'=>'Backend', 'action'=>'add'),'adminrout',true);?>"><span class="icon add"><?php echo $this->translator->translator('common_add'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($permission_arr['publish_enable']) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="publish_all" rel="publish"><span class="icon publish"><?php echo $this->translator->translator('common_publish_selected'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($permission_arr['publish_enable']) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="publish_all" rel="unpublish"><span class="icon unpublish"><?php echo $this->translator->translator('common_unpublish_selected'); ?></span></a></span>
        <?php endif; ?>
        <?php if ($permission_arr['delete_enable']) : ?>
        <span class="button  ui-widget-content-1"><a href="javascript: void(0);" class="delete_all"><span class="icon delete"><?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, "UTF-8"); ?></span></a></span>
        <?php endif; ?>
    </div>
</div>
</div>
<?php endif; ?>	
<div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('article_list_page_name')); ?>"></div>
<div id="dialog-confirm" title="<?php echo $this->translator->translator('common_confirmation',$this->translator->translator('common_delete')); ?>"></div>