<?php
$maximum_stars_digit = $this->translator->translator('maximum_stars_digit');
$version = Zend_Registry::get('version'); 
$tab_base_link = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
$front_template = Zend_Registry::get('front_template');

echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/gallery/jquery.ad-gallery.js'); 
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/raty/js/jquery.raty.js');
echo $this->headLink()->setStylesheet($this->baseUrl().'/js/jquery/gallery/jquery.ad-gallery.css');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/jquery.scrollTo.js');

if(!empty($this->view_datas['HotelSummary']['name'])){ $this->headMeta()->setName('keywords',$this->view_datas['HotelSummary']['name']); }
if(!empty($this->view_datas['HotelSummary']['name'])) { $this->headMeta()->setName('description',$this->view_datas['HotelSummary']['name']); }
if(!empty($this->view_datas['HotelSummary']['name'])) { $this->headTitle()->headTitle($this->escape($this->view_datas['HotelSummary']['name']),'SET'); }

function isnot_int($hotels_agent)
{
	$r = true;			
	if(is_numeric($hotels_agent))
	{ 
		if(is_int((int)$hotels_agent))
		{
			$r = false;
		}				
	}
	return $r;
}
$global_conf = Zend_Registry::get('global_conf');
// 1ist param options are : like, inline, plus_minus, horizontal, triangle
$vote = new Vote_Controller_Helper_ShowVoteButton('inline','hotels_page' );

$auth = Zend_Auth::getInstance ();
$hasIdentity = $auth->hasIdentity ();

?>
<style type="text/css">
.dialogPosition{position:fixed;}	
</style>
<script type="text/javascript">
function scrolling(class_name)
{
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	$('a.'+class_name).click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		var rel = $(this).attr('rel');
		var id_arr = rel.split('-');
		var id_no = parseInt(id_arr[1]);
		$('#tabs').tabs({ active: --id_no });
		$.scrollTo( rel , 1500, { easing:'swing' });		
		return false;
	});
}

function bookScrolling()
{
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	
	$('a.book_btn').click(function() {
	 	
		var tmp  = false;
		$.each($('#bookHotel').serializeArray(), function(i, field) {	
			if(field.name.match(/\[\]$/))
			{
				if($('select[name="'+field.name+'"]').attr('class') == 'apartments_no multi-hotel-room')
				{
					if(field.value != '0' && field.value != '')
					{
						tmp = true;
					}
				}				
			}			
		});
		if(tmp == true)
		{
			$('#bookHotel').submit();
		}
		else
		{	
			var msg = "<?php echo $this->translator->translator('hotels_selected_err'); ?>";
			openMsgDialog(msg);	
							
			var self = this;			
			var rel = $(self).attr('rel');
			var id_arr = rel.split('-');
			var id_no = parseInt(id_arr[1]);
			$('#tabs').tabs({ active: --id_no });
			$.scrollTo( rel , 1500, { easing:'swing' });			
			return false;			
		}
	 });
}

function changeImageScrolling()
{
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	
	 
	 $("a.change_img").click(function(){
			var self = this;			
			var src = $(self).attr('link');			
			$("div.ad-image").children("img:nth-child(1)").attr('src',src);							
			$.scrollTo( '#gallery' , 1500, { easing:'swing' });			
			return false;
		});
}

 $(function() {				
	var galleries = $('.ad-gallery').adGallery({
					slideshow: {
                       enable: true,
                       autostart: true,
                       speed: 5000,
                       start_label: 'Start',
                       stop_label: 'Stop',
                       stop_on_scroll: true,
                       countdown_prefix: '(',
                       countdown_sufix: ')',
                       onStart: false,
                       onStop: false
                     }
					 });
	$('#switch-effect').change(
	  function() {
		galleries[0].settings.effect = $(this).val();
		return false;
	  }
	);
	$('#toggle-slideshow').click(
	  function() {
		galleries[0].slideshow.toggle();
		return false;
	  }
	);
	$('#toggle-description').click(
	  function() {
		if(!galleries[0].settings.description_wrapper) {
		  galleries[0].settings.description_wrapper = $('#descriptions');
		} else {
		  galleries[0].settings.description_wrapper = false;
		}
		return false;
	  }
	);
  });
$(function() {		
		
		$("#tabs").tabs({ 
				active: 0, 
				select: function(event, ui) { 
				
				} 		
		}).find(".ui-tabs-nav").sortable({axis:'xy'});
		
		$("#matchTabs").tabs().find(".ui-tabs-nav").sortable({axis:'xy'});
		
		changeImageScrolling();
			
	});
	
	

function openMsgDialog(msg)
{
	$('#dialog_container').html(msg).dialog({
		autoOpen: true,
		modal: false,
		show: 'fade',
		resizable: 'false',	
		dialogClass: 'dialogPosition',			
		buttons: { "Ok": function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } },
		open: function(event, ui)
			 {
				setTimeout(function() 
				{									
					if($('#' + event.target.id).dialog('isOpen'))
					{
						$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
					}
				}, 10000);
			  }
	});
}


$(document).ready(function() {
	function stripslashes(str) 
	{
		str=str.replace(/\\'/g,'\'');
		str=str.replace(/\\"/g,'"');
		str=str.replace(/\\0/g,'\0');
		str=str.replace(/\\\\/g,'\\');
		return str;
	}
	
	$('a.toggle_desc').click(function() {
		var self = this;
		var id = $(self).attr('rel');
		
		$('#room_type_desc'+id).slideToggle(500,function () {
			
		});
		return false;
	  });
	  
	 bookScrolling();	
	
	$('a.save_hotels_btn').click(function() {
		var self = this;
		var id = $(self).attr('rel');
		$.ajax({
			  url: "<?php echo $this->url( array('module' =>'Hotels','controller' => 'frontend', 'action'     => 'save' ), 'adminrout',    true) ?>",
			  type: 'POST',
			  data: { id: id },
			  beforeSend: function(){						
						$(self).html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" border="0" height="15" />');	
					 },
			  success: function(response){
				//alert(response);
				var json_arr = eval("("+response+")");							
				if(json_arr.status == 'ok')
				{
					openMsgDialog(json_arr.msg);
				}
				else
				{
					openMsgDialog(json_arr.msg);
				}
				$(self).html('<?php echo $this->translator->translator("hotels_front_page_save_hotels"); ?>');
			  }
		});
	});	
	
	$('a.print_btn').click(function (event){
	
			var width = 1200;
    		var height = 700;
			var left = parseInt((screen.availWidth/2) - (width/2));
   			var top = parseInt((screen.availHeight/2) - (height/2));
			var windowSizeArray = [ "width="+width+",height="+height+",left="+left+",top="+top+"screenX=" + left + ",screenY=" + top + ",scrollbars=yes",
									"width="+width+",height="+height+",scrollbars=yes" ];
			var url = "<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'print','hotels_title' => $this->escape($this->view_datas['hotels_title']) ),'Hotels-print/:hotels_title',true); ?>";
			var windowName = "popUp";
			var windowSize = windowSizeArray[$(this).attr("rel")];

			window.open(url, windowName, windowSize);

			event.preventDefault();

		});
	
});
function raty (id, start_point)
{
	$('#'+id+'_star').raty({
	  path: 'js/jquery/raty/img/',						  
	  hintList:		"<?php echo $this->translator->translator("common_rating_hintList"); ?>",
	  number:     <?php $hint_arr = explode(', ',str_replace('[', '', str_replace(']', '', $this->translator->translator('common_rating_hintList')))); echo count($hint_arr); ?>,
	  start: start_point,
	  readOnly:   true					 
	});
}
</script>
	<?php 
	
	if($this->errorMassage){	
	
		print_r ($this->verboseMessage);
		echo  '<br />'.$this->errorMassage ;	

	} 
		
	$roomList = $this->room_collection['HotelRoomAvailabilityResponse'] ;
	
	if( ! empty ($this->view_datas)) : ?>
    <div class="mod mod-details">
        <h1><?php echo $this->escape($this->view_datas['HotelSummary']['name']); ?></h1>
        <div class="clear">&nbsp;</div>
        <!-- Hotel Info Start -->
        <div class="products-info">
                <div class="products-stars">
                    <?php							
                        for($i = 1; $i < $maximum_stars_digit; $i++)
                        {
                            $hotel_stars = ($i <= $this->escape($this->view_datas['HotelSummary']['hotelRating'])) ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-inactive.png' border='0' />";
                            echo $hotel_stars.'&nbsp;';
                        }
                    ?>
                </div>
                            
                <ul class="products-options">
                    <li class="room"><?php echo $this->translator->translator('hotels_api_expedia_number_of_rooms').' : '.$this->escape($this->view_datas['HotelDetails']['numberOfRooms']); ?></li>
                    <li class="floor"><?php echo $this->translator->translator('hotels_api_expedia_number_of_fooms').' : '.$this->escape($this->view_datas['HotelDetails']['numberOfFloors']); ?></li>                    
                    <li class="checkin"><?php echo $this->translator->translator('hotels_list_page_search_check_in').$this->escape($this->view_datas['HotelDetails']['checkInTime']); ?></li>
                    <li class="checkout"><?php echo $this->translator->translator('hotels_list_page_search_check_out').$this->escape($this->view_datas['HotelDetails']['checkOutTime']); ?></li>                 
                	<li class="pet"><?php echo $this->escape($this->view_datas['HotelDetails']['propertyInformation']); ?></li>					  
                </ul>
        </div>
        
        <div class="products-info right">
            <span class="products-status">
                <span class="products-mark"><?php  echo $this->translator->translator('High Rate :'); ?></span>&nbsp; <span class="products-type"><?php echo strtoupper($this->view_datas['HotelSummary']['highRate']); ?></span>
                <span class="products-mark"><?php  echo $this->translator->translator('Low Rate :'); ?></span>&nbsp; <span class="products-type"><?php echo strtoupper($this->view_datas['HotelSummary']['lowRate']); ?></span>
            </span>   
            <div class="clear"></div>
               	<?php if(!empty($this->view_datas['HotelSummary']['tripAdvisorRating'])){ $review_no = (!empty($this->view_datas['HotelSummary']['tripAdvisorRating'])) ? htmlentities($this->view_datas['HotelSummary']['tripAdvisorRating']) : htmlentities('0'); ?> &nbsp; <a href="javascript:void(0);" class="review_btn" rel="#tabs-11"><div class="travelnow-details-review"><?php echo $this->translator->translator('hotels_api_expedia_details_common_rating_no',$review_no); ?></div></a><?php } ?>
            	<div class="clear"></div>
                <?php 
                    $reviewNumber = $roomList['tripAdvisorReviewCount'];
                    if (! empty($reviewNumber)){
                ?>		
                <div class="clear"></div>
                <span class="products-review-count travelnow-review-count">
                    <a href="javascript:void(0);"><?php echo $this->escape($reviewNumber) . '  ' . $this->translator->translator('hotels_api_expedia_room_reviews'); ?></a>
                </span> 
               	<div class="clear"></div>
                
              	<img src="<?php echo $roomList['tripAdvisorRatingUrl']?>" >
                
                <?php } ?>
        </div>
        <!-- Hotel Info End -->
        <div class="clear"></div>
        <!-- Hotel Details Middle Tab Start -->
           
        <div class="products-middle-tab-area">
            <!-- Slide Show Start -->
            <div class="products-slideshow">
                <?php	
                    $photos_arr = $this->view_datas['HotelImages']['@size'];
                    $hotels_image_val_arr = $this->view_datas['HotelImages']['HotelImage'];
                ?> 
            
                <div id="container">
                    <div id="gallery" class="ad-gallery">
                      <div class="ad-image-wrapper"></div>
                      <div class="ad-controls"></div>
                        <div class="ad-nav">
                            <div class="ad-thumbs">
                              <ul class="ad-thumb-list">									
                                <?php		
                                                                                    
                                    foreach($hotels_image_val_arr as $key=>$value)
                                    {								
                                  ?>
                                  <li>
                                  <a href="<?php echo $value['url']; ?>">
                                    <img src="<?php echo $value['thumbnailUrl']; ?>"  width="70" height="50" title="<?php echo $value['caption']; ?>" alt="<?php echo $value['caption']; ?>"  class="image0">
                                    </a>
                                  </li>
                                <?php											
                                    }
                                ?>					
                                </ul>
                            </div>
                        </div>
                    </div>
                
                    <div class="switch">
                      <select id="switch-effect">
                        <option value="slide-hori">Slide horizontal</option>
                        <option value="slide-vert">Slide vertical</option>
                        <option value="resize">Shrink/grow</option>
                        <option value="fade">Fade</option>
                        <option value="">None</option>
                        </select> <a href="#" id="toggle-slideshow">Toggle slideshow</a> |
                      <a href="#" id="toggle-description">Toggle description outside image</a>
                    </div>
                </div>
            </div>
            <!-- Slide Show End -->
            
            <!-- Hotel Match Start -->
            <div class="match-container">
                <div id="matchTabs">
                    <ul>
                      <li><a href="<?php echo $tab_base_link; ?>#matchTabs-1"><?php echo $this->translator->translator('hotels_front_page_hotels_photo_no', '<span class="photo-no">'. $photos_arr. '</span>'); ?></a></li>
                      <li><a href="<?php echo $tab_base_link; ?>#matchTabs-2"><?php echo $this->translator->translator('hotels_front_page_Title_summary'); ?></a></li>					
                     <!-- <li><a href="#matchTabs-3"><?php //echo $this->translator->translator('hotels_front_page_match_agent'); ?></a></li>-->
                      
                    </ul>
                    <div class="match-tab-container travelnow-details" id="matchTabs-2">                              
                    	<div class="products-feature">
                            <div class="products-details">
                                <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('hotels_front_page_Title_summary'); ?></h4></div>
                                <div class="summary-label"><?php echo $this->translator->translator('hotels_block_simple_search_label_city'); ?></div>
                                <div class="summary-value"><?php echo $this->escape($this->view_datas['HotelSummary']['city']); ?></div>
                                
                                <div class="summary-label"><?php echo $this->translator->translator('hotels_list_page_search_postcode'); ?></div>
                                <div class="summary-value"><?php echo $this->escape($this->view_datas['HotelSummary']['postalCode']); ?></div>
                                
                                <div class="summary-label"><?php echo $this->translator->translator('hotels_list_page_search_country'); ?></div>
                                <div class="summary-value"><?php echo $this->escape($this->view_datas['HotelSummary']['countryCode']); ?></div>
                                
                                <div class="summary-label"><?php echo $this->translator->translator('hotels_front_page_hotels_location'); ?></div>
                                <div class="summary-value"><?php echo $this->escape($this->view_datas['HotelSummary']['address1']).', '.$this->escape($this->view_datas['HotelSummary']['locationDescription']); ?></div>
                                
                                <div class="summary-label"><?php echo $this->translator->translator('latitude'); ?></div>
                                <div class="summary-value"><?php echo $this->escape($this->view_datas['HotelSummary']['latitude']); ?></div>
                                
                                <div class="summary-label"><?php echo $this->translator->translator('longitude'); ?></div>
                                <div class="summary-value"><?php echo $this->escape($this->view_datas['HotelSummary']['longitude']); ?></div>     
                            </div>
                        </div>
                    </div>
                    
                   <!--<div class="match-tab-container" id="matchTabs-3">
                    
                    </div>-->
                    <div class="match-tab-container" id="matchTabs-1">
                      <h4><?php echo $this->translator->translator('hotels_front_page_Title_images'); ?></h4>	
                    
                        <?php				
                        
                            $i = 1;
                            foreach($hotels_image_val_arr as $key => $value)
                            {
                        ?>              
                        <div>
                            <a href="javascript:void(0);" class="change_img preview" link="<?php echo $value['url']; ?>" width="<?php echo $value['width']; ?>" title="<?php echo $value['caption']; ?>"><img src="<?php echo $value['thumbnailUrl']; ?>"  border="0" class="thumb additional-thumb"/></a>  
                        </div>
                        <?php                                   
                             $i++;
                          }
                        ?>                
                    </div>
                </div>
                
            </div>
            <!-- Hotel Match End -->
                
        </div>
        
        <!-- Hotel Bottom Tab Start -->
        
        <div id="tabs" class="travelnow-tab">
                <ul>
                    <li><a href="<?php echo $tab_base_link; ?>#tabs-1"><?php echo $this->translator->translator('hotels_api_expedia_details_page_room_details'); ?></a></li>
                    <li><a href="<?php echo $tab_base_link; ?>#tabs-2"><?php echo $this->translator->translator('hotels_front_page_hotels_features'); ?></a></li>
                    <li><a href="<?php echo $tab_base_link; ?>#tabs-3"><?php echo $this->translator->translator('hotels_front_page_hotels_profile'); ?></a></li>
                    <li><a href="<?php echo $tab_base_link; ?>#tabs-4"><?php echo $this->translator->translator('hotels_front_page_hotels_policy'); ?></a></li>
                    <li><a href="<?php echo $tab_base_link; ?>#tabs-5"><?php echo $this->translator->translator('hotels_api_expedia_details_page_tab5'); ?></a></li>
                    <li><a href="<?php echo $tab_base_link; ?>#tabs-6"><?php echo $this->translator->translator('hotels_location'); ?></a></li>	 					
                    <!--<li><a href="#tabs-7"><?php //echo $this->translator->translator('hotels_api_expedia_details_page_tab6'); ?></a></li>-->
                    <!--<li><a href="#tabs-8"><?php //echo $this->translator->translator('hotels_front_page_hotels_map'); ?></a></li>
                    <li><a href="#tabs-9"><?php //echo $this->translator->translator('hotels_front_page_hotels_financing'); ?></a></li>
                    
                    <li><a href="#tabs-10"><?php //echo $this->translator->translator('hotels_front_page_hotels_available'); ?></a></li>-->
                    
                </ul>
                
                <div id="tabs-1">
                    <!-- Tab Detail Start -->
                        
                        <div class="check-container">
                            <div class="check-label"><?php echo 'Check In : '; ?></div>
                            <div class="check-value"><?php echo $roomList['arrivalDate'] ?></div>
                            
                            <div class="check-label"><?php echo 'Check Out : '; ?></div>
                            <div class="check-value"><?php echo $roomList['departureDate'] ?></div>
                        </div>
                        
                        <div class="room-chart-container">
                        <form name="bookHotel" id="bookHotel" action="<?php echo $this->url(array('module' => 'Hotels','controller' =>'book', 'action' => 'booking','hotels_title' => $this->escape($this->view_datas['hotels_title']) ),'Book-Hotel/:hotels_title',true) ?>" method="post">                    
                            
                            <div class="room-chart">
                                
                                <!-- Header Start -->
                                    <div class="room-chart-row">
                                        <div class="room-chart-header-col-1 details-header-col-1">
                                            <?php echo $this->translator->translator('hotels_front_page_list_head_room_type'); ?>
                                        </div>
                                        
                                        <div class="room-chart-header-col-1 room-chart-header-col-2">
                                            <?php echo $this->translator->translator('hotels_front_page_list_head_people_per_room'); ?>
                                        </div>
                                        
                                        <div class="room-chart-header-col-1 room-chart-header-col-2">
                                            <?php echo $this->translator->translator('hotels_api_expedia_details_tbl_fee_Includes'); ?>
                                        </div>
                                        
                                        
                                        <div class="room-chart-header-col-1 room-chart-header-col-3 details-header-col-3">
                                            <?php echo $this->translator->translator('hotels_front_page_list_head_price_per_room'); ?>
                                        </div>
                                        
                                        <div class="room-chart-header-col-1 room-chart-header-col-4 details-header-col-4">
                                            <?php echo $this->translator->translator('common_action'); ?>
                                        </div> 
                                    </div>
                                <!-- Header End -->
                            </div>
                                    
                                    <?php
                                        $numbersOfRooms = (int) $roomList['@size']; 											
                                        for ($roomCount = 0 ; $roomCount < $numbersOfRooms ;  $roomCount++)
                                        { 
                                            
                                            $room_type_info = null;
                                            
                                            if ( $numbersOfRooms <= 1 ){
                                                $room_type_info = $roomList['HotelRoomResponse'];
                                            }
                                            else {
                                            
                                                $room_type_info  = $roomList['HotelRoomResponse'][$roomCount];	
                                            }
                                            
                                            $row_class = ( ($key % 2) == 0) ? 'room-chart-row2' : 'room-chart-row2 room-chart-row3';	
                                    ?>
                                <div class="room-chart chart-border">
                                    
                                    <!-- Row-2 & Row-3 Start -->
                                    <div class="<?php echo $row_class ?>" <?php echo $height_style; ?>>
                                        <div class="room-chart-c1 details-col-1">
                                            <span><a href="javascript: void(0);" class="toggle_desc preview chart-link" rel="<?php echo $this->escape($room_type_info['roomTypeDescription']); ?>" link=""  title="<?php echo $this->escape($room_type_info['roomTypeDescription']); ?>"><?php echo $this->escape($room_type_info['roomTypeDescription']); ?></a></span>
                                        </div>
                                        
                                        <div class="room-chart-c1 room-chart-c2" <?php echo $height_style; ?>>
                                            <a class="preview" link="" title="<?php echo $this->translator->translator('hotels_front_page_list_title_people',$this->escape($room_type_info['rateOccupancyPerRoom'])); ?>">
                                                
                                    
                                                <div>
                                                    <?php
                                                        $max_people = $room_type_info['rateOccupancyPerRoom'];
                                                                                                                            
                                                    ?> 
                                                    <a class="preview" link="" title="<?php echo $this->translator->translator('hotels_front_page_list_title_people',$max_people); ?>">
                                                    <?php 
                                                        if($max_people <= 4)
                                                        {
                                                            for($j = 1; $j <= $max_people; $j++)
                                                            {
                                                                echo '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/people.png" border="0" />';
                                                            }
                                                        } 
                                                        else
                                                        {
                                                            for($j = 1; $j <= 3; $j++)
                                                            {
                                                                echo '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/people.png" border="0" />';
                                                            }
                                                            echo '<span class="person-count">'.$max_people.'</span>';
                                                        }
                                                    ?>
                                                    </a>
                                                </div>
                                                
                                            </a>
                                        </div>

                                        <div class="room-chart-c1 room-chart-c2" >
                                            <div>
                                                <span>

                                                <?php
                                                    $valueAdds = $room_type_info['ValueAdds'];
                                                    $totalServices = (int) $valueAdds ['@size']  ;

                                                    for ($serviceCount  = 0 ; $serviceCount < $totalServices ; $serviceCount++ ) {
                                                        $services = $valueAdds ['ValueAdd'][$serviceCount] ;
                                                        echo $services ['description'] . '<br />';
                                                    }
                                                    
                                                ?>
                                                </span>
                                                
                                                   
                                            <?php  
                                            $surchargeTotal = $ChargeableRateInfo ['@surchargeTotal'] ;
                                            if (! empty($surchargeTotal)){	
                                            ?>
                                            
                                            <span class="mod-title">
                                            
                                            <?php 
                                                                                       
                                                echo ' &nbsp; '.$this->translator->translator('hotels_api_expedia_details_tbl_surcharge' ). ' (' . $ChargeableRateInfo ['@currencyCode']  . ' '. $surchargeTotal . ')' ; 
                                            
                                            ?>
                                            </span> 
                                            <?php }  ?>
                                                
                                            </div>
                                        </div> 
                                                                                    
                                        
                                        <div class="room-chart-c1 room-chart-c3 details-col-3" <?php echo $height_style; ?>>
                                            <!--- PRICE START --->
                                            <span class="payable">
                                            <?php  

                                            $rateInfo = $room_type_info['RateInfos'] ['RateInfo'] ;
                                            $promo = $rateInfo['@promo']; 
                                            if ($promo === 'true' ){
                                                    echo '<span class="promotional">' . $this->translator->translator('hotels_api_expedia_details_promo_running' )  .'</span> <br />';
                                                }
                                            
                                            echo $this->translator->translator('hotels_api_expedia_details_total_payble' ) . '  ' 
                                            
                                            ?>
                                            </span>
                                            
                                            <span class="hotel-price">
                                                                                            
                                            <?php 
                                            
                                            $ChargeableRateInfo = $rateInfo['ChargeableRateInfo'];
                                            $price = $ChargeableRateInfo ['@currencyCode']  . ' '.  $ChargeableRateInfo ['@total'];
                                            echo  $price ; 
                                            
                                            ?>
                                           
                                            </span> 
                                         
                                            
                                            <span class="non-refundable">
                                            <br />
                                            <?php 
                                            
                                                $isRefundable = $room_type_info['nonRefundable'] ;
                                                if ($isRefundable){
                                                    echo $this->translator->translator('hotels_api_expedia_details_tbl_nonrefundable' ); 
                                                }	
                                                                                                
                                            ?>
                                            </span>
                                            
                         
                                            <!--- PRICE END --->
                                        </div>
                                        <!--- BOOK BUTTON STARTS --->
                                        <div class="room-chart-c1 room-chart-c4 details-col-4" <?php echo $height_style; ?>>
                                            <div class="room-chart book-btn-area">
                                            
                                                <?php
                                                  
                                                  $thumImages	=   $hotels_image_val_arr[0]['thumbnailUrl'];
                                                    
                                                  $hotel_id = $roomList['hotelId'] ;
                                                  $reservation_Param  =  array (
                                                                                'hotelId' => $hotel_id , 
                                                                                'customerSessionId' => $roomList['customerSessionId'],
                                                                                'thumbNailUrl' => $this->escape($thumImages),
                                                                                'hotelName' =>  $roomList['hotelName'],
                                                                                'hotelAddress' => $roomList['hotelAddress'],
                                                                                'rateCurrencyCode' => $this->escape($ChargeableRateInfo ['@currencyCode']),
                                                                                'roomTypeDescription' => $this->escape($room_type_info['roomTypeDescription']),
                                                                                'nonRefundable' => $isRefundable,
                                                                                'surchargeTotal' => $ChargeableRateInfo ['@surchargeTotal']  ,																					
                                                                                'nightlyRateTotal' => $ChargeableRateInfo ['@nightlyRateTotal'],																					
                                                                                'GustNumber' =>  $this->roomDetails,
                                                                                'minGuestAge' => $room_type_info['minGuestAge'],
                                                                                'arrivalDate' => $roomList['arrivalDate'], 
                                                                                'departureDate' => $roomList['departureDate'], 
                                                                                'rateKey' => $roomList['rateKey']  , 
                                                                                'roomTypeCode' => $room_type_info['roomTypeCode'], 
                                                                                'rateCode' => $room_type_info['rateCode'], 
                                                                                'chargeableRate' => $ChargeableRateInfo ['@total']   
                                                                              );																		
                                                  $request_object = base64_encode( json_encode ($reservation_Param) ) ;	
                                                  
                                                if($global_conf['payment_system'] == 'On')
                                                {
                                            ?>
                                                <span class="products-book-btn"><a href="<?php echo $this->url( array('module' =>'Hotels','controller' => 'expedia', 'action'  => 'reservation' , 'bookingInfo' => $request_object, 'hotel_id' => $hotel_id ), 'Ean-Booking/:bookingInfo/:hotel_id',    true) ?>" target="_blank"><?php echo $this->translator->translator('hotels_front_page_show_price'); ?></a></span>
                                            <?php } ?>                                              
                                            </div>
                                            
                                            <!--- BOOK BUTTON ENDS --->
                                        </div>                                                                       
                                    </div>
                                    
                                    </div>
                                    <div class="room-chart chart-border">
                                   
                                        <div id="room_type_desc<?php echo $room_type_info['@roomTypeId']; ?>"  class="room-chart-details">
                                                <?php
                                                    if(!empty($room_type_info['roomAmenities']))
                                                    {															
                                                        $room_type_im_arr = $room_type_info['roomAmenities']['RoomAmenity'];															
                                                        foreach($room_type_im_arr as $key=>$value)
                                                        {
                                                ?>
                                                            <?php echo '<div class="hotel-tab-feature">'.$value['amenity'].'</div>'; ?>
                                                <?php
                                                        }															
                                                    }														
                                                ?>
                                        </div>      
                                    </div>
                                    <!-- Row-2 & Row-3 End -->                                            
                                    <?php														
                                            
                                        }
                                    ?>	                                  
                                        
                                    
                        </form>
                        </div>
                    <!-- Tab Detail End -->
                    
                    <!-- Hotel Summary Start -->
                    
                    <!--<div class="hotel-summary">
                        <div class="hotel-details">
                            <h6 class="hotel-details-title"><?php echo $this->translator->translator('hotels_front_page_Title_summary'); ?></h6>
                            
                        </div>                    
                    </div>-->
                    <!-- Hotel Summary End -->
                    
                    
                </div>
            
                <div id="tabs-2">
                    <h2><?php echo $this->translator->translator('hotels_page_sec_feature'); ?></h2>
                    <?php								
                            $feature_facilities_arr = $this->view_datas['PropertyAmenities']['PropertyAmenity']; 
                            if(!empty($feature_facilities_arr))
                            { 
                                foreach($feature_facilities_arr as $key=>$value)
                                {
                                    echo '<div class="products-features">&bull; '.$this->escape($value['amenity']).'</div>';
                                }
                            }						  
                      ?>					
                </div>
                <div id="tabs-3">
                    <?php echo   html_entity_decode($this->escape($this->view_datas['HotelDetails']['propertyDescription']), HTML_ENTITIES, 'UTF-8'); ?>
                </div>
                <div id="tabs-4">
                    <p><?php echo   html_entity_decode($this->escape($this->view_datas['HotelDetails']['drivingDirections']), HTML_ENTITIES, 'UTF-8'); ?></p>
                    <hr />
                    <p><?php echo   html_entity_decode($this->escape($this->view_datas['HotelDetails']['checkInInstructions']), HTML_ENTITIES, 'UTF-8'); ?></p>
                    <hr />
                    <p><?php echo   html_entity_decode($this->escape($this->view_datas['HotelDetails']['roomInformation']), HTML_ENTITIES, 'UTF-8'); ?></p>
                    <hr />
                    <p><?php echo   html_entity_decode($this->escape($this->view_datas['HotelDetails']['hotelPolicy']), HTML_ENTITIES, 'UTF-8'); ?></p>
                </div>

                <div id="tabs-5">
                    <hr />
                    <p><?php echo   html_entity_decode($this->escape($roomList['checkInInstructions']), HTML_ENTITIES, 'UTF-8'); ?></p>
                    <hr />
                </div>

                <div id="tabs-6"> 
                    <p><?php echo html_entity_decode($this->escape($this->view_datas['HotelDetails']['areaInformation']), HTML_ENTITIES, 'UTF-8'); ?></p>
                </div>
                
                <!--<div class="hotel-tab" id="tabs-7">
                    <hr />
                    <pre>
                    
                    <p><?php //  print_r( $roomList);  echo '<br /> <hr>' ; print_r ($this->view_datas) ;  ?></p>
                    
                    </pre>
                    <hr />
                </div>-->
        </div>
    </div>

	<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg','Message'); ?>"></div>

	<?php endif; ?>	
