<?php
$maximum_stars_digit = $this->translator->translator('maximum_stars_digit');
$version = Zend_Registry::get('version'); 
$tab_base_link = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
$front_template = Zend_Registry::get('front_template');
echo $this->headScript()->setFile($this->baseUrl().'/vendor/scripts/BookingCalendar/js/jquery.dop.BookingCalendar.js');
echo $this->headLink()->setStylesheet('application/layouts/scripts/'.$front_template['theme_folder'].'/css/jquery.dop.BookingCalendar.css');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/gallery/jquery.ad-gallery.js'); 
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/raty/js/jquery.raty.js');
echo $this->headLink()->setStylesheet($this->baseUrl().'/js/jquery/gallery/jquery.ad-gallery.css');
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/jquery.scrollTo.js');

if(!empty($this->view_datas['meta_keywords'])){ $this->headMeta()->setName('keywords',$this->view_datas['meta_keywords']); }
if(!empty($this->view_datas['meta_desc'])) { $this->headMeta()->setName('description',$this->view_datas['meta_desc']); }
if(!empty($this->view_datas['hotels_name'])) { $this->headTitle()->headTitle($this->escape($this->view_datas['hotels_name']),'SET')->setSeparator(' - ')->headTitle($this->view_datas['meta_title']); }

function isnot_int($hotels_agent)
{
	$r = true;			
	if(is_numeric($hotels_agent))
	{ 
		if(is_int((int)$hotels_agent))
		{
			$r = false;
		}				
	}
	return $r;
}

function getNights($sStartDate, $sEndDate)
{		
	$sStartDate =strtotime($sStartDate);
	$sEndDate = strtotime($sEndDate);
	
	$datediff = $sEndDate - $sStartDate;
	$aDays	= floor($datediff/(60*60*24));
	
	return $aDays;
}

$global_conf = Zend_Registry::get('global_conf');

// 1ist param options are : like, inline, plus_minus, horizontal, triangle
$vote = new Vote_Controller_Helper_ShowVoteButton('inline','hotels_page' );
$business_type_db = new Hotels_Model_DbTable_BusinessType();
$mem_db = new Members_Model_DbTable_MemberList();
$room_db = new Hotels_Model_DbTable_Room();
$room_type_id_arr = explode(',', $this->hotelsForm->room_type_id->getValue());

$nextHotels = $this->hotels_db->getNextHotels($this->view_datas['id'],$this->view_datas['group_id'], null);
$prevHotels = $this->hotels_db->getPrevHotels($this->view_datas['id'],$this->view_datas['group_id'], null);
$auth = Zend_Auth::getInstance ();
$hasIdentity = $auth->hasIdentity ();



if($this->view_datas['area_id'])
{												
	try
	{
		$area_db = new Hotels_Model_DbTable_Area();
		$area_info = $area_db->getAreaInfo($this->view_datas['area_id']);		
	}
	catch(Exception $e)
	{
		
	}
}
if($this->view_datas['state_id'])
{
	try
	{
		$state_db = new Hotels_Model_DbTable_State();
		$state_info = $state_db->getStateInfo($this->view_datas['state_id']);
	}
	catch(Exception $e)
	{
		
	}
}
if($this->view_datas['country_id'])
{
	try
	{
		$country_db = new Hotels_Model_DbTable_Country();
		$country_info = $country_db->getCountryName($this->view_datas['country_id']);
	}
	catch(Exception $e)
	{
	}
} 
?>
<style type="text/css">	
#dialog_calendar{background-color: #f0f0f0; background: url('js/jquery/BookingCalendar/images/loader-big.gif') no-repeat center center;}
.dialogPosition {position:fixed;}
</style>
<script type="text/javascript">
function scrolling(class_name)
{
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	$('a.'+class_name).click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		var rel = $(this).attr('rel');
		var id_arr = rel.split('-');
		var id_no = parseInt(id_arr[1]);
		$('#tabs').tabs({ active: --id_no });
		$.scrollTo( rel , 1500, { easing:'swing' });		
		return false;
	});
}

function bookScrolling()
{
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	
	$('a.book_btn').click(function() {
	 	
		var tmp  = false;
		$.each($('#bookHotel').serializeArray(), function(i, field) {	
			if(field.name.match(/\[\]$/))
			{
				if($('select[name="'+field.name+'"]').attr('class') == 'apartments_no multi-hotel-room')
				{
					if(field.value != '0' && field.value != '')
					{
						tmp = true;
					}
				}				
			}			
		});
		if(tmp == true)
		{
			$('#bookHotel').submit();
		}
		else
		{	
			var msg = "<?php echo $this->translator->translator('hotels_selected_err'); ?>";
			openMsgDialog(msg);	
							
			var self = this;			
			var rel = $(self).attr('rel');
			var id_arr = rel.split('-');
			var id_no = parseInt(id_arr[1]);
			$('#tabs').tabs({ active: --id_no });
			$.scrollTo( rel , 1500, { easing:'swing' });			
			return false;			
		}
	 });
}

function changeImageScrolling()
{
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	
	 
	 $("a.change_img").click(function(){
			var self = this;
			var src = $(self).children("img:nth-child(1)").attr('src');			
			$("div.ad-image").children("img:nth-child(1)").attr('src',src);							
			$.scrollTo( '#gallery' , 1500, { easing:'swing' });			
			return false;
		});
}

 $(function() {				
	var galleries = $('.ad-gallery').adGallery({
					slideshow: {
                       enable: true,
                       autostart: true,
                       speed: 5000,
                       start_label: 'Start',
                       stop_label: 'Stop',
                       stop_on_scroll: true,
                       countdown_prefix: '(',
                       countdown_sufix: ')',
                       onStart: false,
                       onStop: false
                     }
					 });
	$('#switch-effect').change(
	  function() {
		galleries[0].settings.effect = $(this).val();
		return false;
	  }
	);
	$('#toggle-slideshow').click(
	  function() {
		galleries[0].slideshow.toggle();
		return false;
	  }
	);
	$('#toggle-description').click(
	  function() {
		if(!galleries[0].settings.description_wrapper) {
		  galleries[0].settings.description_wrapper = $('#descriptions');
		} else {
		  galleries[0].settings.description_wrapper = false;
		}
		return false;
	  }
	);
  });
$(function() {		
		
		$("#tabs").tabs({ 
				active: <?php echo $this->tab; ?>, 
				select: function(event, ui) { 
				
				} 		
		}).find(".ui-tabs-nav").sortable({axis:'xy'});
		
		$("#matchTabs").tabs().find(".ui-tabs-nav").sortable({axis:'xy'});
		
		openBookingCalendar();
		
		changeImageScrolling();
				
		scrolling('payment_btn');
		
		scrolling('review_btn');	
		
		scrolling('calendar_btn');	
		
		scrolling('additional_photo_btn');
			
	});
	
function openBookingCalendar()
{
	$('select.dialog_calendar_select').change(function() {
		var self = this;
		var id = $(self).val();	
		var room_type = $(self).parents('div:first').attr('title');
		$('select.dialog_calendar_select').val('0');
		$(self).val(id);
		if(id == '0' || id == 0 || id == null || id == '')
		{
			$('#dialog_calendar').html('');
			$('#dialog_calendar').css('background', "none");
			$('#dialog_calendar_title').text('');
		}
		else
		{
			$('#dialog_calendar_title').text(room_type);	
			$('#dialog_calendar').html('');
			$('#dialog_calendar').css('background', "url('vendor/scripts/BookingCalendar/images/loader-big.gif') no-repeat center center");
			$('#dialog_calendar').DOPBookingCalendar({'Type':'FrontEnd', 'DataURL':'<?php echo $this->url( array("module"=> "Hotels", "controller" => "frontend", "action"     => "load", "id" => '' ), "adminrout",    true) ?>'+id,'Currency':'<?php echo $this->currency->getSymbol(); ?>', 'AvailableText':"<?php echo $this->translator->translator("calerdar_AvailableText", '', '', $front_template['theme_folder']); ?>", 'BookedText':"<?php echo $this->translator->translator("calerdar_BookedText", '', '', $front_template['theme_folder']); ?>", 'UnavailableText':"<?php echo $this->translator->translator("calerdar_UnavailableText", '', '', $front_template['theme_folder']); ?>"});
		}
	});
}	

function openMsgDialog(msg)
{
	$('#dialog_container').html(msg).dialog({
		autoOpen: true,
		modal: false,
		show: 'explode',
		resizable: true,	
		dialogClass: 'dialogPosition',			
		buttons: [{ text: "<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>", click: function() { $(this).dialog('option', 'hide', 'explode').dialog("close"); } } ],
		open: function(event, ui)
			 {
				setTimeout(function() 
				{									
					if($('#' + event.target.id).dialog('isOpen'))
					{
						$('#' + event.target.id).dialog('option', 'hide', 'explode').dialog('close');										
					}
				}, 10000);
			  }
	});
}


$(document).ready(function() {
	function stripslashes(str) 
	{
		str=str.replace(/\\'/g,'\'');
		str=str.replace(/\\"/g,'"');
		str=str.replace(/\\0/g,'\0');
		str=str.replace(/\\\\/g,'\\');
		return str;
	}
	
	$('a.toggle_desc').click(function() {
		var self = this;
		var id = $(self).attr('rel');
		
		$('#room_type_desc'+id).slideToggle(500,function () {
			
		});
		return false;
	  });
	  
	  <?php if(!empty($this->post_search_info) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT])){ ?>
	  		$('div.room-chart-details').show();
	  <?php } ?>
	  
	 bookScrolling();	
	
	$('a.save_hotels_btn').click(function() {
		var self = this;
		var id = $(self).attr('rel');
		$.ajax({
			  url: "<?php echo $this->url( array('module' =>'Hotels','controller' => 'frontend', 'action'     => 'save' ), 'adminrout',    true) ?>",
			  type: 'POST',
			  data: { id: id },
			  beforeSend: function(){						
						$(self).html('<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/loader/mod-loader.gif" border="0" height="15" />');	
					 },
			  success: function(response){
				//alert(response);
				var json_arr = eval("("+response+")");							
				if(json_arr.status == 'ok')
				{
					openMsgDialog(json_arr.msg);
				}
				else
				{
					openMsgDialog(json_arr.msg);
				}
				$(self).html('<?php echo $this->translator->translator("hotels_front_page_save_hotels"); ?>');
			  }
		});
	});	
	
	$('a.print_btn').click(function (event){
	
			var width = 1200;
    		var height = 700;
			var left = parseInt((screen.availWidth/2) - (width/2));
   			var top = parseInt((screen.availHeight/2) - (height/2));
			var windowSizeArray = [ "width="+width+",height="+height+",left="+left+",top="+top+"screenX=" + left + ",screenY=" + top + ",scrollbars=yes",
									"width="+width+",height="+height+",scrollbars=yes" ];
			var url = "<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'print','hotels_title' => $this->escape($this->view_datas['hotels_title']) ),'Hotels-print/:hotels_title',true); ?>";
			var windowName = "popUp";
			var windowSize = windowSizeArray[$(this).attr("rel")];

			window.open(url, windowName, windowSize);

			event.preventDefault();

		});
	
});
function raty (id, start_point)
{
	$('#'+id+'_star').raty({
	  path: 'js/jquery/raty/img/',						  
	  hintList:		"<?php echo $this->translator->translator("common_rating_hintList"); ?>",
	  number:     <?php $hint_arr = explode(', ',str_replace('[', '', str_replace(']', '', $this->translator->translator('common_rating_hintList')))); echo count($hint_arr); ?>,
	  start: start_point,
	  readOnly:   true					 
	});
}
</script>
<?php 
$allow_obj = new Hotels_View_Helper_Allow();
if (!$allow_obj->allowRule('details',null,null,$this->group_datas['role_id'])) : ?>
	<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
<?php else : ?>
<?php if($this->view_datas['active'] == '1') : ?>
<div class="mod mod-details">
	<!-- Top Bar Start -->
    <div class="nav-bar">
        <div class="nav-row">
            <div class="nav-col first"> 
            <?php
                if(!empty($prevHotels))
                {
            ?>
            <span class="prev"><a href="<?php echo 'Hotels-details/'.$this->escape($prevHotels['hotels_title']); ?>"><?php echo $this->translator->translator('hotels_front_page_prev_hotels'); ?></a></span>
            <?php
                }
                else
                {
            ?>
            <span class="no-link"><?php echo $this->translator->translator('hotels_front_page_prev_hotels'); ?></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col"><span class="search"><a href="Search-Hotels"><?php echo $this->translator->translator('hotels_front_page_new_search'); ?></a></span></div>
            <div class="nav-col">
            <?php
                if(!empty($nextHotels))
                {
            ?>
            <span class="save"><a  href="javascript:void(0);" class="save_hotels_btn" rel="<?php echo $this->escape($this->view_datas['id']); ?>"><?php echo $this->translator->translator('hotels_front_page_save_hotels'); ?></a></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col last">
            <?php
                if(!empty($nextProperty))
                {
            ?>
            <span class="next"><a href="<?php echo 'Hotels-details/'.$this->escape($nextHotels['hotels_title']); ?>"><?php echo $this->translator->translator('hotels_front_page_next_hotels'); ?></a></span>
            <?php
                }
                else
                {
            ?>
            <span class="no-link"><?php echo $this->translator->translator('hotels_front_page_next_hotels'); ?></span>
            <?php
                }
            ?>
            </div>
        </div>
    </div>
	<!-- Top Bar End -->
    <div class="clear"></div>
    <h1><?php echo $this->escape($this->hotelsForm->hotels_name->getValue()); ?></h1>
    <div class="clear"></div>
    
    <!-- Hotel Info Start -->
    <div class="products-info">
        <div class="products-stars">
            <?php
                for($i = 1; $i < $maximum_stars_digit; $i++)
                {
                    $hotel_stars = ($i <= $this->escape($this->hotelsForm->hotels_grade->getValue())) ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-inactive.png' border='0' />";
                    echo $hotel_stars.'&nbsp;';
                }
            ?>
        </div>
                        
        <ul class="products-options">
            <li class="availability"><a href="javascript: void(0);" class="calendar_btn" rel="#tabs-10" title="<?php echo $this->translator->translator('hotels_front_page_hotels_check_calendar'); ?>"><?php echo $this->translator->translator('hotels_front_page_hotels_check_calendar'); ?></a></li>
            <?php
                $feature_facilities_arr = explode(',',$this->hotelsForm->feature_facilities->getValue());
                if(in_array('airport transfer',$feature_facilities_arr))
                {
            ?>
        
            <li class="airport-transfer"><?php echo $this->translator->translator('hotels_front_page_hotels_airport_transfer'); ?></li>
            <?php
                }
                $feature_sports_recreations_arr = explode(',',$this->hotelsForm->feature_sports_recreations->getValue());															
                if(in_array('indoor pool',$feature_sports_recreations_arr))
                {
            ?>
        
        	<li class="swimming"><?php echo $this->translator->translator('hotels_front_page_hotels_swwimming_pool_availability'); ?></li>            
        
			<?php
                }
                if($this->hotelsForm->feature_pet->getValue() == 'Pets are allowed')
                {
            ?>
        
        	<li class="pet"><?php echo $this->translator->translator('hotels_front_page_hotels_pet_allow'); ?></li>
        
			<?php
                }																				
                if(in_array('Internet Available',$feature_facilities_arr))
                {
            ?>
        
        	<li class="internet" title="<?php echo $this->translator->translator('hotels_front_page_hotels_internet_availability'); ?>"><?php echo $this->translator->translator('hotels_front_page_hotels_internet_availability'); ?></li>
        
			<?php 
            }
              if(!empty($this->view_datas['hotels_phone'])){ ?>
                <span class="products-call"><?php if(!empty($this->view_datas['hotels_phone'])){ ?><span><?php  echo $this->escape($this->hotelsForm->hotels_phone->getValue()); ?></span><?php } ?></span>
            <?php } ?>
        </ul>
    </div>
    
    <div class="products-info right">
        <span class="products-status">
            <span class="products-mark"><?php  echo $this->escape($this->hotelsForm->hotels_status->getValue()); ?></span>&nbsp; <span class="products-type"><?php echo strtoupper($this->escape($this->businessTypeInfo['business_type'])); ?></span>
        </span>     
       	<div class="clear"></div>
        <div class="products-review">
            <span class="products-write-review"><?php if(!empty($this->group_datas['review_id'])){ $review_no = (!empty($this->review_datas)) ? htmlentities($this->review_datas['review_no']) : htmlentities('0'); ?><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $this->view_datas['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></span> &nbsp; <span class="products-review-count"><a href="javascript:void(0);" class="review_btn" rel="#tabs-11"><?php echo $this->translator->translator('common_review_no',$review_no); ?></a></span><?php } ?>
        </div>
        
        <div class="products-vote">
            <p><?php echo $this->translator->translator('hotels_front_page_label_voting'); ?></p>
            <span><?php  $vote->showButton($this->view_datas['id'] , $this->escape($this->view_datas['hotels_name'])); ?></span>
        </div>   
	  	<?php
      		if($global_conf['payment_system'] == 'On'){
      	?>
        
        <div class="clear">
            <span class="form-button"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'book', 'action' => 'booking','hotels_title' => $this->escape($this->view_datas['hotels_title']) ),'Book-Hotel/:hotels_title',true); ?>"><?php echo $this->translator->translator('hotels_front_page_show_price'); ?></a></span>
        </div>
       	<?php } ?>
    </div>
    <!-- Hotel Info End -->
    
    <!-- Hotel Details Middle Tab Start -->
    <div class="products-middle-tab">
        <ul>
            <li><a href="javascript:void(0);" class="print_btn" rel="0"><?php echo $this->translator->translator('common_print'); ?></a></li>
            <li><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'emails', 'action' => 'friend','hotels_title' => $this->escape($this->view_datas['hotels_title']), 'form_id' => $this->translator->translator('email_to_friend_form_id') ),'Email-Your-Friend/:hotels_title/:form_id',true); ?>"><?php echo $this->translator->translator('common_email_to_friend'); ?></a></li>
            <li><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'emails', 'action' => 'appointment','hotels_title' => $this->escape($this->view_datas['hotels_title']), 'form_id' => $this->translator->translator('appointment_form_id') ),'Hotels-Appointment/:hotels_title/:form_id',true); ?>"><?php echo $this->translator->translator('common_appointment'); ?></a></li>
            <li><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'emails', 'action' => 'owner','hotels_title' => $this->escape($this->view_datas['hotels_title']), 'form_id' => $this->translator->translator('contact_owner_form_id') ),'Contact-Agent/:hotels_title/:form_id',true); ?>"><?php echo $this->translator->translator('common_contact'); ?></a></li>
            <li><a href="javascript: void(0);" class="payment_btn" rel="#tabs-8" ><?php echo $this->translator->translator('hotels_front_page_Title_payment'); ?></a></li>
        </ul>
    </div>    
    <div class="products-middle-tab-area">
        <!-- Slide Show Start -->
        <div class="products-slideshow">
            <?php		  
                $hotels_image_val_arr = explode(',', $this->hotelsForm->hotels_image->getValue());
                if($this->escape($this->view_datas['hotels_primary_image']))
                { 
                    $thumb_image = 'data/frontImages/hotels/hotels_image/'.$this->escape($this->view_datas['hotels_primary_image']); 
                }
                else
                { 
                    if($this->escape($this->hotelsForm->hotels_image->getValue()))
                    {					
                        $thumb_image = 'data/frontImages/hotels/hotels_image/'.$this->escape($hotels_image_val_arr[0]); 
                    }
                    else
                    {
                        $thumb_image = 'data/frontImages/hotels/design_images/no_image.jpg'; 
                    }		
                }
                if($this->group_datas['img_big_width'] && ($this->group_datas['img_big_resize_func'] == 'resizeToWidth' || $this->group_datas['img_big_resize_func'] == 'resize' ))
                { 
                    $width = 'width="'.$this->escape($this->group_datas['img_big_width']).'"'; 
                }
                else
                {
                    $width = '';
                } 
                if($this->group_datas['img_big_height'] && ( $this->group_datas['img_big_resize_func'] == 'resizeToHeight' || $this->group_datas['img_big_resize_func'] == 'resize' ))
                { 
                    $height = 'height="'.$this->escape($this->group_datas['img_big_height']).'"'; 
                } 
                else
                {
                    $height = '';
                }
                
            ?> 
        
            <div id="container">
                <div id="gallery" class="ad-gallery">
                  <div class="ad-image-wrapper"></div>
                  <div class="ad-controls"></div>
                    <div class="ad-nav">
                        <div class="ad-thumbs">
                          <ul class="ad-thumb-list" style="min-width:100%;">
                            <li>
                              <a href="<?php echo $thumb_image; ?>">
                                <img src="<?php echo $thumb_image; ?>"  width="70" height="50" title="<?php echo $this->escape($this->hotelsForm->hotels_name->getValue()); ?>" alt="<?php echo $this->escape($area_info['city']).', '.$this->escape($country_info['value']); ?>"  class="image0">
                                </a>
                              </li>
                            <?php		
                                                                                
                                foreach($hotels_image_val_arr as $key=>$value)
                                {									
                                    if($thumb_image != 'data/frontImages/hotels/hotels_image/'.$value)
                                    {
                              ?>
                            <li>
                              <a href="data/frontImages/hotels/hotels_image/<?php echo $value; ?>">
                                <img src="data/frontImages/hotels/hotels_image/<?php echo $value; ?>"  width="70" height="50" title="<?php echo $this->escape($this->hotelsForm->hotels_name->getValue()); ?>" alt="<?php echo $this->escape($area_info['city']).', '.$this->escape($country_info['value']); ?>"  class="image0">
                                </a>
                              </li>
                            <?php
                                    }
                                }
                            ?>					
                            </ul>
                        </div>
                    </div>
                </div>
            
                <div class="switch">
                  <select id="switch-effect">
                    <option value="slide-hori">Slide horizontal</option>
                    <option value="slide-vert">Slide vertical</option>
                    <option value="resize">Shrink/grow</option>
                    <option value="fade">Fade</option>
                    <option value="">None</option>
                    </select> <a href="#" id="toggle-slideshow">Toggle slideshow</a> |
                  <a href="#" id="toggle-description">Toggle description outside image</a>
                </div>
            </div>
        </div>
        <!-- Slide Show End -->
        
        <!-- Hotel Match Start -->
        <div class="match-container">
            <div id="matchTabs">
                <ul>
                  <li><a href="<?php echo $tab_base_link; ?>#matchTabs-1"><?php echo $this->translator->translator('hotels_front_page_match_related'); ?></a></li>
                  <li><a href="<?php echo $tab_base_link; ?>#matchTabs-2"><?php echo $this->translator->translator('hotels_front_page_match_state'); ?></a></li>					
                  <li><a href="<?php echo $tab_base_link; ?>#matchTabs-3"><?php echo $this->translator->translator('hotels_front_page_match_agent'); ?></a></li>
                </ul>
                <div class="match-tab-container" id="matchTabs-2">
                    <?php
                            $hotelsMatchRegion = $this->hotels_db->getHotelsMatchRegion($this->escape($this->view_datas['id']),$this->escape($this->hotelsForm->state_id->getValue()),10);
                            if($hotelsMatchRegion)
                            {																
                                foreach($hotelsMatchRegion as $match_info)
                                {								
                    ?>
                        <div class="products-match">                          
                            <span><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($match_info['hotels_title']) ),'Hotels-details/:hotels_title',true); ?>" class="preview hotel-related"  title="<?php echo $this->escape($match_info['hotels_name']); ?>" width="300"><?php echo $this->escape($match_info['hotels_name']); ?></a></span>
                            <div class="products-star">
                                <?php
                                 $hotel_stars = (int) $this->escape($match_info['hotels_grade']);
                                                                                           
                                  for($i = 1; $i < $maximum_stars_digit ; $i++)
                                  {
                                      $print_stars = ($i <= $hotel_stars )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-small-inactive.png' border='0' />";
                                      echo $print_stars.'&nbsp;';
                                  }
                              ?>											
                            </div>
                            
                            <?php
                                if(!empty($this->group_datas['review_id']))
                                { 
                                    $review_match_no = htmlentities($this->review_helper->getNumOfReviews($match_info['id'], $this->group_datas['review_id']));
                                ?>
                                <div class="products-review">
                                    <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($match_info['hotels_title']),'tab' => 10 ),'Hotels-details/:hotels_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                                    <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $match_info['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                                </div>
                            <?php
                                }
                            ?>
                            
                            <div class="thumb">
                                <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($match_info['hotels_title']) ),'Hotels-details/:hotels_title',true); ?>" class="preview" link="data/frontImages/hotels/hotels_image/<?php echo $match_info['hotels_primary_image']; ?>"  title="<?php echo $this->escape($match_info['hotels_name']); ?>" width="300"><img src="data/frontImages/hotels/hotels_image/<?php echo $match_info['hotels_primary_image']; ?>" alt="<?php echo strip_tags($this->escape($match_info['hotels_name'])); ?>"  width="70" height="50" border="0" /></a>
                            </div>
                                
                            <div class="products-desc">
                                <?php
                                $related_feature_facilities_arr = explode(',', $match_info['feature_facilities']);
                                foreach($related_feature_facilities_arr as $facilities_key => $facilities_value)
                                {
                                    echo $this->escape($facilities_value).'<br />';
                                    if($facilities_key >= 4){ break; }
                                }
                                ?>											
                            </div>
                        </div>
                    
                    <?php
                                }            
                            }
                    ?>
                </div>
                <div class="match-tab-container" id="matchTabs-3">
                    <?php
                            $hotelsMatchAgent = $this->hotels_db->getHotelsMatchAgent($this->escape($this->view_datas['id']),$this->escape($this->hotelsForm->hotels_agent->getValue()),10);
                            if($hotelsMatchAgent)
                            {
                                echo '<ul>';
                                foreach($hotelsMatchAgent as $match_info)
                                {
                    ?>
                        <div class="products-match">                     
                            <span><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($match_info['hotels_title']) ),'Hotels-details/:hotels_title',true); ?>" class="preview hotel-related"   title="<?php echo $this->escape($match_info['hotels_name']); ?>" width="300"><?php echo $this->escape($match_info['hotels_name']); ?></a></span>
                            <div class="products-star">
                                <?php
                                 $hotel_stars = (int) $this->escape($match_info['hotels_grade']);
                                                                                           
                                  for($i = 1; $i < $maximum_stars_digit ; $i++)
                                  {
                                      $print_stars = ($i <= $hotel_stars )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-small-inactive.png' border='0' />";
                                      echo $print_stars.'&nbsp;';
        
                                  }
                                ?>											
                            </div>
                            
                            <?php
                                if(!empty($this->group_datas['review_id']))
                                { 
                                    $review_match_no = htmlentities($this->review_helper->getNumOfReviews($match_info['id'], $this->group_datas['review_id']));
                                ?>
                                <div class="products-review">
                                    <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($match_info['hotels_title']),'tab' => 10 ),'Hotels-details/:hotels_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                                    <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $match_info['id'] ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                                </div>
                            <?php
                                }
                            ?>
    
                            <div class="thumb">
                                <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($match_info['hotels_title']) ),'Hotels-details/:hotels_title',true); ?>" class="preview" link="data/frontImages/hotels/hotels_image/<?php echo $match_info['hotels_primary_image']; ?>"  title="<?php echo $this->escape($match_info['hotels_name']); ?>" width="300"><img src="data/frontImages/hotels/hotels_image/<?php echo $match_info['hotels_primary_image']; ?>" alt="<?php echo strip_tags($this->escape($match_info['hotels_name'])); ?>"  width="70" height="50" border="0" /></a>
                            </div>
                            
                            <div class="products-desc">
                                <?php
                                $related_feature_facilities_arr = explode(',', $match_info['feature_facilities']);
                                foreach($related_feature_facilities_arr as $facilities_key => $facilities_value)
                                {
                                    echo $this->escape($facilities_value).'<br />';
                                    if($facilities_key >= 4){ break; }
                                }
                                ?>											
                            </div>
                        </div>
                    
                    <?php
                                    
                            }
                            echo '</ul>';
                        }
                    ?>
                </div>
                <div class="match-tab-container" id="matchTabs-1">
                    <?php						
                        if($this->hotelsForm->related_items->getValue())
                        {
                            $related_items_arr = explode(',',$this->hotelsForm->related_items->getValue());
                            
                            foreach($related_items_arr as $key=>$value)
                            {
                                $get_related_info = $this->hotels_db->getHotelsInfo($value); 
                    ?>		
                        <div class="products-match">
                            <span><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($get_related_info['hotels_title']) ),'Hotels-details/:hotels_title',true); ?>" class="preview hotel-related"   title="<?php echo $this->escape($get_related_info['hotels_name']); ?>" width="300"><?php echo $this->escape($get_related_info['hotels_name']); ?></a></span>
                            <div class="products-star">
                                <?php
                                 $hotel_stars = (int) $this->escape($get_related_info['hotels_grade']);
                                                                                           
                                  for($i = 1; $i < $maximum_stars_digit ; $i++)
                                  {
                                      $print_stars = ($i <= $hotel_stars )  ? "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-small-active.png' border='0' />" : "<img src='application/layouts/scripts/".$front_template['theme_folder']."/images/mod_hotel_img/star-small-inactive.png' border='0' />";
                                      echo $print_stars.'&nbsp;';
                                  }
                                ?>											
                            </div>
                            
                            <?php
                            if(!empty($this->group_datas['review_id']))
                                { 
                                $review_match_no = htmlentities($this->review_helper->getNumOfReviews($value, $this->group_datas['review_id']));
                            ?>
                            <div class="products-review">
                                <div class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($get_related_info['hotels_title']),'tab' => 10 ),'Hotels-details/:hotels_title/:tab',true); ?>"><?php echo $this->translator->translator('common_review_no',$review_match_no); ?></a>&nbsp;</div>
                                <div class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', 'group_id' => $this->escape($this->group_datas['review_id']), Eicra_File_Constants::ITEM_ID => $value ), 'Review-Write/:group_id/:item_id',    true); ?>"><?php echo $this->translator->translator('common_write_review'); ?></a></div>
                            </div>
                            <?php
                                }
                            ?>
                            
                            <div class="thumb">
                                <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => $this->escape($get_related_info['hotels_title']) ),'Hotels-details/:hotels_title',true); ?>" class="preview" link="data/frontImages/hotels/hotels_image/<?php echo $get_related_info['hotels_primary_image']; ?>"  title="<?php echo $this->escape($get_related_info['hotels_name']); ?>" width="300"><img src="data/frontImages/hotels/hotels_image/<?php echo $get_related_info['hotels_primary_image']; ?>" alt="<?php echo strip_tags($this->escape($get_related_info['hotels_name'])); ?>"  width="70" height="50" border="0"  /></a>
                            </div>
                            
                            <div class="products-desc">
                                <?php
                                $related_feature_facilities_arr = explode(',', $get_related_info['feature_facilities']);
                                foreach($related_feature_facilities_arr as $facilities_key => $facilities_value)
                                {
                                    echo $this->escape($facilities_value).'<br />';
                                    if($facilities_key >= 4){ break; }
                                }
                                ?>											
                            </div>
                        </div>
                    <?php    
                            }   
                        }
                    ?>                    
                </div>
            </div>
        </div>
        <!-- Hotel Match End -->     
    </div>
    
    <div class="products-details">
        <div class="products-details-header"><h4 class="icon"><?php echo $this->hotelsForm->hotels_desc->getAttrib('font_end_label'); ?></h4></div>
        <div class="content">
            <div class="details-info"><?php echo $this->escape($this->hotelsForm->hotels_desc->getValue()); ?></div>
        </div>
    </div>
  
    <!-- Hotel Bottom Tab Start -->
    <div id="tabs">
            <ul>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-1"><?php echo $this->translator->translator('hotels_front_page_hotels_details'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-2"><?php echo $this->translator->translator('hotels_front_page_hotels_exterior'); ?> <span class="photo-no"><?php if($this->hotelsForm->hotels_image->getValue()){ $photos_arr = explode(',', $this->hotelsForm->hotels_image->getValue()); echo count($photos_arr); } else{ echo '0'; } ?></span></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-3"><?php echo $this->translator->translator('hotels_front_page_hotels_interior'); ?> <span class="photo-no"><?php if($this->hotelsForm->feature_interior_plan_image->getValue()){ $photos_interior_arr = explode(',', $this->hotelsForm->feature_interior_plan_image->getValue()); echo count($photos_interior_arr); } else{ echo '0'; } ?></span></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-4"><?php echo $this->translator->translator('hotels_front_page_hotels_features'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-5"><?php echo $this->translator->translator('hotels_front_page_hotels_profile'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-6"><?php echo $this->translator->translator('hotels_front_page_hotels_brochure'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-7"><?php echo $this->translator->translator('hotels_front_page_hotels_map'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-8"><?php echo $this->translator->translator('hotels_front_page_hotels_financing'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-9"><?php echo $this->translator->translator('hotels_front_page_hotels_policy'); ?></a></li>
                <li><a href="<?php echo $tab_base_link; ?>#tabs-10"><?php echo $this->translator->translator('hotels_front_page_hotels_available'); ?></a></li>
                <?php
                    if(!empty($this->group_datas['review_id']))
                    {
                        echo '<li><a href="'.$tab_base_link.'#tabs-11">'.$this->translator->translator('hotels_front_page_hotels_reviews').'</a></li>';
                    }
                    if(!empty($this->group_datas['dynamic_form']))
                    {									
                        $staticGroupsObj = $this->hotelsForm->getDisplayGroups();							
                        if($staticGroupsObj)
                        {
                            
                            $tabs = (!empty($this->group_datas['review_id'])) ? 12 : 11;
                            foreach($staticGroupsObj as $staticGroup)
                            {
                                echo '<li><a href="'.$tab_base_link.'#tabs-'.$tabs.'">'.$this->translator->translator($staticGroup->getAttrib('title')).'</a></li>';
                                $tabs++;
                            }
                        }
                    }
                    else
                    {
                        $staticGroupsObj = null;
                    }
                ?>
            </ul>
            
            <div id="tabs-1">
                <!-- Tab Detail Start -->
                    <div class="room-chart-container">
                    <form name="bookHotel" id="bookHotel" action="<?php echo $this->url(array('module' => 'Hotels','controller' =>'book', 'action' => 'booking','hotels_title' => $this->escape($this->view_datas['hotels_title']) ),'Book-Hotel/:hotels_title',true) ?>" method="post">
                            <div class="room-chart">
                                <!-- Header Start -->
                                    <div class="room-chart-row">
                                        <div class="room-chart-header-col-1 details-header-col-1">
                                            <?php echo $this->translator->translator('hotels_front_page_list_head_room_type'); ?>
                                        </div>
                                        
                                        <div class="room-chart-header-col-1 room-chart-header-col-2">
                                            <?php echo $this->translator->translator('hotels_front_page_list_head_people_per_room'); ?>
                                        </div>
                                        
                                        <div class="room-chart-header-col-1 room-chart-header-col-3 details-header-col-3">
                                            <?php echo $this->translator->translator('hotels_front_page_list_head_price_per_room'); ?>
                                        </div>
                                        
                                        <div class="room-chart-header-col-1 room-chart-header-col-4 details-header-col-4">
                                            <?php echo $this->translator->translator('hotels_front_page_list_head_no_apartments'); ?>
                                        </div> 
                                    </div>
                                <!-- Header End -->
                            </div>
                            
                                <?php														
                                    $room_type_name_arr = array();	
                                    $count = 0;									
                                    foreach($room_type_id_arr as $key=>$value)
                                    {
                                        $room_type_info = $this->room_type_db->getRoomTypeInfo($value);
                                        $room_type_name_arr[$key] = $this->escape($room_type_info['room_type']);														
                                        $row_class = ($key % 2 == 0) ? 'room-chart-row2' : 'room-chart-row2 room-chart-row3';	
                                        $height_style = (!empty($this->post_search_info) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]))	? 'style="height:70px"' : '';												
                                ?>
                            <div class="room-chart chart-border">
                                
                                <!-- Row-2 & Row-3 Start -->
                                <div class="<?php echo $row_class ?>" <?php echo $height_style; ?>>
                                    <div class="room-chart-c1 details-col-1">
                                        <span><a href="javascript: void(0);" class="toggle_desc preview chart-link" rel="<?php echo $this->escape($room_type_info['id']); ?>" link=""  title="<?php echo $this->escape($room_type_info['room_condition']); ?>"><?php echo $this->escape($room_type_info['room_type']); ?></a></span>
                                    </div>
                                    
                                    <div class="room-chart-c1 room-chart-c2" <?php echo $height_style; ?>>
                                        <a class="preview" link="" title="<?php echo $this->translator->translator('hotels_front_page_list_title_people',$this->escape($room_type_info['max_people'])); ?>">
                                            <?php 
                                                if($this->escape($room_type_info['max_people']) <= 4)
                                                {
                                                    for($i = 1; $i <= $this->escape($room_type_info['max_people']); $i++)
                                                    {
                                                        echo '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/people.png" border="0" />';
                                                    }
                                                } 
                                                else
                                                {
                                                    for($i = 1; $i <= 3; $i++)
                                                    {
                                                        echo '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/people.png" border="0" />';
                                                    }
                                                    echo '<span class="person-count">'.$this->escape($room_type_info['max_people']).'</span>';
                                                }
                                            ?>
                                        </a>
                                    </div>
                                    
                                    <div class="room-chart-c1 room-chart-c3 details-col-3" <?php echo $height_style; ?>>
                                        <span class="hotel-old-price"><?php echo $this->currency->getShortName().'&nbsp;'.$this->escape($room_type_info['basic_price']); ?></span>
                                        <span class="hotel-price"><?php echo $this->currency->getShortName().'&nbsp;'.$this->price($this->escape($room_type_info['descount_price'])); ?></span>
                                    </div>
                                    
                                    <div class="room-chart-c1 room-chart-c4 details-col-4" <?php echo $height_style; ?>>
                                        <?php																
                                            if(!empty($this->post_search_info) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]))
                                            {
                                                $room_info = $room_db->getAvailableRooms($room_type_info['id'], $this->post_search_info);																	
                                            ?>
                                            <select name="apartments_no<?php echo $count; ?>[]" id="apartments_no" class="apartments_no multi-hotel-room" multiple="multiple">
                                                <option value="0">0</option>
                                                <?php
                                                if($room_info)
                                                {
                                                    foreach($room_info as $room_info_key => $room_info_arr )
                                                    {
                                                        $price_sum = $this->price($this->escape($room_type_info['descount_price']));
                                                        echo '<option value="'.$room_info_arr['room_id'].'">'.$this->escape($room_info_arr['room_name'])/*.' ('.$this->currency->getShortName().'&nbsp;'.$price_sum.') '.$this->translator->translator('hotels_front_page_list_head_no_apartments_per_night')*/.'</option>';
                                                    }
                                                }
                                                ?>
                                            </select><input type="hidden" name="room_type_id[]" id="room_type_id" value="<?php echo $this->escape($room_type_info['id']); ?>" /><input type="hidden" name="hotel_id[]" id="hotel_id" value="<?php echo $this->escape($this->view_datas['id']); ?>" /><br />
                                            <?php 
                                            }
                                            else
                                            {
                                                $room_info = $room_db->getAvailableRooms($room_type_info['id'], array(Eicra_File_Constants::HOTELS_CHECK_IN => date("Y-m-d"), Eicra_File_Constants::HOTELS_CHECK_OUT => date("Y-m-d")));
                                            }
                                                $total_room_number = $room_db->getTotalRooms($room_type_info['id']);
                                                if((count($room_info) == $total_room_number) && $total_room_number != '0')
                                                {
                                                    echo $this->translator->translator('hotels_front_page_list_available_type_yes');
                                                }
                                                else if(count($room_info) == '0' || $total_room_number == '0')
                                                {
                                                    echo $this->translator->translator('hotels_front_page_list_available_type_no');
                                                }
                                                else if(count($room_info) == '1')
                                                {
                                                    echo '<a class="preview" link="" title="'.$this->translator->translator('hotels_front_page_list_available_type_last_desc', $this->currency->getShortName().'&nbsp;'.$this->price($this->escape($room_type_info['descount_price']))).'">'.$this->translator->translator('hotels_front_page_list_available_type_llast', count($room_info)).'</a>';
                                                }
                                                else if(count($room_info) > '1' && count($room_info) <= $total_room_number)
                                                {
                                                    echo $this->translator->translator('hotels_front_page_list_available_type_left', count($room_info));
                                                }
                                             ?>
                                    </div>                                                                       
                                </div>
                                
                                </div>
                                <div class="room-chart chart-border">
                               
                                    <div id="room_type_desc<?php echo $room_type_info['id']; ?>"  class="room-chart-details">
                                            <?php
                                                if(!empty($room_type_info['room_type_image']))
                                                {
                                                    $room_type_im_arr = explode(',', $room_type_info['room_type_image']);
                                                    foreach($room_type_im_arr as $key=>$value)
                                                    {
                                            ?>
                                                        <a href="javascript:void(0)" link="data/frontImages/hotels/room_type_image/<?php echo $value; ?>" class="change_img preview" title="<?php echo $this->escape($room_type_info['room_type']); ?>" <?php echo $width; ?> <?php echo $height; ?> ><img src="data/frontImages/hotels/room_type_image/<?php echo $value; ?>" width="90" border="0" class="thumb"/></a> &nbsp;
                                            <?php
                                                    }
                                                }
                                                echo '<div class="clear"><p>'.nl2br($this->escape($room_type_info['room_desc'])).'</p></div>';
                                                if(!empty($this->post_search_info) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]) && $room_type_info['price_setting_type'] == '2')
                                                {
                                                    if($room_info)
                                                    {
                                                        $totalNights = getNights($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN] , $this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]) + 1;
                                                        foreach($room_info as $room_infos_key => $room_infos_arr )
                                                        {	
                                            ?>
                                                            <div>
                                            <?php																
                                                            $roomCalendar_info = $this->roomCalendar_db->getCalendarInfo($room_infos_arr['room_id'], $this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN] , $this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]);
                                                            
                                                            if($roomCalendar_info && ($totalNights == count($roomCalendar_info)))
                                                            {
                                            ?>
                                                            <fieldset class="room-types">
                                                                <legend><?php  echo $this->escape($room_infos_arr['room_name']).' ----------------- '.$this->currency->getShortName().'&nbsp;'.$price_sum.'&nbsp;'.$this->currency->getSymbol(); ?></legend>
                                                                <div class="price-container">
                                                                    <div class="room-per-day">
                                                                        <span class="mod-label"><?php echo $this->translator->translator('hotels_details_room_day'); ?></span>
                                                                    </div>
                                                                    
                                                                    <div class="price-per-day">
                                                                        <span class="mod-label"><?php echo $this->translator->translator('hotels_details_room_price'); ?></span>
                                                                    </div>
                                                                    <?php
                                                                        foreach($roomCalendar_info	as $roomCalendar_info_key	=> $roomCalendar_info_arr)
                                                                        {
                                                                    ?>
                                                                    <div class="room-per-day"><?php echo $roomCalendar_info_arr['calendar_date']; ?></div>
                                                                    <div class="price-per-day"><?php echo $this->currency->getShortName().'&nbsp;'.$this->price($roomCalendar_info_arr['room_price']).'&nbsp;'.$this->currency->getSymbol(); ?></div>
                                                                    <?php	
                                                                        }
                                                                    ?>
                                                                </div>	
                                                            </fieldset>			
                                            <?php	
                                                                /*echo '<pre>';
                                                                print_r($roomCalendar_info);
                                                                echo '</pre>';*/
                                                            }
                                                            else
                                                            {
                                            ?>
                                                                <div class="room-types">
                                                                    <h6><?php  echo $this->escape($room_infos_arr['room_name']).' ----------------- '.$this->currency->getShortName().'&nbsp;'.$price_sum.'&nbsp;'.$this->currency->getSymbol(); ?></h6>
                                                                </div>
                                            <?php
                                                            }
                                            ?>
                                                            </div>
                                            <?php
                                                        }
                                                    }
                                                }
                                            ?>
                                    </div>      
                                </div>
                                <!-- Row-2 & Row-3 End -->                                            
                                <?php														
                                        $count++;
                                    }
                                ?>	                                  
                                    
                                <?php
                                    if(!empty($this->post_search_info) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]))
                                    {
                                
                                    if($global_conf['payment_system'] == 'On'){
                                ?>
                                  
                             <div class="room-chart book-btn-area">    
                             	<div class="form-button"><a href="javascript: void(0);" class="book_btn" rel="#tabs-1" ><?php echo $this->translator->translator('hotels_front_page_show_price'); ?></a></div>
                             </div>                                
                                <?php
                                    }
                                   	}
                                ?>
                    <input type="hidden" name="<?php echo Eicra_File_Constants::HOTELS_CHECK_IN; ?>" id="<?php echo Eicra_File_Constants::HOTELS_CHECK_IN; ?>" value="<?php echo $this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]; ?>" /><input type="hidden" name="<?php echo Eicra_File_Constants::HOTELS_CHECK_OUT; ?>" id="<?php echo Eicra_File_Constants::HOTELS_CHECK_OUT; ?>" value="<?php echo $this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]; ?>" />
                    </form>
                    </div>
                <!-- Tab Detail End -->
                
                <!-- Hotel Summary Start -->
                
                <div class="products-feature">
                    <div class="products-details">
                        <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('hotels_front_page_Title_summary'); ?></h4></div>
                        <div class="content feature-content">
                        <?php
                        if($this->escape($this->hotelsForm->category_id->getValue()))
                        {
                        ?>
                        <div class="summary-label"><?php echo $this->hotelsForm->category_id->getAttrib('font_end_label'); ?></div>
                        <div class="summary-value">
                            <?php	  	
                                $cat_db =  new Hotels_Model_DbTable_Category();
                                $cat_info = $cat_db->getCategoryInfo($this->escape($this->hotelsForm->category_id->getValue()));
                                echo $this->escape($cat_info['category_name']);
                        ?>
                        </div>
                        
                        <?php
                         }
                         if($this->hotelsForm->feature_pet->getValue())
                         {
                        ?>
                        <div class="summary-label"><?php  echo $this->hotelsForm->feature_pet->getAttrib('font_end_label'); ?></div>
                        <div class="summary-value"><?php echo $this->escape($this->hotelsForm->feature_pet->getValue()); ?></div>
                        
                        <?php
                          }
                          if($this->view_datas['checkin_date'] != '00:00:00')
                         {
                         ?>
                         <div class="summary-label"><?php  echo $this->hotelsForm->checkin_hour->getAttrib('font_end_label'); ?></div>
                         <div class="summary-value"><?php echo $this->escape($this->view_datas['checkin_date']).' '.$this->view_datas['checkin_time']; ?></div>
                         <?php
                          }
                          if($this->view_datas['checkout_date'] != '00:00:00')
                         {
                         ?>
                         <div class="summary-label"><?php echo $this->hotelsForm->checkout_hour->getAttrib('font_end_label'); ?></div>
                         <div class="summary-value"><?php echo $this->escape($this->view_datas['checkout_date']).' '.$this->view_datas['checkout_time']; ?></div>
                         <?php
                         }
                         if($this->hotelsForm->feature_distance_from_airport->getValue() || $this->hotelsForm->feature_distance_from_city_market->getValue())
                         {
                         ?>
                         <div class="summary-label"><?php echo $this->hotelsForm->feature_distance_from_airport->getAttrib('font_end_label');  ?></div>
                         <div class="summary-value"><?php echo $this->escape($this->hotelsForm->feature_distance_from_airport->getValue()).' '.$this->translator->translator('hotels_front_page_label_distance_km').'<br />'.$this->escape($this->hotelsForm->feature_distance_from_city_market->getValue()).' '.$this->translator->translator('hotels_front_page_label_distance_km_city_market'); ?></div>
                         <?php
                         }
                         if($this->hotelsForm->hotels_about_internet->getValue())
                         {
                         ?>
                         <div class="summary-label"><?php echo $this->hotelsForm->hotels_about_internet->getAttrib('font_end_label');  ?></div>
                         <div class="summary-value"><?php echo $this->escape($this->hotelsForm->hotels_about_internet->getValue()); ?></div>
                         <?php
                         }
                         if($this->hotelsForm->hotels_about_parking->getValue())
                         {
                         ?>
                         <div class="summary-label"><?php echo $this->hotelsForm->hotels_about_parking->getAttrib('font_end_label');  ?></div>
                         <div class="summary-value"><?php echo $this->escape($this->hotelsForm->hotels_about_parking->getValue()); ?></div>
                          <?php
                         }
                         ?>  
                        </div>
                    </div>                    
                </div>
                <!-- Hotel Summary End -->
                
                <!-- Hotel Agent Start-->
                <?php
                    //Checking Membership Package Option
                    $packages = new Members_Controller_Helper_Packages();
                    $general_db = new Members_Model_DbTable_General();
                    $forms_db = new Members_Model_DbTable_Forms();
                    $mem_info = (isnot_int($this->view_datas['hotels_agent'])) ? $mem_db->getMemberInfo($this->view_datas['entry_by']) : $mem_db->getMemberInfo($this->view_datas['hotels_agent']);	
                    $module = $this->module;
                    $controller = $this->controller;
                    $action = $this->action;
                    if($packages->checkFormAvailable('Default Info'))
                    {
                        $default_form_id  = $forms_db->getFormId('Default Info');
                        $default_form_info['form_id'] = 	$default_form_id[0]['id'];
                        $default_general_info = $general_db->getAllValues($default_form_id[0]['id']);												
                        $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
                        if($default_general_info)
                        {								
                            $default_general_info = (!empty($default_general_info[0]) && !empty($default_general_info[0]['id'])) ? $default_general_info :  $default_general_info->toArray();
                            $default_form_info	=	$dynamic_valu_db->getFieldsValueInfo($default_form_info,$default_general_info[0]['id']);									
                        }
                        else
                        {
                            $default_form_info = null;
                        }						
                    }
                    else
                    {
                        $default_form_info = null;
                    }
                    if($packages->isPackageFrontend($mem_info['user_id'],$mem_info['role_id']))
                    {															
                        if($packages->isPackageFrontendField($module,$controller,$action,$mem_info['user_id'],$mem_info['role_id']))
                        {
                            $package_no = $packages->getPackageFrontendFieldValue($module,$controller,$action,$mem_info['user_id'],$mem_info['role_id']);				
                        }
                        else
                        {
                            $package_no = 'Off';
                        }
                    }
                    else
                    {
                        $package_no = 'On';
                    }
                    
                    
                if($package_no == 'On')
                {	
                    
                ?>
                <div class="products-agent">
                    <div class="products-details">
                       	<div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('hotels_front_page_Title_realtor'); ?></h4></div>
                        	<div class="content">
								<?php
                                    if($this->escape($this->view_datas['hotels_agent']))
                                    {
                                        $mem_db = new Members_Model_DbTable_MemberList();
                                        $owner_info = (isnot_int($this->view_datas['hotels_agent'])) ? $this->escape($this->view_datas['hotels_agent']) : $mem_db->getMemberInfo($this->escape($this->view_datas['hotels_agent']));
                                        $owner_name = (is_array($owner_info)) ? $owner_info['title'].' '.$owner_info['firstName'].' '.$owner_info['lastName'] : $owner_info;	
                                        //echo $this->escape($owner_name);
                                        $mem_user_id = (is_array($owner_info)) ? $owner_info['user_id'] : $mem_info['user_id'];
                                        $mem_role_id = (is_array($owner_info)) ? $owner_info['role_id'] : $mem_info['role_id'];
                                        if(is_array($owner_info))
                                        {
                                            $role_db = new Members_Model_DbTable_Role();
                                            $role_info = $role_db->getRoleInfo($owner_info['role_id']);
                                            $owner_info['form_id'] = 	$role_info['form_id'];
                                            $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
                                            $owner_info	=	$dynamic_valu_db->getFieldsValueInfo($owner_info,$owner_info['user_id']);
                                            foreach($owner_info as $key=>$value)
                                            {
                                                $field_name_arr = explode('_',$key);
                                                if(in_array('package',$field_name_arr))
                                                {
                                                    $package_info = $packages->getFormAllDatas($value);
                                                }
                                            }
                                        }
                                        else
                                        {
                                            $mem_user_id = $mem_info['user_id'];
                                            $mem_role_id = $mem_info['role_id'];
                                            $role_db = new Members_Model_DbTable_Role();
                                            $role_info = $role_db->getRoleInfo($mem_role_id);
                                            $mem_info['form_id'] = 	$role_info['form_id'];
                                            $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
                                            $mem_info	=	$dynamic_valu_db->getFieldsValueInfo($mem_info,$mem_user_id);
                                            foreach($mem_info as $key=>$value)
                                            {
                                                $field_name_arr = explode('_',$key);
                                                if(in_array('package',$field_name_arr))
                                                {
                                                    $package_info = $packages->getFormAllDatas($value);
                                                }
                                            }
                                        }
                                    }
                                    else
                                    {
                                        $mem_user_id = $mem_info['user_id'];
                                        $mem_role_id = $mem_info['role_id'];
                                        $role_db = new Members_Model_DbTable_Role();
                                        $role_info = $role_db->getRoleInfo($mem_role_id);
                                        $mem_info['form_id'] = 	$role_info['form_id'];
                                        $dynamic_valu_db = new Members_Model_DbTable_FieldsValue();	
                                        $mem_info	=	$dynamic_valu_db->getFieldsValueInfo($mem_info,$mem_user_id);
                                        foreach($mem_info as $key=>$value)
                                        {
                                            $field_name_arr = explode('_',$key);
                                            if(in_array('package',$field_name_arr))
                                            {
                                                $package_info = $packages->getFormAllDatas($value);
                                            }
                                        }
                                    }
                                    ?>          
                                    <?php
                                        if(is_array($owner_info))
                                        {
                                            if($owner_info['member_photo'])
                                            {
                                                $owner_forms_info = $forms_db->getFormsInfo($role_info['form_id']);
                                                if($owner_info['member_photo'])
                                                {
                                                    $member_photo_path = $owner_forms_info['attach_file_path'];
                                                    $member_photo = $member_photo_path.'/'.$owner_info['member_photo'];
                                                    $member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
                                                    $member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
                                                }
                                                else
                                                {
                                                    if(!empty($default_form_info))
                                                    {
                                                            $member_photo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['member_photo_default'];
                                                            $member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
                                                            $member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
                                                    }
                                                    else
                                                    {
                                                            $member_photo = 'data/frontImages/hotels/design_images/no_user_image.gif';
                                                            $member_photo_width = 'width="75"';
                                                            $member_photo_height = 'height="87"';
                                                    }
                                                }
                                            }
                                            else
                                            {												
                                                    if(!empty($default_form_info))
                                                    {
                                                            $member_photo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['member_photo_default'];
                                                            $member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
                                                            $member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
                                                    }
                                                    else
                                                    {
                                                            $member_photo = 'data/frontImages/hotels/design_images/no_user_image.gif';
                                                            $member_photo_width = 'width="75"';
                                                            $member_photo_height = 'height="87"';
                                                    }
                                            }
                                        }
                                        else
                                        {
                                            if(!empty($default_form_info))
                                            {
                                                    $member_photo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['member_photo_default'];
                                                    $member_photo_width = 'width="'.$default_form_info['member_photo_width_default'].'"';
                                                    $member_photo_height = 'height="'.$default_form_info['member_photo_height_default'].'"';
                                            }
                                            else
                                            {
                                                    $member_photo = 'data/frontImages/hotels/design_images/no_user_image.gif';
                                                    $member_photo_width = 'width="75"';
                                                    $member_photo_height = 'height="87"';
                                            }
                                        }
                                                                            
                                    ?>
                                    <img src="<?php echo $member_photo; ?>" <?php echo $member_photo_width.' '.$member_photo_height; ?> class="avatar"/>
                        
                                    <div>
                                    	<span class="label"><?php echo $this->translator->translator('hotels_front_page_label_presented'); ?></span>
										<span class="value"><?php echo $this->escape($owner_name); ?></span>
									</div>
                                    
                                    <div>
                                        <div class="pkg-img">
                                            <?php                                                                                            
                                                if($packages->isPackageFrontendField($module,$controller,$action.'_pic',$mem_user_id,$mem_role_id))
                                                {													
                                                    $package_pic_info = $packages->getPackageFrontendFieldDetailsValue($module,$controller,$action.'_pic',$mem_user_id,$mem_role_id);				
                                                    
                                                    if(!empty($package_pic_info))
                                                    {
                                                        $forms_info = $forms_db->getFormsInfo($package_pic_info['form_id']);
                                                        if(!empty($package_pic_info['field_value']))
                                                        {
                                                            $package_pic = $this->serverUrl().$this->baseUrl().'/'. $forms_info['attach_file_path'].'/'.$package_pic_info['field_value'];
                                                            $package_pic_width = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_width',$mem_user_id,$mem_role_id);
                                                            $package_pic_height = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_height',$mem_user_id,$mem_role_id);
                                                            $package_pic_width_field = ($package_pic_width) ? 'width="'.$package_pic_width.'"' : '';
                                                            $package_pic_height_field = ($package_pic_width) ? 'height="'.$package_pic_height.'"' : '';
                                                        }
                                                        else
                                                        {
                                                            $package_pic = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['property_frontend_details_pic_default'];
                                                            $package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="'.$default_form_info['property_frontend_details_pic_width_default'].'"' : '';
                                                            $package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="'.$default_form_info['property_frontend_details_pic_height_default'].'"' : '';
                                                        }
                                                    }
                                                    else
                                                    {
                                                        $package_pic = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['property_frontend_details_pic_default'];
                                                        $package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="'.$default_form_info['property_frontend_details_pic_width_default'].'"' : '';
                                                        $package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="'.$default_form_info['property_frontend_details_pic_height_default'].'"' : '';
                                                    }
                                                }
                                                else
                                                {
                                                    $package_pic = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['property_frontend_details_pic_default'];
                                                    $package_pic_width_field = (!empty($default_form_info['property_frontend_details_pic_width_default'])) ? 'width="'.$default_form_info['property_frontend_details_pic_width_default'].'"' : '';
                                                    $package_pic_height_field = (!empty($default_form_info['property_frontend_details_pic_height_default'])) ? 'height="'.$default_form_info['property_frontend_details_pic_height_default'].'"' : '';
                                                }
                                                
                                                if($package_pic)
                                                {
                                            ?>
                                            <img src="<?php echo $package_pic; ?>" <?php echo $package_pic_width_field.' '.$package_pic_height_field; ?> />
                                            <?php
                                                }
                                            ?>	
                                        </div>   
                                        <span class="label"><?php if(($package_info[0]['field_value'])){ echo $this->translator->translator('common_package_name_title'); } ?></span><br />
                                        <span class="pkg-title"><?php echo $this->escape($package_info[0]['field_value']); ?></span>
                                    </div>
                                    
                                    <hr />
                                    
                                    <?php
                                    if($packages->isPackageFrontendField($module,$controller,$action.'_certified',$mem_user_id,$mem_role_id))
                                    {
                                        $allow_certified = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_certified',$mem_user_id,$mem_role_id);				
                                    }
                                    else
                                    {
                                        $allow_certified = 'No';
                                    }
                                    if($packages->isPackageFrontendField($module,$controller,$action.'_allow_logo',$mem_user_id,$mem_role_id))
                                    {
                                        $allow_logo = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_allow_logo',$mem_user_id,$mem_role_id);				
                                    }
                                    else
                                    {
                                        $allow_logo = 'No';
                                    }
                                    ?>
                                    
                                    <div>
                                            <?php
                                                    
                                            if($allow_logo == 'Yes')
                                            {									
                                                if(is_array($owner_info))
                                                {
                                                    if($owner_info['company_logo'])
                                                    {
                                                        $company_logo_path = $owner_forms_info['attach_file_path'];
                                                        $company_logo = $company_logo_path.'/'.$owner_info['company_logo'];
                                                        $company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="'.$default_form_info['company_logo_width_default'].'"' : '';
                                                        $company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="'.$default_form_info['company_logo_height_default'].'"' : '';
                                                    }
                                                    else
                                                    {
                                                        if(!empty($default_form_info))
                                                        {
                                                            $company_logo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['company_logo_default'];
                                                            $company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="'.$default_form_info['company_logo_width_default'].'"' : '';
                                                            $company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="'.$default_form_info['company_logo_height_default'].'"' : '';
                                                        }
                                                        else
                                                        {
                                                            $company_logo = 'data/frontImages/hotels/design_images/no_company_logo.gif';
                                                            $company_logo_width = 'width="80"';
                                                            $company_logo_height = 'height="60"';
                                                        }
                                                    }
                                                }
                                                else
                                                {
                                                    if(!empty($default_form_info))
                                                    {
                                                        $company_logo = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$default_form_info['company_logo_default'];
                                                        $company_logo_width = ($default_form_info['company_logo_width_default']) ? 'width="'.$default_form_info['company_logo_width_default'].'"' : '';
                                                        $company_logo_height = ($default_form_info['company_logo_height_default']) ? 'height="'.$default_form_info['company_logo_height_default'].'"' : '';
                                                    }
                                                    else
                                                    {
                                                        $company_logo = 'data/frontImages/hotels/design_images/no_company_logo.gif';
                                                        $company_logo_width = 'width="80"';
                                                        $company_logo_height = 'height="60"';
                                                    }
                                                }
                                        ?>
                                        <img src="<?php echo $company_logo; ?>" <?php echo $company_logo_width.' '.$company_logo_height; ?> class="company-logo"/>
                                        <?php
                                            }
                                        ?>
                                    </div>
                                     <?php
                                    
                                        if($packages->isPackageFrontendField($module,$controller,$action.'_contact_directly',$mem_user_id,$mem_role_id))
                                        {
                                            $contact_directly = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_contact_directly',$mem_user_id,$mem_role_id);				
                                        }
                                        else
                                        {
                                            $contact_directly = 'No';
                                        }
                                        if($contact_directly == 'Yes')
                                        {
                                        ?>
                                    <div class="company-info">
                                        <!-- Company Name -->
                                        <div>
                                            <span class="label"><?php if(is_array($owner_info) && !empty($owner_info['companyName'])){  echo $this->translator->translator('hotels_front_page_label_company'); } ?></span>
                                            <?php if(is_array($owner_info)){ echo $this->escape($owner_info['companyName']); } ?>
                                        </div>
                                        <!-- Company Name -->
                                        
                                        
                                        <!-- Address -->
                                        <div>
                                            <span class="label"><?php echo $this->translator->translator('hotels_front_page_label_contact'); ?></span><br />
                                            <?php 
                                            $hotels_building_no = $this->hotelsForm->hotels_building_no->getValue();
                                            if(!empty($hotels_building_no))
                                            {
                                                echo $this->hotelsForm->hotels_building_no->getAttrib('font_end_label');
                                                echo $this->escape($hotels_building_no); 
                                             }
                                            ?><br />
                                            <?php
                                                if(is_array($owner_info) && $owner_info['city'])
                                                {												
                                                    echo $this->translator->translator('hotels_front_page_label_city'); 
                                                    echo " ".$this->escape($owner_info['city']);
                                                }
                                            ?><br />
                                            <?php 
                                                if(is_array($owner_info) && $owner_info['state'])
                                                {
                                                    echo $this->translator->translator('hotels_front_page_label_state'); 
                                                    echo " ".$this->escape($owner_info['state']);
                                                }
                                            ?><br />
                                            <?php  
                                                if(is_array($owner_info) && $owner_info['country'])
                                                {
                                                    echo $this->translator->translator('hotels_front_page_label_country');
                                                    $owner_country_info = $country_db->getCountryName($owner_info['country']);
                                                    echo " ".$this->escape($owner_country_info['value']);
                                                }
                                            ?><br />
                                            <?php 
                                                $post_code = $this->hotelsForm->post_code->getValue();
                                                if(is_array($owner_info) && !empty($owner_info['postalCode']))
                                                {
                                                    echo $this->hotelsForm->post_code->getAttrib('font_end_label');
                                                    echo " ".$this->escape($owner_info['postalCode']);	
                                                }
                                            ?>	
                                        </div>                                        
                                        <!-- Address -->
                                        
                                        
                                       
                                        
                                        <!-- Tel -->
                                        <?php
                                            $hotels_phone = $this->hotelsForm->hotels_phone->getValue();
                                            if(is_array($owner_info) && !empty($owner_info['phone']))
                                            {
                                        ?>										
                                            <div>
                                                <span class="label"><?php echo $this->hotelsForm->hotels_phone->getAttrib('font_end_label'); ?></span>
                                                <?php echo $this->escape($owner_info['phone']); ?>
                                            </div>                                                                      
                                        <?php
                                            }
                                        ?>
                                        <!-- Tel --> 
                                        
                                        <!-- Fax -->
                                        <?php
                                            $hotels_fax = $this->hotelsForm->hotels_fax->getValue();
                                            if(is_array($owner_info) && !empty($owner_info['fax']))
                                            {
                                        ?>                                        
                                            <div>
                                                <span class="label"><?php echo $this->hotelsForm->hotels_fax->getAttrib('font_end_label'); ?></span>
                                                <?php echo $this->escape($owner_info['fax']); ?>
                                            </div>										
                                        <?php
                                            }
                                        ?>
                                        <!-- Fax -->
                                        
                                        <!-- Email -->
                                        <div>
                                            <a href="<?php if(is_array($owner_info)){ echo 'mailto:'.$this->escape($owner_info['username']); }else{ echo 'mailto:'.$this->escape($this->view_datas['house_email']) ;} ?>" class="agent-email"><?php echo $this->translator->translator('hotels_front_page_label_email_lang'); ?></a>
                                        </div>
                                        <!-- Email -->
                                        
                                        <!-- Web -->
                                        <?php								  		
                                        if(is_array($owner_info) && !empty($owner_info['website']))
                                        {
                                        ?>                                        
                                        <div>
                                            <span class="label"><?php echo $this->translator->translator('hotels_front_page_label_web'); ?></span>
                                            <a href="<?php if(is_array($owner_info)){ echo 'http://'.$this->escape($owner_info['website']); } ?>" target="_blank" class="agent-web"><?php if(is_array($owner_info)){ echo $this->escape($owner_info['website']); } ?></a>
                                        </div>                                        
                                        <?php
                                        }
                                        ?>
                                        <!-- Web -->                                        
                                    </div>
                                    
                                    <?php
                                        }
                                      ?>
                                   
                                    <?php
                                    if($allow_certified == 'Yes')
                                    {
                                    ?>
                                    <hr />
                                    <!-- Certifdicate -->
                                    <div class="certificate">
                                         <?php												
                                                if($packages->isPackageFrontendField($module,$controller,$action.'_pic_certi',$mem_user_id,$mem_role_id))
                                                {
                                                    $package_pic_certi_info = $packages->getPackageFrontendFieldDetailsValue($module,$controller,$action.'_pic_certi',$mem_user_id,$mem_role_id);				
                                                    if(!empty($package_pic_certi_info))
                                                    {
                                                        $forms_info = $forms_db->getFormsInfo($package_pic_certi_info['form_id']);
                                                        if(!empty($package_pic_certi_info['field_value']))
                                                        {
                                                            $package_pic_certi = $this->serverUrl().$this->baseUrl().'/'. $forms_info['attach_file_path'].'/'.$package_pic_certi_info['field_value'];
                                                            $package_pic_certi_width = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_certi_width',$mem_user_id,$mem_role_id);
                                                            $package_pic_certi_height = $packages->getPackageFrontendFieldValue($module,$controller,$action.'_pic_certi_height',$mem_user_id,$mem_role_id);
                                                            $package_pic_certi_width_field = ($package_pic_certi_width) ? 'width="'.$package_pic_certi_width.'"' : '';
                                                            $package_pic_certi_height_field = ($package_pic_certi_height) ? 'height="'.$package_pic_certi_height.'"' : '';
                                                        }
                                                        else
                                                        {
                                                            $certi_pic_arr = explode(',',$default_form_info['property_frontend_details_pic_certi_default']);
                                                            $package_pic_certi = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$certi_pic_arr[0];
                                                            $package_pic_certi_width_field = ($default_form_info['property_frontend_details_pic_certi_width_default']) ? 'width="'.$default_form_info['property_frontend_details_pic_certi_width_default'].'"' : '';
                                                            $package_pic_certi_height_field = ($default_form_info['property_frontend_details_pic_certi_height_default']) ? 'height="'.$default_form_info['property_frontend_details_pic_certi_height_default'].'"' : '';
                                                        }
                                                    }
                                                    else
                                                    {
                                                        $certi_pic_arr = explode(',',$default_form_info['property_frontend_details_pic_certi_default']);
                                                        $package_pic_certi = $this->serverUrl().$this->baseUrl().'/'. $default_form_id[0]['attach_file_path'].'/'.$certi_pic_arr[0];
                                                        $package_pic_certi_width_field = ($default_form_info['property_frontend_details_pic_certi_width_default']) ? 'width="'.$default_form_info['property_frontend_details_pic_certi_width_default'].'"' : '';
                                                        $package_pic_certi_height_field = ($default_form_info['property_frontend_details_pic_certi_height_default']) ? 'height="'.$default_form_info['property_frontend_details_pic_certi_height_default'].'"' : '';
                                                    }
                                                }
                                                else
                                                {
                                                    $package_pic_certi = null;
                                                }
                                                if($package_pic_certi)
                                                {
                                        ?>
                                                    <img src="<?php echo $package_pic_certi; ?>" <?php echo $package_pic_certi_width_field.' '.$package_pic_certi_height_field; ?> />
                                        <?php
                                                }											
                                         ?>
                                        <p><?php if($allow_certified == 'Yes'){ echo $this->translator->translator('hotels_front_page_label_verified'); } ?></p>
                                    </div>
                                    <!-- Certificate -->
                                    <?php
                                    }
                                    ?>
                        </div>
                    </div>
                </div>
                <?php
                }
                ?>
                <!-- Hotel Agent End-->
            </div>
                
            <div id="tabs-2">
                <h2><?php echo $this->translator->translator('hotels_front_page_Title_images'); ?></h2>
                
                <?php
                    if($this->group_datas['file_thumb_width'] && ($this->group_datas['file_thumb_resize_func'] != 'resizeToHeight' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
                    { 
                        $width_img = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
                    }
                    else
                    {
                        $width_img = '';
                    } 
                    if($this->group_datas['file_thumb_height'] && ( $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
                    { 
                        $height_img = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
                    } 
                    else
                    {
                        $height_img = '';
                    }
                    $img_arr = explode(',',$this->hotelsForm->hotels_image->getValue());
                    $i = 1;
                    foreach($img_arr as $key => $value)
                    {
                ?>              
                <div>
                    <a href="javascript:void(0);" class="change_img preview" link="data/frontImages/hotels/hotels_image/<?php echo $value; ?>" <?php echo $width; ?> <?php echo $height; ?> title="<?php echo $this->escape($this->hotelsForm->hotels_name->getValue()); ?>"><img src="data/frontImages/hotels/hotels_image/<?php echo $value; ?>" <?php echo $width_img.' '.$height_img; ?> border="0" class="thumb additional-thumb"/></a>  
                </div>
                <?php                                   
                     $i++;
                  }
                ?>
            </div>
            
            <div id="tabs-3">
                <h2><?php echo $this->translator->translator('hotels_front_page_Title_floorplan'); ?></h2>
                
                <?php
                    if($this->group_datas['file_thumb_width'] && ($this->group_datas['file_thumb_resize_func'] != 'resizeToHeight' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
                    { 
                        $width_img = 'width="'.$this->escape($this->group_datas['file_thumb_width']).'"'; 
                    }
                    else
                    {
                        $width_img = '';
                    } 
                    if($this->group_datas['file_thumb_height'] && ( $this->group_datas['file_thumb_resize_func'] != 'resizeToWidth' || $this->group_datas['file_thumb_resize_func'] != 'resize' ))
                    { 
                        $height_img = 'height="'.$this->escape($this->group_datas['file_thumb_height']).'"'; 
                    } 
                    else
                    {
                        $height_img = '';
                    }
                    if($this->view_datas['feature_interior_plan_image'])
                    {
                        $img_froor_arr = explode(',',$this->view_datas['feature_interior_plan_image']);
                        $i = 1;
                        foreach($img_froor_arr as $key => $value)
                        {
                    ?>
                    <div>
                        <a href="javascript:void(0);" class="change_img preview" link="data/frontImages/hotels/interior_plan_image/<?php echo $value; ?>" <?php echo $width; ?> <?php echo $height; ?> title="<?php echo $this->escape($this->hotelsForm->hotels_name->getValue()); ?>"><img src="data/frontImages/hotels/interior_plan_image/<?php echo $value; ?>" <?php echo $width_img.' '.$height_img; ?> border="0" class="thumb additional-thumb"/></a>
                    </div>
                    <?php
                            $i++;
                        }
                    }
                ?>
            </div>
            
            <div id="tabs-4">
            	 <div class="products-details">
                 	<div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('hotels_front_page_hotels_features'); ?></h4></div>
                        <div class="content">
                            <div class="details-info">
                            	<h2><?php echo $this->hotelsForm->feature_facilities->getAttrib('font_end_label'); ?></h2>
                            	<?php
										$feature_facilities = $this->hotelsForm->feature_facilities->getValue();
										if(!empty($feature_facilities))
										{ 
											$feature_facilities_arr = explode(',', $feature_facilities); 
											foreach($feature_facilities_arr as $key=>$value)
											{
												echo '<div class="products-features"> &bull; '.$this->escape($value).'</div>';
											}
										}						  
								?>
								  
								<hr/>
							
								<h2><?php echo $this->hotelsForm->feature_sports_recreations->getAttrib('font_end_label'); ?></h2>
								
								<?php 
									$feature_sports_recreations = $this->hotelsForm->feature_sports_recreations->getValue();
									if(!empty($feature_sports_recreations))
									{ 
										$feature_sports_recreations_arr = explode(',', $feature_sports_recreations); 
										foreach($feature_sports_recreations_arr as $key=>$value)
										{
											echo '<div class="products-features"> &bull; '.$this->escape($value).'</div>';
										}
									}						  
								?>
								
								<?php 
									$feature_additional = $this->hotelsForm->feature_additional->getValue();
									if(!empty($feature_additional)){ ?>
								<hr/>
								
								<h2><?php echo $this->hotelsForm->feature_additional->getAttrib('font_end_label');  ?></h2>
								
								<?php 
									echo '<p">'.$this->escape($feature_additional).'</p>'; 						  
								?>
								
								<?php } ?>
                            </div>
                        </div>
                 </div>
            </div>
            
            <div id="tabs-5">
            	<div class="products-details">
                 		<div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('hotels_front_page_hotels_profile'); ?></h4></div>
                        <div class="content">
                        	<?php
								$hotels_building_name = $this->hotelsForm->hotels_building_name->getValue();
								if(!empty($hotels_building_name))
								{
							?>
							
							<h2><?php echo $this->hotelsForm->hotels_building_name->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_building_name); ?></p>
							<hr />
							
							<?php
								}
								$hotels_building_no = $this->hotelsForm->hotels_building_no->getValue();
								if(!empty($hotels_building_no))
								{
							?>
							<h2><?php echo $this->hotelsForm->hotels_building_no->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_building_no); ?></p>
							<hr />
							
							<?php
								}
								$hotels_phone = $this->hotelsForm->hotels_phone->getValue();
								if(!empty($hotels_phone))
								{
							?>
							<h2><?php echo $this->hotelsForm->hotels_phone->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_phone); ?></p>
							<hr />
							
							<?php
								}
								$hotels_fax = $this->hotelsForm->hotels_fax->getValue();
								if(!empty($hotels_fax))
								{
							?>
							<h2><?php echo $this->hotelsForm->hotels_fax->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_fax); ?></p>
							<hr />
							
							<?php
								}
								$hotels_email = $this->hotelsForm->hotels_email->getValue();
								if(!empty($hotels_email))
								{
							?>
							<h2><?php echo $this->hotelsForm->hotels_email->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_email); ?></p>
							<hr />
							
							<?php
								}
								$post_code = $this->hotelsForm->post_code->getValue();
								if(!empty($post_code))
								{
							?>
							<h2><?php echo $this->hotelsForm->post_code->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($post_code); ?></p>
							<hr />
							
							<?php
								}
								$hotels_address = $this->hotelsForm->hotels_address->getValue();
								if(!empty($hotels_address))
								{
							?>
							<h2><?php echo $this->hotelsForm->hotels_address->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_address); ?></p>
							<hr />
							
							<?php
								}
								$hotels_about_information = $this->hotelsForm->hotels_about_information->getValue();
								if(!empty($hotels_about_information))
								{
							?>
							
							<h2><?php echo $this->hotelsForm->hotels_about_information->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_about_information); ?></p>
							<hr />
							
							<?php
								}
								$hotels_about_general = $this->hotelsForm->hotels_about_general->getValue();
								if(!empty($hotels_about_general))
								{
							?>
							
							<h2><?php echo $this->hotelsForm->hotels_about_general->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_about_general); ?></p>
							<hr />
							
							<?php
								}
								$hotels_about_services = $this->hotelsForm->hotels_about_services->getValue();
								if(!empty($hotels_about_services))
								{
							?>
							
							<h2><?php echo $this->hotelsForm->hotels_about_services->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_about_services); ?></p>
							<hr />
							
							<?php
								}
								$hotels_policy_surroundings = $this->hotelsForm->hotels_policy_surroundings->getValue();
								if(!empty($hotels_policy_surroundings))
								{
							?>
							
							<h2><?php echo $this->hotelsForm->hotels_policy_surroundings->getAttrib('font_end_label'); ?></h2>
							<p><?php echo $this->escape($hotels_policy_surroundings); ?></p>
							<hr />
							
							<?php
								}
								$hotels_about_other = $this->hotelsForm->hotels_about_other->getValue();
								if(!empty($hotels_about_other))
								{
							?>
							
							<h2><?php echo $this->hotelsForm->hotels_about_other->getAttrib('font_end_label');  ?></h2>
							<p><?php echo $this->escape($hotels_about_other); ?></p>
							
							<?php
							}
							?>
                       	</div>
              	</div>
            </div>		
                
            <div id="tabs-6">
            	<div class="products-details">
                	<div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('hotels_front_page_hotels_brochure'); ?></h4></div>
                    <div class="content">
                    	<h3><?php echo $this->hotelsForm->brochure_desc->getAttrib('font_end_label');  ?></h3>
                        <div class="details-info">
                           <h2><?php echo $this->escape($this->hotelsForm->brochure_title->getValue()); ?></h2>
                           <?php echo $this->escape($this->hotelsForm->brochure_desc->getValue()); ?>
                        </div>
                    </div>
				</div>
            </div>
                
            <div id="tabs-7">
            	<div class="products-details">
                	<div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('hotels_front_page_hotels_map'); ?></h4></div>
                    <div class="content">
                    	<h2><?php echo $this->hotelsForm->feature_google_map->getAttrib('font_end_label');  ?></h2>
                        <div class="products-map"><?php echo $this->escape($this->hotelsForm->feature_google_map->getValue()); ?></div>
                  	</div>
				</div>
            </div>
                
            <div id="tabs-8">
            	<div class="products-details">
                	<div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('hotels_front_page_hotels_financing'); ?></h4></div>
                    <div class="content">
                    	<h2><?php echo $this->hotelsForm->payment_desc->getAttrib('font_end_label'); ?></h2>
                        <?php echo $this->escape($this->hotelsForm->payment_desc->getValue()); ?>
                   	</div>
              	</div>
            </div>
                
            <div id="tabs-9">
                <div class="products-details">
                    <div class="products-details-header"><h4 class="icon"><?php echo $this->translator->translator('hotels_front_page_hotels_policy'); ?></h4></div>
                    <div class="content">
                    	<?php
							if($this->hotelsForm->hotels_policy_policies->getValue())
							{
						?>
						<h4><?php echo $this->hotelsForm->hotels_policy_policies->getAttrib('font_end_label'); ?></h4>
						<p><?php echo $this->escape($this->hotelsForm->hotels_policy_policies->getValue()); ?></p>
						<hr />
						
						<?php
							}
							if($this->hotelsForm->hotels_policy_terms_condition->getValue())
							{
						?>
						<h4><?php echo $this->hotelsForm->hotels_policy_terms_condition->getAttrib('font_end_label'); ?></h4>
						<p><?php echo $this->escape($this->hotelsForm->hotels_policy_terms_condition->getValue()); ?></p>
						<hr />
						
						<?php
							}
							if($this->hotelsForm->hotels_policy_privacy->getValue())
							{
						?>
						
						<h4><?php echo $this->hotelsForm->hotels_policy_privacy->getAttrib('font_end_label');?></h4>
						<p><?php echo $this->escape($this->hotelsForm->hotels_policy_privacy->getValue()); ?></p>
						
						<?php
						}	
						?>	
                    </div>
                </div>
            </div>	
                
            <div id="tabs-10">
                 <div class="products-legend">      
                        <div class="legend-icon">
                            <img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/available.gif" />
                        </div>
                        <div class="legend-icon">
                            <img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/booked.gif"/>
                        </div>
                        <div class="legend-icon">
                            <img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/not-available.gif"/>
                        </div>
                        <div class="legend-icon">
                            <img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_img/blank.gif"/>
                        </div>
                 </div>
                
                
                 <div class="room-chart-container">
                        <div class="room-chart">
                            <!-- Header Start -->
                                <div class="room-chart-row">
                                    <div class="room-chart-header-col-1 details-header-col-1">
                                        <?php echo $this->translator->translator('hotels_front_page_list_head_room_type'); ?>
                                    </div>
                                    
                                    <div class="room-chart-header-col-1 room-chart-header-col-2">
                                        <?php echo $this->translator->translator('hotels_front_page_list_head_people_per_room'); ?>
                                    </div>
                                    
                                    <div class="room-chart-header-col-1 room-chart-header-col-3 details-header-col-3">
                                        <?php echo $this->translator->translator('hotels_front_page_list_head_price_per_room'); ?>
                                    </div>
                                    
                                    <div class="room-chart-header-col-1 room-chart-header-col-4 details-header-col-4">
                                        <?php echo $this->translator->translator('hotels_front_page_list_head_no_apartments'); ?>
                                    </div> 
                                </div>
                            <!-- Header End -->
                        </div>
                        
                        <?php									
                            $room_type_name_arr = array();	
                            $count = 0;									
                            foreach($room_type_id_arr as $key=>$value)
                            {										
                                $room_type_info = $this->room_type_db->getRoomTypeInfo($value);
                                $room_type_name_arr[$key] = $this->escape($room_type_info['room_type']);														
                                $row_class = ($key % 2 == 0) ? 'room-chart-row2' : 'room-chart-row2 room-chart-row3';	
                                $height_style =  '';																					
                        ?>
                        
                        <div class="room-chart chart-border">
                            <!-- Row-2 & Row-3 Start -->
                                <div class="<?php echo $row_class ?>" <?php echo $height_style; ?>>
                                        <div class="room-chart-c1 details-col-1">
                                            <a  class="preview chart-link" rel="<?php echo $this->escape($room_type_info['id']); ?>" link=""  title="<?php echo $this->escape($room_type_info['room_condition']); ?>"><?php echo $this->escape($room_type_info['room_type']); ?></a>
                                        </div>
                                        
                                        <div class="room-chart-c1 room-chart-c2" <?php echo $height_style; ?>>
                                            <a class="preview" link="" title="<?php echo $this->translator->translator('hotels_front_page_list_title_people',$this->escape($room_type_info['max_people'])); ?>">
                                            <?php 
                                                if($this->escape($room_type_info['max_people']) <= 4)
                                                {
                                                    for($i = 1; $i <= $this->escape($room_type_info['max_people']); $i++)
                                                    {
                                                        echo '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/people.png" border="0" />';
                                                    }
                                                } 
                                                else
                                                {
                                                    for($i = 1; $i <= 3; $i++)
                                                    {
                                                        echo '<img src="application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/people.png" border="0" />';
                                                    }
                                                    echo '<span class="person-count">'.$this->escape($room_type_info['max_people']).'</span>';
                                                }
                                            ?>
                                            </a>
                                        </div>
                                        
                                        <div class="room-chart-c1 room-chart-c3 details-col-3" <?php echo $height_style; ?>>
                                            <span class="hotel-old-price"><?php echo $this->currency->getShortName().'&nbsp;'.$this->escape($room_type_info['basic_price']); ?></span>
                                            <span class="hotel-price"><?php echo $this->currency->getShortName().'&nbsp;'.$this->price($this->escape($room_type_info['descount_price'])); ?></span>
                                        </div>
                                        
                                        <div class="room-chart-c1 room-chart-c4 details-col-4" <?php echo $height_style; ?> title="<?php echo $this->escape($room_type_info['room_type']); ?>">
                                            <?php																
                                                if(!empty($this->post_search_info) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_IN]) && !empty($this->post_search_info[Eicra_File_Constants::HOTELS_CHECK_OUT]))
                                                {
                                                    $room_info = $room_db->getAvailableRooms($room_type_info['id'], $this->post_search_info);								
                                                }
                                                else
                                                {
                                                    $room_info = $room_db->getAvailableRooms($room_type_info['id'], array(Eicra_File_Constants::HOTELS_CHECK_IN => date("Y-m-d"), Eicra_File_Constants::HOTELS_CHECK_OUT => date("Y-m-d")));
                                                }
                                            ?>
                                                <select name="dialog_calendar_select<?php echo $count; ?>" id="dialog_calendar_select<?php echo $count; ?>" class="dialog_calendar_select room-list">
                                                    <option value="0"><?php echo $this->translator->translator('hotels_front_page_details_select_view_calendar'); ?></option>
                                                    <?php
                                                    if($room_info)
                                                    {
                                                        foreach($room_info as $room_info_key => $room_info_arr )
                                                        {
                                                            $price_sum = $this->price($this->escape($room_type_info['descount_price']));
                                                            echo '<option value="'.$room_info_arr['room_id'].'">'.$this->escape($room_info_arr['room_name']).' ('.$this->currency->getShortName().'&nbsp;'.$price_sum.') '.$this->translator->translator('hotels_front_page_list_head_no_apartments_per_night').'</option>';
                                                        }
                                                    }
                                                    ?>
                                                </select><br />
                                                <?php 
                                                    $total_room_number = $room_db->getTotalRooms($room_type_info['id']);
                                                    if((count($room_info) == $total_room_number) && $total_room_number != '0')
                                                    {
                                                        echo $this->translator->translator('hotels_front_page_list_available_type_yes');
                                                    }
                                                    else if(count($room_info) == '0' || $total_room_number == '0')
                                                    {
                                                        echo $this->translator->translator('hotels_front_page_list_available_type_no');
                                                    }
                                                    else if(count($room_info) == '1')
                                                    {
                                                        echo '<a class="preview" link="" title="'.$this->translator->translator('hotels_front_page_list_available_type_last_desc', $this->currency->getShortName().'&nbsp;'.$this->price($this->escape($room_type_info['descount_price']))).'">'.$this->translator->translator('hotels_front_page_list_available_type_llast', count($room_info)).'</a>';
                                                    }
                                                    else if(count($room_info) > '1' && count($room_info) <= $total_room_number)
                                                    {
                                                        echo $this->translator->translator('hotels_front_page_list_available_type_left', count($room_info));
                                                    }
                                            ?>
                                        </div>                                                                       
                                </div>
                            <!-- Row-2 & Row-3 End -->
                        </div>
                        <?php														
                            $count++;
                            }
                        ?>	
                </div>
                
                <div class="clear">&nbsp;</div>
                <h2 id="dialog_calendar_title"></h2>
                <div id="dialog_calendar" class="dialog_calendar"></div>   
                                      
            </div>
            <?php
                if(!empty($this->group_datas['review_id']))
                {
            ?>

            <div id="tabs-11">
                    <?php 
                    if(!empty($this->review_datas['review_info']))
                    {							
                        foreach($this->review_datas['review_info'] as $key => $infos)
                        {		
                            $div_class = ($key % 2 == 0) ? 'review-box' : 'review-box2';						
                    ?> 
                    <div class="<?php echo $div_class; ?>">
                        <div class="review-box-img">
                            <?php										
                                $primary_image_field = (!empty($this->review_datas['review_settings_info']['primary_image_field'])) ? $this->review_datas['review_settings_info']['primary_image_field'] : '';
                                $primary_images = (!empty($primary_image_field) && !empty($infos[$primary_image_field])) ? $infos[$primary_image_field] : '' ;
                                if(empty($primary_images))
                                {
                                    $img_path = 'application/layouts/scripts/'.$front_template['theme_folder'].'/images/mod_hotel_img/avatar.png';
                                }
                                else
                                {
                                    $files_arr = explode(',',$primary_images);
                                    $img_path = $this->escape($this->review_datas['form_info']['attach_file_path']).'/'.$this->escape($files_arr[0]);
                                }
                            ?>
                            <img src= "<?php echo $img_path ?>" width="80" />
                        
                        </div>
                        
                        <div>
                            <div class="review-box-title">
                                        <span>
                                        <?php 
                                            if(!empty($this->review_datas['review_settings_info']['name_title_field']))
                                            { 
                                                $name_title_field  = $this->review_datas['review_settings_info']['name_title_field'];
                                                if(!empty($infos[$name_title_field]))
                                                {
                                                    echo $this->escape($infos[$name_title_field]); 
                                                }
                                            } 
                                        ?>
                                        </span>
                                        
                                        <div>
                                        
                                            <?php 
                                                if(!empty($this->review_datas['review_settings_info']['rating_fields']))
                                                { 												
                                                    $rating_fields_arr  = explode(',',$this->review_datas['review_settings_info']['rating_fields']);
                                                    if(!empty($infos[$rating_fields_arr[0]]))
                                                    {	
                                                        $cnt = $this->escape($infos[$rating_fields_arr[0]]) - 1;                                                    											
                                                        
                                            ?>                                        
                                            <div class="review-box-rate"><?php echo str_replace("'",'',$hint_arr[$cnt]); ?></div>
                                            <div class="review-box-star">
                                                        <div id="<?php echo $this->escape($rating_fields_arr[0]).$infos['id']; ?>_star"  class="review-box-rate-star"></div>
                                                        <script type="text/javascript">
                                                            $(function() {
                                                                raty ('<?php echo $this->escape($rating_fields_arr[0]).$infos["id"]; ?>','<?php echo $this->escape($infos[$rating_fields_arr[0]]); ?>');
                                                            });
                                                        </script>
                                            </div>
                                           
                                            <?php 
                                                    }
                                                } 
                                            ?>
                                        </div>
                                        
                                        
                                    </div>
                                    <div class="review-box-desc">
                                        <?php 
                                            if(!empty($this->review_datas['review_settings_info']['short_desc_field']))
                                            { 
                                                $short_desc_field  = $this->review_datas['review_settings_info']['short_desc_field'];
                                                if(!empty($infos[$short_desc_field]))
                                                {
                                                    echo '"'.$this->escape($infos[$short_desc_field]).'"'; 
                                                }
                                            } 
                                        ?>
                                        
                                            <div class="review-box-date">
                                                <?php 											
                                                    if(!empty($infos['g_date']))
                                                    {
                                                        echo $this->escape($infos['g_date']); 
                                                    }											
                                                ?>
                                            </div>
                                    </div>
                            </div>
                        </div>
                        <?php 								
                            }							
                        }
                        ?>
            </div>
                <?php
                    }
                    if(!empty($staticGroupsObj))
                    {
                        $tab = (!empty($this->group_datas['review_id'])) ? 12 : 11;
                        foreach($staticGroupsObj as $staticGroup)
                        {
                            $elementsObj = $staticGroup->getElements();
                    ?>
                    <div id="tabs-<?php echo $tab; ?>">
                        
                        <?php																
                            foreach($elementsObj as $element)
                            {
                                if($element->getAttrib('frontend') == '1')
                                {	
                                    if($element->getType() != 'Zend_Form_Element_File')
                                    {	
                                        $element_value = $element->getValue();											
                                        if((is_array($element_value) && !empty($element_value[0])) || (!is_array($element_value) && !empty($element_value)) )
                                        {														
                                        ?>	
                                    
                                        <div class="tab-element">
                                            <?php echo $element->getLabel();  ?>
                                        </div>
                                        
                                        <div class="tab-element-value">
                                            <?php 										
                                                $id_f = $element->getAttrib('id');
                                                $id_arr = explode('_',$id_f);	
                                                if(($element->getType() == 'Zend_Form_Element_MultiCheckbox') || ($element->getType() == 'Zend_Form_Element_Multiselect'))
                                                {	
                                                    $val_arr = $element_value;														
                                                    echo implode(', ',$val_arr);
                                                }
                                                else
                                                {													
                                                    echo $this->escape($element_value);	
                                                }														
                                            ?>		
                                        </div>
                                        <?php
                                        }
                                    }
                                    else
                                    {										
                                        $element_name = $element->getName();										
                                        $element_value = $this->view_datas[$element_name];																				
                                        if((is_array($element_value) && !empty($element_value[0])) || (!is_array($element_value) && !empty($element_value)) )
                                        {
                                            ?>	
                                    
                                            <div class="tab-element">
                                                <?php echo $element->getLabel();  ?>
                                            </div>
                                            
                                            <div class="tab-element-value">
                                            <?php									
                                                                                                                        
                                                echo '<a href="#">'.$this->escape($element_value).'</a>';																										
                                            ?>		
                                        </div>
                                         <?php
                                        }
                                    }
                                }
                            }
                        ?>		
                    
                    </div>
                    <?php
                            $tab++;
                         }
                     }
                    ?>
    </div>
    
    <!-- Hotel Bottom Tab End -->


    <!-- Bottom Bar Start -->
    <div class="nav-bar bottom">
        <div class="nav-row">
            <div class="nav-col first"> 
            <?php
                if(!empty($prevHotels))
                {
            ?>
            <span class="prev"><a href="<?php echo 'Hotels-details/'.$this->escape($prevHotels['hotels_title']); ?>"><?php echo $this->translator->translator('hotels_front_page_prev_hotels'); ?></a></span>
            <?php
                }
                else
                {
            ?>
            <span class="no-link"><?php echo $this->translator->translator('hotels_front_page_prev_hotels'); ?></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col"><span class="search"><a href="Search-Hotels"><?php echo $this->translator->translator('hotels_front_page_new_search'); ?></a></span></div>
            <div class="nav-col">
            <?php
                if(!empty($nextHotels))
                {
            ?>
            <span class="save"><a  href="javascript:void(0);" class="save_hotels_btn" rel="<?php echo $this->escape($this->view_datas['id']); ?>"><?php echo $this->translator->translator('hotels_front_page_save_hotels'); ?></a></span>
            <?php
                }
            ?>
            </div>
            <div class="nav-col last">
            <?php
                if(!empty($nextProperty))
                {
            ?>
            <span class="next"><a href="<?php echo 'Hotels-details/'.$this->escape($nextHotels['hotels_title']); ?>"><?php echo $this->translator->translator('hotels_front_page_next_hotels'); ?></a></span>
            <?php
                }
                else
                {
            ?>
            <span class="no-link"><?php echo $this->translator->translator('hotels_front_page_next_hotels'); ?></span>
            <?php
                }
            ?>
            </div>
        </div>
    </div>    
	<!-- Bottom Bar End -->
</div>
<div id="dialog_container" title="<?php echo $this->translator->translator('common_dialog_msg','Message'); ?>"></div>
<?php else : ?>
	<h2><?php echo $this->translator->translator('common_not_approved'); ?></h2>
<?php endif; ?>	
<?php endif; ?>	