<?php
$this->headMeta()->setName('keywords', $this->translator->translator('hotels_frontend_last_deal_header_title'));
$this->headMeta()->setName('description', $this->translator->translator('hotels_frontend_last_deal_header_title')); 
$this->headTitle()->headTitle($this->translator->translator('hotels_frontend_last_deal_header_title') ,'SET');

$locale_direction = Eicra_Global_Variable::getSession()->site_direction;
$locale = Eicra_Global_Variable::getSession()->sess_lang;

echo $this->headScript()->setFile($this->baseUrl().'/vendor/scripts/jtruncate/jquery.jtruncate.pack.js');

$front_template = Zend_Registry::get('front_template');

// 1ist param options are : like, inline, plus_minus, horizontal, triangle
$vote = new Vote_Controller_Helper_ShowVoteButton('inline','hotels_page' );

$global_conf = Zend_Registry::get('global_conf');

 ?>
	
	<script type="text/javascript">
    $(document).ready(function() {
        var settingObj = {
                            grid_id : 'grid',
                            dest_url : "<?php echo $this->url(); ?>",
                            pageSize : '<?php echo Eicra_Global_Variable::getSession()->viewPageNum; ?>',
                            page: '<?php echo ($this->posted_data['page']) ? $this->posted_data['page'] : ''; ?>',	
                            calendar: {
                                culture: "<?php echo str_ireplace('_', '-', $locale); ?>",
                                value: ''
                            },
                            search_action: {},
                            common_action : {
                                    permission_arr : {},
                                    toolbar_button_loader		:	'<span class="icon loader"></span>',
                                    ajax_loader_link			:	"application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif",
                            
                                    multi_action	: []
                            },
                            search_data : {},
                            batch:		false,
                            editable:	false,
                            scrollable: false,
                            detailInit:	false,
                            dataBound: function(e) {									
                                    var self = this;
                                    self.element.css("border", "none");
                                    self.element.height("").find(".k-grid-pager").css("border-width", "1px 1px 1px 1px");
                                    self.thead.remove();
                                    text_truncate();
                                    commonVoting();													                      
                            },
                            filterable: false,
                            rowTemplate: kendo.template($("#view_template").html()),
                            model: {},					
                            column_fields: [],
                            columnMenu:	false,
                            messages: {
                                            display				: 	'<?php echo $this->translator->translator("portfolio_pagination_messages_display", '', 'Portfolio'); ?>',
                                            empty				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_empty", '', 'Portfolio'); ?>',
                                            page				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_page", '', 'Portfolio'); ?>',
                                            of					:	'<?php echo $this->translator->translator("portfolio_pagination_messages_of", '', 'Portfolio'); ?>',
                                            itemsPerPage		:	'<?php echo $this->translator->translator("portfolio_pagination_messages_items_per_page", '', 'Portfolio'); ?>',
                                            first				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_first", '', 'Portfolio'); ?>',
                                            previous			:	'<?php echo $this->translator->translator("portfolio_pagination_messages_previous", '', 'Portfolio'); ?>',
                                            next				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_next", '', 'Portfolio'); ?>',
                                            last				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_last", '', 'Portfolio'); ?>',
                                            refresh				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_refresh", '', 'Portfolio'); ?>',
                                            
                                            common_msg_dialog_id 		:	'dialog_msg',
                                            common_confirn_dialog_id	:	'dialog-confirm',
                                            common_ok					:	"<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>",
                                            common_delete_title			:	"<?php echo html_entity_decode($this->translator->translator('common_delete_title'), ENT_QUOTES, 'UTF-8'); ?>",
                                            common_delete_selected		:	"<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, 'UTF-8'); ?>",
                                            common_cancel				:	"<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, 'UTF-8'); ?>",
                                            common_delete_confirm		:	"<?php echo $this->translator->translator("hotels_list_delete_confirm"); ?>",
                                            common_publish_title		:	"<?php echo $this->translator->translator("common_publish_title"); ?>",
                                            common_unpublish_title		:	"<?php echo $this->translator->translator("common_unpublish_title"); ?>",										
                                            common_publish_selected		:	"<?php echo $this->translator->translator("common_publish_selected"); ?>",
                                            common_unpublish_selected	:	"<?php echo $this->translator->translator("common_unpublish_selected"); ?>",
                                            common_publish_perm	 		:	"<?php echo $this->translator->translator("common_publish_perm"); ?>",
                                            common_perm_err				:	"<?php echo $this->translator->translator("common_perm_err"); ?>",
                                            common_selected_err	 		:	"<?php echo $this->translator->translator("hotels_selected_err"); ?>"
                                        }
                        };
        commonGrid(settingObj);
    });
    function text_truncate()
    {
        $('div.jTruncate').jTruncate({  
            length:  300,  
            minTrail: 0,  
            moreText: "[<?php echo html_entity_decode($this->translator->translator('common_see_all'), ENT_QUOTES, "UTF-8"); ?>]",  
            lessText: "[<?php echo html_entity_decode($this->translator->translator('common_hide'), ENT_QUOTES, "UTF-8"); ?>]",  
            ellipsisText: "",  
            moreAni: "fast",  
            lessAni: 2000  
        });
    }
    </script>
    <script type="text/x-kendo-template" id="view_template">
            <div class="products-list">
                <!-- List Header Start -->
                <div class="list-header">
                    <div class="header-row">
                        <div class="header-left">
                            <span class="title-small">#= hotels_name_format #</span><br />
                            <span class="info"># if(feature_distance_from_airport){ # #= feature_distance_from_airport # #= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_distance'), ENT_QUOTES, "UTF-8"); ?>' # #} #</span>  
                        </div>
                    
                        <div class="header-middle">
                            <span class="products-mark">#= hotels_status #</span>&nbsp;<span class="products-type">#= business_type #</span>
                        </div>
                    
                        <div class="header-right"> 
                            # if(review_id){ #                                         
                            <span class="products-write-review"><a href="<?php echo $this->url( array('module' => 'Review','controller' => 'frontend', 'action'     => 'write', Eicra_File_Constants::ITEM_ID => '', 'group_id' => '' ), 'Review-Write/:group_id/:item_id',    true); ?>/${id}/${review_id}">#= '<?php echo html_entity_decode($this->translator->translator('common_write_review'), ENT_QUOTES, "UTF-8"); ?>' #</a></span> &nbsp; 
                            <span class="products-review-count"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '','tab' => '' ),'Hotels-details/:hotels_title/:tab',true); ?>/${hotels_title}/10">#= review_no_format #</a></span>
                            # } #
                        </div>
                    </div>
                </div>
                <!-- List Header End -->
                
                 <!-- List Body Start -->
                  <div class="body-container #= (featured == '1') ? 'products-featured' : '' #">
                       <div class="left-content">
                              <div class="img-wrapper">
                                  <a href="<?php echo $this->url(array('module' => 'hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '' ),'Hotels-details/:hotels_title',true); ?>/${hotels_title}" class="preview" link="#= hotels_image_format #" title="#= hotels_name #"><img src="#= hotels_image_format #" border="0" #= thumb_width # #= thumb_height # class="thumb" /></a>
                                  <div class="photo-count-container">
                                      <div class="photo-count">
                                          <a href="<?php echo $this->url(array('module' => 'hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '','tab' => '' ),'Hotels-details/:hotels_title/:tab',true); ?>/${hotels_title}/1" title="#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_click_view_listing'), ENT_QUOTES, "UTF-8"); ?>' #">#= hotels_image_no_format #</a>
                                      </div>
                                  </div>                                            
                              </div>
                              
                              <h2>
                                  <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '' ),'Hotels-details/:hotels_title',true); ?>/${hotels_title}" class="preview" link="" title="#= hotels_name #">#= hotels_name_format #</a>
                              </h2>
                              
                              <div class="products-stars">
                                  #= hotel_stars_format #
                              </div>
                              
                              <div class="products-desc jTruncate">
                                  #= hotels_desc_format #
                              </div>
                              
                       </div>
                       
                       <div class="right-content">
                          <ul class="products-options">	
                              <li class="availability"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '','tab' => '' ),'Hotels-details/:hotels_title/:tab',true); ?>/${hotels_title}/9" title="Check Calendar for reservation">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_check_availability'), ENT_QUOTES, "UTF-8"); ?>' #</a></li>
                              #
                                  var feature_facilities_arr = (feature_facilities) ? feature_facilities.split(',') : [];															
                                  if($.inArray('airport transfer', feature_facilities_arr) != -1)
                                  {
                              #						  
                              <li class="airport-transfer">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_airport_transfer'), ENT_QUOTES, "UTF-8"); ?>' #</li>						  
                              #
                                  }
                                  var feature_sports_recreations_arr = (feature_sports_recreations) ? feature_sports_recreations.split(',') : [];															
                                  if($.inArray('indoor pool', feature_sports_recreations_arr) != -1)
                                  {
                              #		
                              <li class="swimming">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_swwimming_pool_availability'), ENT_QUOTES, "UTF-8"); ?>' #</li>
                              #
                                  }
                                  if(feature_pet == 'Pets are allowed')
                                  {
                              #
                              <li class="pet">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_pet_allow'), ENT_QUOTES, "UTF-8"); ?>' #</li>
                              #
                                  }															
                                  if($.inArray('Internet Available', feature_facilities_arr) != -1)
                                  {
                              #
                              <li class="internet" title="#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_internet_availability'), ENT_QUOTES, "UTF-8"); ?>' #">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_internet_availability'), ENT_QUOTES, "UTF-8"); ?>' #</li>
                              #
                                  }
                                 if(hotels_phone){ 
                              #
                              <div>
                                  <span class="products-call"># if(hotels_phone){ #<span>#= hotels_phone #</span># } #</span>
                              </div>
                              # } #
                          </ul>
                          
                          <div class="products-vote">
                              <p>#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_label_voting'), ENT_QUOTES, "UTF-8"); ?>' #</p>
                              <span>#= vote_format #</span>
                          </div>
                       </div>
                       
                       <!--  Availability Chart Start-->
                       <div class="room-chart-container">
                       <div class="room-chart">
                          # if(room_type_id && room_type_info){  #
                          <!-- Header Start -->
                          <div class="room-chart-row">
                              <div class="room-chart-header-col-1">
                                  #= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_list_head_room_type'), ENT_QUOTES, "UTF-8"); ?>' #
                              </div>
                              
                              <div class="room-chart-header-col-1 room-chart-header-col-2">
                                  #= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_list_head_people_per_room'), ENT_QUOTES, "UTF-8"); ?>' #
                              </div>
                              
                              <div class="room-chart-header-col-1 room-chart-header-col-3">
                                  #= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_list_head_available_room'), ENT_QUOTES, "UTF-8"); ?>' #
                              </div>
                              
                              <div class="room-chart-header-col-1 room-chart-header-col-4">
                                  #= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_list_head_price_per_room'), ENT_QUOTES, "UTF-8"); ?>' #
                              </div> 
                          </div>
                          <!-- Header End -->
                              # if(room_type_info){  $.each(room_type_info, function(room_type_key, room_type_arr){ #
                                  <!-- Row-2 & Row-3 Start -->
                                  <div class="#= ( room_type_key % 2 == 0) ? 'room-chart-row2' :  'room-chart-row2 room-chart-row3' #">
                                    <div class="room-chart-c1">
                                         <a class="preview" link="" title="#= room_type_arr.room_condition #">#= room_type_arr.room_type #</a> # if(room_type_arr.save_price > 0){ # #= room_type_arr.save_format # # } # # if(room_type_arr.just_booked){ # <?php echo html_entity_decode($this->translator->translator('hotels_front_page_list_booked_today'), ENT_QUOTES, "UTF-8"); ?> # } #
                                      </div>
                                      
                                       <div class="room-chart-c1 room-chart-c2">
                                          <a class="preview" link="" title="#= room_type_arr.max_people_lang_format #">
                                          # 
                                              if(room_type_arr.max_people <= 4)
                                              {
                                                  for(var i = 1; i <= room_type_arr.max_people; i++)
                                                  {
                                            #<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_hotel_img/people.png" border="0" />#
                                                  }
                                              } 
                                              else
                                              {
                                                  for($i = 1; $i <= 3; $i++)
                                                  {
                                                      #<img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/mod_hotel_img/people.png" border="0" />#
                                                  }
                                              }
                                          #<span class="person-count">#= room_type_arr.max_people_format #</span>
                                          </a>
                                      </div>
                                      
                                      <div class="room-chart-c1 room-chart-c3">
                                          #
										  if(room_type_arr.room_info)
										  {
                                            if((room_type_arr.room_info.length == room_type_arr.room_num) && room_type_arr.room_num != 0)
                                            {
                                          #	 
                                                <?php echo html_entity_decode($this->translator->translator('hotels_front_page_list_available_type_yes'), ENT_QUOTES, "UTF-8"); ?>
                                          #
                                            }
                                            else if(room_type_arr.room_info.length == 0 || room_type_arr.room_num == 0)
                                            {
                                          #	 
                                                <?php echo html_entity_decode($this->translator->translator('hotels_front_page_list_available_type_no'), ENT_QUOTES, "UTF-8"); ?>
                                          #
                                            }
                                            else if(room_type_arr.room_info.length == 1)
                                            {
                                          #	 
                                              <a class="preview" link="" title="#= room_type_arr.room_info_count_format2 #">#= room_type_arr.room_info_count_format #</a>
                                          # 
                                            }
                                            else if(room_type_arr.room_info.length > 1 && room_type_arr.room_info.length <= room_type_arr.room_num)
                                            {
                                          # 
                                                #= room_type_arr.room_info_count_format1 #
                                          #
                                            }
										  }
										  else
										  {
										  #
											<?php echo html_entity_decode($this->translator->translator('hotels_front_page_list_available_type_no'), ENT_QUOTES, "UTF-8"); ?>
										  #
										  }
										  #
                                      </div>
                                      
                                      <div class="room-chart-c1 room-chart-c4">
                                          <span class="hotel-old-price"><?php echo $this->currency->getShortName().'&nbsp;'; ?>#= room_type_arr.basic_price_format #</span>&nbsp;
                                          <span class="hotel-price"><?php echo $this->currency->getShortName().'&nbsp;'; ?>#= room_type_arr.descount_price_format #</span>
                                      </div>						  
                                  
                                  </div>
                                 <!-- Row-2 & Row-3 End -->
                              # }); } #						  
                        # } #						
                       </div>
                       
                       </div>
                       <!--  Availability Chart End-->
                       
              </div>
              <!-- List Body End -->
            
            <!-- List footer start -->
                <div class="list-footer">
                    <div class="footer-left">
                        <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '','tab' => '' ),'Hotels-details/:hotels_title/:tab',true); ?>/#= hotels_title #/0">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_summary_booking'), ENT_QUOTES, "UTF-8"); ?>' #</a> | 
                        <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '','tab' => '' ),'Hotels-details/:hotels_title/:tab',true); ?>/#= hotels_title #/1">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_photo'), ENT_QUOTES, "UTF-8"); ?>' #</a> |
                        <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '','tab' => '' ),'Hotels-details/:hotels_title/:tab',true); ?>/#= hotels_title #/6">#= '<?php echo html_entity_decode(ucfirst(strtolower($this->translator->translator('hotels_front_page_hotels_map'))), ENT_QUOTES, "UTF-8"); ?>' #</a>  | 											 
                        <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '','tab' => '' ),'Hotels-details/:hotels_title/:tab',true); ?>/#= hotels_title #/3">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_facilities_eatures'), ENT_QUOTES, "UTF-8"); ?>' #</a>  |
                        <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '','tab' => '' ),'Hotels-details/:hotels_title/:tab',true); ?>/#= hotels_title #/8">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_policies'), ENT_QUOTES, "UTF-8"); ?>' #</a>  |
                        <a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '','tab' => '' ),'Hotels-details/:hotels_title/:tab',true); ?>/#= hotels_title #/4">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_profile'), ENT_QUOTES, "UTF-8"); ?>' #</a>
                    </div>
                
                    <div class="footer-right">
                        <?php if($global_conf['payment_system'] == 'On') : ?><span class="products-book-btn"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'book', 'action' => 'booking','hotels_title' => '' ),'Book-Hotel/:hotels_title',true) ?>/#= hotels_title #">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_show_price'), ENT_QUOTES, "UTF-8"); ?>' #</a></span><?php endif; ?>
                        
                        <span class="products-details-btn"><a href="<?php echo $this->url(array('module' => 'Hotels','controller' =>'frontend', 'action' => 'details','hotels_title' => '' ),'Hotels-details/:hotels_title',true); ?>/#= hotels_title #">#= '<?php echo html_entity_decode($this->translator->translator('hotels_front_page_hotels_more'), ENT_QUOTES, "UTF-8"); ?>' #</a></span>
                    </div>                                
                </div>
            <!-- List footer end -->
            </div>	
    </script>
    <div class="mod">
        <div class="list-icon">
            <h1><?php echo $this->translator->translator('hotels_frontend_last_deal_header_title'); ?></h1>
        </div>   
        
        <div class="social">
            <!-- AddThis Button BEGIN -->
            <div class="addthis_toolbox addthis_default_style">
            <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
            <a class="addthis_button_tweet"></a>
            <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
            <a class="addthis_counter addthis_pill_style"></a>
            </div>
            <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4e89660c7edb029a"></script>
            <!-- AddThis Button END -->
        </div>
        <div class="clear"></div>
        
        <div <?php if($locale_direction == 'rtl'){ ?> class="k-rtl" <?php } ?>>
                   <div id="grid"></div>  
         </div>
        
    </div>	

