<?php 
$front_template = Zend_Registry::get('front_template'); 
$this->translator = Zend_Registry::get('translator');
$global_conf = Zend_Registry::get('global_conf');
?>

<div id="middle-bar">
    <div class="container">
        <div class="bookmark">
            <a href="<?php echo $this->url(); ?>" class="jQueryBookmark" title="<?php echo strip_tags($this->headTitle()); ?>">
                <div class="icon"><span></span></div><div class="text-wrap"><?php echo $this->translator->translator('front_bookmark_btn','', '', $front_template['theme_folder']); ?></div>
            </a>
        </div>
        <?php echo $this->partial('blocks/breadcrumb.phtml'); ?>
        <?php echo $this->partial('blocks/search_mini.phtml'); ?>
    </div>
</div>