<div id="container">
<?php if (!$this->allow()) : ?>
	<div class="grid_12 t_a_bottom">
		<?php echo $this->translator->translator('Member_Access_deny_desc'); ?>
	</div>
<?php else : 
echo $this->headScript()->setFile($this->baseUrl().'/js/jquery/jquery.scrollTo.js');

$this->proForm->setEditor($this->serverUrl().$this->baseUrl());
$this->proForm->getEditor();

$tab_base_link = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();

$locale_direction = Eicra_Global_Variable::getSession()->site_direction;
$locale = Eicra_Global_Variable::getSession()->sess_lang;

$global_conf = Zend_Registry::get('global_conf');
$currency = new Zend_Currency($global_conf['default_locale']);

$frontController = Zend_Controller_Front::getInstance();
$param_group_id = $frontController->getRequest()->getParam('group_id');

$original_tab_counter = 6;
?>

<script type="text/javascript">
var settingObj = {
					tab_base_link: '<?php echo $tab_base_link; ?>',
					form_action : {
										form_id: 'formItem',
										hasTinyMCE: true,											
										currency_symbol:	"<?php echo $currency->getSymbol(); ?>",
										common_msg_field_id: 'actionMessage',
										dialog_container_id:	'dialog_container',
										dialog_progressbar_id:	'progressbar',
										field_toggle_action: [
											{
												from_field_tag	: 'input',
												from_field_id 	: 'billing_user_places_order_email_enable',
												to_field_id 	: 'billing_user_places_order_email_address',
												active_value	: 'yes',												
											},
											{
												from_field_tag	: 'input',
												from_field_id 	: 'billing_user_pay_invoice_email_enable',
												to_field_id 	: 'billing_user_pay_invoice_email_address',
												active_value	: 'yes',												
											},
											{
												from_field_tag	: 'input',
												from_field_id 	: 'billing_user_cancel_order_email_enable',
												to_field_id 	: 'billing_user_cancel_order_email_address',
												active_value	: 'yes',												
											}
										],										
										extra_field_for_reset: [
											{field_id : 'categoryTree', field_value: '' , field_type : 'html'},
											{field_id : 'selected_file_hotels_image', field_value: '' , field_type : 'html'},
											{field_id : 'selected_file_feature_interior_plan_image', field_value: '' , field_type : 'html'},
											{field_id : 'hotels_parent', field_value: '0' , field_type : 'val'},
											{field_id : 'hotels_image', field_value: '' , field_type : 'val'},
											{field_id : 'feature_interior_plan_image', field_value: '' , field_type : 'val'},
											{field_id : 'dataId', field_value: '<?php echo $this->translator->translator("hotels_tree_root"); ?> (0)' , field_type : 'html'}
										],
										extra_function_for_reset: function(){
											if(tinyMCE.get('hotels_desc'))
											{
												tinyMCE.get('hotels_desc').setContent('');
											}
											if(tinyMCE.get('hotels_address'))
											{
												tinyMCE.get('hotels_address').setContent('');
											}
											if(tinyMCE.get('feature_google_map'))
											{
												tinyMCE.get('feature_google_map').setContent('');
											}
											if(tinyMCE.get('feature_additional'))
											{
												tinyMCE.get('feature_additional').setContent('');
											}
											if(tinyMCE.get('brochure_desc'))
											{
												tinyMCE.get('brochure_desc').setContent('');
											}
											if(tinyMCE.get('payment_desc'))
											{
												tinyMCE.get('payment_desc').setContent('');
											}
											$('#billing_user_places_order_email_address').removeAttr('disabled');	
											$('#billing_user_pay_invoice_email_address').removeAttr('disabled');
											$('#billing_user_cancel_order_email_address').removeAttr('disabled');										
											$('a.back_btn_link').attr('href','<?php echo $this->url( array("module" => "Hotels","controller" => "backendpro", "action"  => "list" ,"group_id" => $param_group_id), "adminrout",    true) ?>');
											commonRemoveTabs(settingObj);
										},
										category_tree:{
											category_tree_id: 'categoryTree',
											category_tree_input_field_id : 'hotels_parent',
											category_tree_input_html_id : 'dataId',
											category_tree_dest_url: "<?php echo $this->url( array('module' => 'Hotels','controller' => 'backend', 'action'     => 'parent' ), 'adminrout',    true) ?>",
											tree_view: {
												dragAndDrop : true,
												template: "<label><input type=\"radio\" name=\"radio\" />#= item.text #</label>",
												dataBound	: function(obj){
																													
															var treeView = $("#"+settingObj.form_action.category_tree.category_tree_id).data('kendoTreeView');
															var getitem = treeView.dataSource.get("<?php echo (!empty($this->category_info['id'])) ? $this->category_info['id'] : '0'; ?>");
															if(getitem)
															{
																var selectitem = treeView.findByUid(getitem.uid);
																treeView.select(selectitem);
															}
												},
												dataSource :  {
													transport: {
															read: {
																url: "<?php echo $this->url( array('module' => 'Hotels','controller' => 'backendpro', 'action'     => 'hotelsgroup' ), 'adminrout',    true) ?>",
																dataType: "json",
																type: "POST",
																data : {expanded : true}, // true is enable null is disable
																complete: function(e) {																		
																	var json_arr = $.parseJSON(e.responseText);	
																	if(json_arr.status == 'ok')
																	{	
																		$.each(json_arr.TreeDataSource, function(key, arr_obj){
																			if(arr_obj['id'] == '0')
																			{																		
																				commonDynamicFieldGenrator(json_arr.dynamic_field_arr, settingObj);
																				<?php if($this->auth->getIdentity()->access_file_image_manager != '1'){ ?>
																					uploadSettingsStart(json_arr);
																				<?php } ?>	
																				var business_type = json_arr.businessType_options;
																				var option = '<option value=""><?php echo $this->translator->translator("hotels_select_businessType"); ?></option>';
																				if(business_type)
																				{							
																					$.each(business_type, function(key, arr){ option += '<option value="'+arr.id+'">'+commonStripslashes(arr.business_type)+'</option>'; });						
																				}
																				$('#hotels_type').html(option);
																			}
																		});																			
																	}
																	else
																	{
																	   commonMsgDialog(settingObj, json.msg);
																	   <?php if($this->auth->getIdentity()->access_file_image_manager != '1'){ ?>
																			uploadSettingsEnd();			
																		<?php } ?>															
																	}
																}
															}
														},
														schema: {
															data: 'TreeDataSource',
															model: {
																id : 'id',
																text : 'text' ,
																hasChildren: 'hasChildren'  
															}
														}	
												}
											}
										},
										dynamic_field_generator: {
											has_tab	: true,
											tab_id	: 'tabs',
											html_input_id: 'dynamic_fields',												
											uploader_upload_url: '<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'upload'), 'adminrout',    true) ?>',
											uploader_remove_url: '<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove'), 'adminrout',    true) ?>',
											constants: {
													DYNAMIC_FIELD_GROUP_TITLE 		: 	'<?php echo Eicra_File_Constants::DYNAMIC_FIELD_GROUP_TITLE; ?>',
													DYNAMIC_FIELD_GROUP_ELEMENTS	:	'<?php echo Eicra_File_Constants::DYNAMIC_FIELD_GROUP_ELEMENTS; ?>',
													DATE							:	'<?php echo Eicra_File_Constants::DATE; ?>',
													PRICE							:	'<?php echo Eicra_File_Constants::PRICE; ?>'
											},
											langueges:{
												common_go_top_title: "<?php echo html_entity_decode($this->translator->translator('common_go_top_title'), ENT_QUOTES, 'UTF-8'); ?>",
											},
											after_add_function : function(){
												//qToolTipFunctions();
											}
										}
								},
					dynamic_list_action: [
																{
																	list_id:'country_id',
																	sub_list: {
																		list_id:'state_id',
																		list_dest_url: '<?php echo $this->url( array('module' =>'Hotels','controller' => 'backendpro', 'action' => 'states' ), 'adminrout',    true) ?>',
																		list_any_value: '<?php echo html_entity_decode($this->translator->translator("hotels_select_state"), ENT_QUOTES, 'UTF-8'); ?>',
																		list_input_value_field: 'state_id',
																		list_input_option_field: 'state_name',
																		list_return_field: 'states',
																		list_loader_info : {
																					loader_id : 'state_id_loader',
																					loader_img : 'application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif',
																					on_loading : [
																									{id : 'state_id', type:'html', loading_lang: '<?php echo html_entity_decode($this->translator->translator("common_loading_language"), ENT_QUOTES, 'UTF-8'); ?>', normal_lang: '<?php echo html_entity_decode($this->translator->translator("hotels_select_state"), ENT_QUOTES, 'UTF-8'); ?>'},
																									{id : 'area_id', type:'html', loading_lang: '<?php echo html_entity_decode($this->translator->translator("hotels_select_area"), ENT_QUOTES, 'UTF-8'); ?>', normal_lang: '<?php echo html_entity_decode($this->translator->translator("hotels_select_area"), ENT_QUOTES, 'UTF-8'); ?>'}
																								]
																			},
																		sub_list:{
																			list_id:'area_id',
																			list_dest_url: '<?php echo $this->url( array('module' =>'Hotels','controller' => 'backendpro', 'action' => 'areas' ), 'adminrout',    true) ?>',
																			list_any_value: '<?php echo html_entity_decode($this->translator->translator("hotels_select_area"), ENT_QUOTES, 'UTF-8'); ?>',
																			list_input_value_field: 'city_id',
																			list_input_option_field: 'city',
																			list_return_field: 'cities',
																			list_loader_info : {
																						loader_id : 'area_id_loader',
																						loader_img : 'application/modules/Administrator/layouts/scripts/images/loader/ajax_loader.gif',
																						on_loading : [
																										{id : 'area_id', type:'html', loading_lang: '<?php echo html_entity_decode($this->translator->translator("common_loading_language"), ENT_QUOTES, 'UTF-8'); ?>', normal_lang: '<?php echo html_entity_decode($this->translator->translator("hotels_select_area"), ENT_QUOTES, 'UTF-8'); ?>'}
																									]
																				}
																		}
																	}
																}
														],
					calendar:	{
									calendar_include_time: true,	
									calendar_img_link: 'application/modules/Administrator/layouts/scripts/images/common/calendar.png',
									monthNamesShort: <?php echo $this->translator->translator("common_calender_monthNamesShort"); ?>,
									monthNames:		<?php echo $this->translator->translator("common_calender_monthNames"); ?>,
									dayNamesMin:		<?php echo $this->translator->translator("common_calender_dayNamesMin"); ?>,
									buttonText:		'calendar',
									dateFormat:		'yy-mm-dd',
									dateTimeFormat:     "yyyy-MM-dd HH:mm:ss tt",
									culture: "<?php echo str_ireplace('_', '-', $locale); ?>",
									value: ''
					},
					messages: {
									display				: 	'<?php echo $this->translator->translator("portfolio_pagination_messages_display", '', 'Portfolio'); ?>',
									empty				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_empty", '', 'Portfolio'); ?>',
									page				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_page", '', 'Portfolio'); ?>',
									of					:	'<?php echo $this->translator->translator("portfolio_pagination_messages_of", '', 'Portfolio'); ?>',
									itemsPerPage		:	'<?php echo $this->translator->translator("portfolio_pagination_messages_items_per_page", '', 'Portfolio'); ?>',
									first				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_first", '', 'Portfolio'); ?>',
									previous			:	'<?php echo $this->translator->translator("portfolio_pagination_messages_previous", '', 'Portfolio'); ?>',
									next				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_next", '', 'Portfolio'); ?>',
									last				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_last", '', 'Portfolio'); ?>',
									refresh				:	'<?php echo $this->translator->translator("portfolio_pagination_messages_refresh", '', 'Portfolio'); ?>',
									
									common_msg_dialog_id 		:	'dialog_msg',
									common_confirn_dialog_id	:	'dialog-confirm',
									common_ok					:	"<?php echo html_entity_decode($this->translator->translator('common_ok'), ENT_QUOTES, 'UTF-8'); ?>",
									common_delete_selected		:	"<?php echo html_entity_decode($this->translator->translator("common_delete_selected"), ENT_QUOTES, 'UTF-8'); ?>",
									common_cancel				:	"<?php echo html_entity_decode($this->translator->translator("common_cancel"), ENT_QUOTES, 'UTF-8'); ?>",										
									common_publish_title		:	"<?php echo $this->translator->translator("common_publish_title"); ?>",
									common_unpublish_title		:	"<?php echo $this->translator->translator("common_unpublish_title"); ?>",										
									common_publish_selected		:	"<?php echo $this->translator->translator("common_publish_selected"); ?>",
									common_unpublish_selected	:	"<?php echo $this->translator->translator("common_unpublish_selected"); ?>",
									common_publish_perm	 		:	"<?php echo $this->translator->translator("common_publish_perm"); ?>"
								}
					};

$(function() {
	$( "#hotels_agent" ).combobox();		
});

$(function() {
	$("#tabs").tabs().find(".ui-tabs-nav").sortable({axis:'xy'});
});
	
$(document).ready(function() {	
	floatingbar('#floatingbar',"#button_top_bar",null);
	commonDynamicListAction(settingObj);
	commonFieldToggle(settingObj);
	
	/**********Scrolling Tools Start****************/
	$.easing.elasout = function(x, t, b, c, d) {
		var s=1.70158;var p=0;var a=c;
		if (t==0) return b;  if ((t/=d)==1) return b+c;  if (!p) p=d*.3;
		if (a < Math.abs(c)) { a=c; var s=p/4; }
		else var s = p/(2*Math.PI) * Math.asin (c/a);
		return a*Math.pow(2,-10*t) * Math.sin( (t*d-s)*(2*Math.PI)/p ) + c + b;
	};
	
	$('#toc a').click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		$.scrollTo( this.hash, 1500, { easing:'swing' });
		$(this.hash).find('span.message').text( this.title );
		return false;
	});
	
	$('span.top-go a').click(function(){//$.scrollTo works EXACTLY the same way, but scrolls the whole screen
		$.scrollTo( this.hash, 1500, { easing:'swing' });		
		return false;
	});	
	/**********Scrolling Tools END****************/
		
	$("#upload-form").dialog({
		autoOpen: false,
		width: 760,
		height: 610,
		show: 'fade',			
		modal: true
	});	

	$('a.upload_btn').click(function() {
		var self = this;
		var src = $("#i-upload-form").attr("src");
		$("#i-upload-form").attr("src", 'application/modules/Administrator/layouts/scripts/images/loader/manager_loader.gif');
		
		var group_id = $("#group_id").val();
		$('input[name="primary_id_field_value"]').val(group_id);
		
		var rel = $(self).attr('rel');		
		var file_suffix = rel;	
		var file_content = $('#'+file_suffix).val();
		
		$('input[name="file_path_field"]').val('file_path_'+rel);
		$('input[name="file_content"]').val(file_content);		
		$('input[name="primary_file_field"]').val(file_suffix);		
		
		if(group_id != null && group_id != "")
		{
			$("#popupForm").attr("action", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action' => 'manager' ), 'adminrout',    true) ?>");			
			$('#upload-form').dialog('open');
			$('#popupForm').submit();
		}
		else
		{
			msg = "<?php echo $this->translator->translator("group_id_selected_err"); ?>";
			commonMsgDialog(settingObj, msg);
		}
	});	
	
	$('a.select_file_btn').click(function() {		 
					
			var currentIFrame = $('#i-upload-form');
			var selected_files = currentIFrame.contents().find("input[name='selected_files']").val();
			var primary_file_field = currentIFrame.contents().find("input[name='primary_file_field']").val();
			var file_path	=	currentIFrame.contents().find("input[name='file_path']").val();
			var selected_files_arr = (selected_files != '') ? selected_files.split(',') : new Array();	
			if(selected_files_arr.length == '0')
			{
				var msg = '<?php echo $this->translator->translator("insert_selected_file_err"); ?>';				
				commonMsgDialog(settingObj, msg);
			}
			else
			{
				var img_code = '';
				var file_name = '';
				for(var i=0;i < selected_files_arr.length;i++)
				{
					var ext = getCommonFileExtension(selected_files_arr[i]);
					var img_path = commonFilePath(file_path, selected_files_arr[i]);
								
					var checked = (i == 0)? ' checked="checked" ' : '';
					var img_type = 	(i == 0) ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span>" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span>";
					var primary_file_field_radio =	(primary_file_field == 'hotels_image') ? 'hotels_primary_image'	: 'feature_primary_interior_image';						
					var primary =  '<input class="radio_style" type="radio" name="'+primary_file_field_radio+'" id="'+primary_file_field_radio+'" '+checked+' value="'+selected_files_arr[i]+'" title="<?php echo $this->translator->translator("hotels_primary_image"); ?>" />';
					var del_link = '<a href="javascript:void(0)" class="delete_image_lnk" rel="'+selected_files_arr[i]+'"><?php echo html_entity_decode($this->translator->translator("common_delete"), ENT_QUOTES, "UTF-8"); ?></a>'+primary;
					
					img_code += '<div class="upload-img box">'+img_type+'<br /><span><div class="thumb"><img src="'+img_path+'" width="30" height="20" class="bdr" /></div><br />'+del_link+'&nbsp;</span></div>';
					file_name = (i == 0)? selected_files_arr[i] : file_name+','+selected_files_arr[i];					
				}			
				var file_suffix = primary_file_field;		
				$('#selected_file_'+file_suffix).html(img_code);		
				$('#'+file_suffix).val(file_name);		
				$("#i-upload-form").attr("src", 'application/modules/Administrator/layouts/scripts/images/loader/manager_loader.gif'); 						
				$("#upload-form").dialog('option','hide','explode').dialog('close');				
				deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");	
				commonImageThumbnil();
			}
		});
	
	$('a.close_dialog_btn').click(function() {
		$("#i-upload-form").attr("src", "");
		$("#i-upload-form").html('');		 
		$("#upload-form").dialog('option','hide','explode').dialog('close');			
	});
		
	$('a.reset_btn').click(function() {			
		 commonResetFormFields(settingObj);	
		 commonRemoveFormError(settingObj);	
		 <?php if($this->auth->getIdentity()->access_file_image_manager != '1'){ ?>
			  uploadSettingsEnd();			
		  <?php } ?>			 
	});
	
	$('a.add_hotels_btn').click(function() {			
			
		var formData = commonGetFormData(settingObj.form_action.form_id, settingObj.form_action.hasTinyMCE);		
		$.ajax({
			url: "<?php echo $this->url( array('module' => 'Hotels','controller' => 'backendpro', 'action'     => 'add' ), 'adminrout',    true) ?>",
			  	type: 'POST',
			  	data: formData,
				beforeSend: function(){						
						commonRemoveFormError(settingObj);
						commonOpenLoaderDialog(settingObj);				
					 },
				success: function(response){
					//alert(response);					
					var json_arr = eval("("+response+")");					
					commonCloseLoaderDialog(settingObj);					
					if(json_arr.status == 'ok')
					{
						$('#actionMessage').html(succMsgDesign(json_arr.msg));						
						commonResetFormFields(settingObj);	
						<?php if($this->auth->getIdentity()->access_file_image_manager != '1'){ ?>
							uploadSettingsEnd();			
						<?php } ?>							
					}
					else if(json_arr.status == 'errV')
					{
						$('#actionMessage').html(errMsgDesign("<?php echo $this->translator->translator('common_err'); ?>"));
												
						for(var i= 0; i < json_arr.msg.length; i++)
						{
							commonAddFormError(json_arr.msg[i].key,json_arr.msg[i].value);							
						}
						openFirstErrTab(json_arr.msg, 'tabs', 'tabs-');
					}
					else
					{
						$('#actionMessage').html(errMsgDesign(json_arr.msg));
					}
				},
				error: function(xhr, status, error){
					commonCloseLoaderDialog(settingObj);
					var msg = "Error! " + xhr.status + " " + error;
					$('#actionMessage').html(errMsgDesign(msg));
				}
		});
	});
	
/***********************************Get Hotels Group***************************************/
	$('select[name="group_id"]').change(function() {		
		var group_id = $('#group_id').val();
		$("#"+settingObj.form_action.category_tree.category_tree_input_html_id).html('<?php echo $this->translator->translator("common_tree_root"); ?> (0)');
		$("#"+settingObj.form_action.category_tree.category_tree_input_field_id).val('0');
		commonRemoveTabs(settingObj);
		if(group_id != '')
		{
			settingObj.form_action.category_tree.tree_view.dataSource.transport.read.data['grp_id'] = group_id;
			$('a.back_btn_link').attr('href','Hotels/backend/list/group_id/'+group_id);
			commonKendoTreeGen(settingObj);
		}
		else
		{	
			commonDestroyKendoTreeGen(settingObj);					
			$('a.back_btn_link').attr('href','Hotels/backend/list');
		}		
		$('#group_id_err').html('');		
	});
	
		
});

/***********************************************************************UPLOAD FUNCTIONS START********************************************************/

function uploadSettingsStart(json_arr)
{
	uploadSettingsEnd();
		
	$('#hotels_image_block').prepend('<input type="file" name="hotels_image_upload" id="hotels_image_upload" />');	
	var thumb_setting_param = json_arr.param_fields;
	thumb_setting_param['file_path_field'] = 'file_path_hotels_image';	
	var thumb_setting_info = getSettingInfo(json_arr.group_info, thumb_setting_param);							
	dynamicUploader('hotels_image_upload', 'hotels_image', thumb_setting_info, languageArray(), "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'upload'), 'adminrout',    true) ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove'), 'adminrout',    true) ?>", true);
	
	$('#feature_interior_plan_image_block').prepend('<input type="file" name="feature_interior_plan_image_upload" id="feature_interior_plan_image_upload" />');	
	var file_setting_param = json_arr.param_fields;		
	thumb_setting_param['file_path_field'] = 'file_path_feature_interior_plan_image';	
	var file_setting_info = getSettingInfo(json_arr.group_info, file_setting_param);							
	dynamicUploader('feature_interior_plan_image_upload', 'feature_interior_plan_image', file_setting_info, languageArray(), "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'upload'), 'adminrout',    true) ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove'), 'adminrout',    true) ?>", true);
	
	$('#hotels_image_err').html("");
	$('#feature_interior_plan_image_err').html("");
}

function uploadSettingsEnd()
{	
	$('#hotels_image_upload').parents('div.k-upload').remove();	
	$('#feature_interior_plan_image_upload').parents('div.k-upload').remove();	
	$('#hotels_image_err').html("<?php echo $this->translator->translator("group_id_selected_err"); ?>");
	$('#feature_interior_plan_image_err').html("<?php echo $this->translator->translator("group_id_selected_err"); ?>");
}

function languageArray()
{
	var language_array = [];
	language_array['portfolio_upload_dy_text_select'] 					= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_dy_text_select", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_cancel'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_cancel", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_dropFilesHere'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_dropFilesHere", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_remove'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_remove", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_retry'] 						= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_retry", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusFailed'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusFailed", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusUploaded'] 				= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusUploaded", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_statusUploading'] 			= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_statusUploading", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_upload_text_uploadSelectedFiles'] 		= "<?php echo html_entity_decode($this->translator->translator("portfolio_upload_text_uploadSelectedFiles", '', 'Portfolio'), ENT_QUOTES, 'UTF-8'); ?>";
	language_array['portfolio_file_extension_dy_support'] 				= "<?php echo $this->translator->translator("portfolio_file_extension_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_no_ext_dy_support'] 					= "<?php echo $this->translator->translator("portfolio_file_no_ext_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_extension_dy_not_supportable_ext1'] 	= "<?php echo $this->translator->translator("portfolio_file_extension_dy_not_supportable_ext1", '', 'Portfolio'); ?>";
	language_array['portfolio_file_extension_dy_not_supportable_ext2']  = "<?php echo $this->translator->translator("portfolio_file_extension_dy_not_supportable_ext2", '', 'Portfolio'); ?>";
	language_array['portfolio_file_size_dy_support'] 					= "<?php echo $this->translator->translator("portfolio_file_size_dy_support", '', 'Portfolio'); ?>";
	language_array['portfolio_file_upload_err'] 						= "<?php echo $this->translator->translator("portfolio_file_upload_err", '', 'Portfolio'); ?>";
	return language_array;
}


function successFileDecoretion(fileObj, serverData, upload_field, upload_value_field)
{
		var extension = fileObj.extension;
		var ext = extension.replace('.','');	
		
		var img_path = commonFilePath(serverData.file_path, fileObj.name);
			
		var img_code = '<div class="thumb"><img src="'+img_path+'" title="'+fileObj.name+'" width="30" height="20" /></div>';		 
		var down_link = (!isImage(fileObj)) ? '<br /><a href="'+serverData.file_path+'/'+fileObj.name+'"><?php echo $this->translator->translator("common_download", "", "Projects"); ?></a>' : '';
		
		var checked = '';
		var primary = '&nbsp;&nbsp;&nbsp;';	
		var block = 'selected_file_'+upload_value_field;
		var img_type = '';	
		var primary_file_field_radio = '';	
			
		switch(upload_value_field)
		{
			case 'hotels_image':					
					primary_file_field_radio =	 'hotels_primary_image';
					checked = ($('#'+upload_value_field).val() == '') ? ' checked="checked" ' : '';	
					img_type = 	($('#'+upload_value_field).val() == '') ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span><br />" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span><br />";				
					primary = '<input class="radio_style" type="radio" name="'+primary_file_field_radio+'" id="'+primary_file_field_radio+'" '+checked+' value="'+fileObj.name+'" title="<?php echo $this->translator->translator("hotels_primary_image"); ?>" />';						
				break;
			case 'feature_interior_plan_image':
					primary_file_field_radio =	'feature_primary_interior_image';	
					checked = ($('#'+upload_value_field).val() == '') ? ' checked="checked" ' : '';	
					img_type = 	($('#'+upload_value_field).val() == '') ? "<span class='main'><?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?></span><br />" : "<span class='related'><?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?></span><br />";				
					primary = '<input class="radio_style" type="radio" name="'+primary_file_field_radio+'" id="'+primary_file_field_radio+'" '+checked+' value="'+fileObj.name+'" title="<?php echo $this->translator->translator("hotels_primary_image"); ?>" />';
				break;
		}				
		
		var del_link = '<a href="javascript:void(0)" class="delete_uploaded_image_link" field_name="'+upload_value_field+'" file_name="'+fileObj.name+'" file_path="'+serverData.file_path+'"><?php echo $this->translator->translator("common_delete_title"); ?></a>'+primary +  down_link;
		
		if(serverData.multi)
		{		
			$('#'+block).append('<div class="upload-img box">'+img_type+'<span>'+img_code+'<br /><br />&nbsp;'+del_link+'&nbsp;</span></div>');				 
			var file_val = ($('#'+upload_value_field).val() == '') ? fileObj.name :  $('#'+upload_value_field).val()+','+fileObj.name;	
		}
		else
		{
			$('#'+block).html('<div class="upload-img box">'+img_type+'<span>'+img_code+'<br /><br />&nbsp;'+del_link+'&nbsp;</span></div>');				 
			var file_val = fileObj.name;
		}
		$('#'+upload_value_field).val(file_val);
		deleteFiles("<?php echo $this->translator->translator('gallery_img_main', '', 'Gallery'); ?>", "<?php echo $this->translator->translator('gallery_img_related', '', 'Gallery'); ?>", "<?php echo $this->url( array('module' => 'Portfolio','controller' => 'frontend', 'action'     => 'remove' ), 'adminrout',    true) ?>", "<?php echo $this->translator->translator('common_delete_title'); ?>");	
		commonImageThumbnil();	
}

function onComplete(e) {
			
}

function onCancel(e) {
	
}

function onProgress(e) {
					
}

/***********************************************************************UPLOAD FUNCTIONS END********************************************************/
</script>

<div id="button_top_bar"></div>
<div class="title-container">
	<div class="hotels-add"><h1><?php echo $this->translator->translator('hotels_page_add_page_name'); ?></h1></div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Hotels','controller' => 'Backendpro', 'action'     => 'list' ,'group_id' => $param_group_id), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_hotels_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

<div class="content-container" id="topGo">
	<div id="sidebar-inner">
    	<div id="nav" <?php if($locale_direction == 'rtl'){ ?> class="k-rtl" <?php } ?>>
    		<div class="nav-header"><div class="nav-title"><?php echo $this->translator->translator('hotels_tree'); ?></div></div>
    		<div id="categoryTree" class="nav-body treebody">
           		&nbsp;	
            </div>
       	</div>
    </div>
    
    <div id="content-inner">
    	<div id="actionMessage"></div>
        <form name="formItem" id="formItem" method="post">
        	<div id="generalInfo">
            	<div id="tabs">
                	<ul>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-1"><?php echo $this->translator->translator('hotels_general_info'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-2"><?php echo $this->translator->translator('hotels_page_page_image'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-3"><?php echo $this->translator->translator('hotels_page_feature'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-4"><?php echo $this->translator->translator('hotels_page_page_Other'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-5"><?php echo $this->translator->translator('hotels_page_page_policy'); ?></a></li>
                        <li><a href="<?php echo $tab_base_link; ?>#tabs-6"><?php echo $this->translator->translator('hotels_page_page_invoice_billing'); ?></a></li>
                    </ul>
                    
                    <div id="tabs-1">
                    	<fieldset class="fieldset">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_page_info'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_name->getLabel();  if($this->proForm->hotels_name->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php  echo $this->proForm->hotels_name; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_name->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_name_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_title->getLabel();  if($this->proForm->hotels_title->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_title;  ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_title->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_title_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_grade->getLabel();  if($this->proForm->hotels_grade->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_grade; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_grade->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_grade_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_status->getLabel();  if($this->proForm->hotels_status->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_status; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_status->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_status_err"></div>
                                </div>
                            </div>
                            <?php
							if($this->auth->getIdentity()->allow_to_change_ownership == '1')
								{
							?>
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_agent->getLabel();  if($this->proForm->hotels_agent->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <span class="ui-widget"><?php echo $this->proForm->hotels_agent;  ?></span>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_agent->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_agent_err"></div>
                                </div>
                            </div>
                            <?php
								}
							?>
                           	<div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->group_id->getLabel();  if($this->proForm->group_id->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->group_id; ?></div><span id="group_id_loader"></span>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->group_id->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="group_id_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_type->getLabel();  if($this->proForm->hotels_type->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_type; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_type->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_type_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->category_id->getLabel(); ?>
                                </div>
                                
                                <div class="field">
                                    <span id="dataId"><?php echo $this->translator->translator("hotels_tree_root"); ?> (0)</span><?php echo $this->proForm->category_id; ?>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->room_type_id->getLabel();  if($this->proForm->room_type_id->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php  echo $this->proForm->room_type_id; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_name->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="room_type_id_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_desc->getLabel();  if($this->proForm->hotels_desc->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_desc; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink1"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_desc',1);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_desc_err"></div>
                                </div>	
                            </div>
                     	</div>
                        </fieldset>
                        
                        <fieldset class="fieldset last">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_address_info'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->country_id->getLabel();  if($this->proForm->country_id->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->country_id; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->country_id->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="country_id_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->state_id->getLabel();  if($this->proForm->state_id->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->state_id; ?></div><span id="state_id_loader"></span>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->state_id->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="state_id_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->area_id->getLabel();  if($this->proForm->area_id->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->area_id; ?></div><span id="area_id_loader"></span>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->area_id->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="area_id_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->location_for_search->getLabel();  if($this->proForm->location_for_search->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->location_for_search; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->location_for_search->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="location_for_search_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_building_name->getLabel();  if($this->proForm->hotels_building_name->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_building_name; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_building_name->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_building_name_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_building_no->getLabel();  if($this->proForm->hotels_building_no->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_building_no; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_building_no->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_building_no_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_phone->getLabel();  if($this->proForm->hotels_phone->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_phone; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_phone->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_phone_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_fax->getLabel();  if($this->proForm->hotels_fax->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_fax; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_fax->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_fax_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_email->getLabel();  if($this->proForm->hotels_email->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_email; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_email->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_email_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->post_code->getLabel();  if($this->proForm->post_code->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->post_code; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->post_code->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="post_code_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_address->getLabel();  if($this->proForm->hotels_address->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_address; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_address->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                  	<span id="loaderLink2"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_address',2);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_address_err"></div>
                                </div>	
                            </div>
                    	</div>
                        </fieldset>
                    </div>
                    
                    <div id="tabs-2">
                    	<fieldset class="fieldset">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_page_image'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_image->getLabel();  if($this->proForm->hotels_image->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                	<?php	
										if($this->auth->getIdentity()->access_file_image_manager == '1')
										{
									?>
                                    <div class="upload-img">
                                    	<span class="button  ui-widget-content-1"><a href="javascript:  void(0);" class="upload_btn" rel="hotels_image"><span class="icon upload"><?php echo $this->translator->translator('common_upload'); ?></span></a></span>
                                  		<div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_image->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    
                                    <?php echo $this->proForm->hotels_image; ?>
                                    <div class="input-errors" id="hotels_image_err"></div><div class="input-errors" id="hotels_primary_image_err"></div>
                                    
									<?php
										}
										else
										{
									?>
                                    <div class="upload-img">
                                    	<div id="hotels_image_block"><?php echo $this->proForm->hotels_image; ?></div>
                                    </div>
									<div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_image->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_image_err"><?php echo $this->escape($this->translator->translator("group_id_selected_err")); ?></div><div class="input-errors" id="hotels_primary_image_err"></div>
                                    <?php
										}
									?>                                    
                                </div>
                                
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                </div>
                    		
                                <div class="field">
                                	<span id="selected_file_hotels_image"></span>
                                </div>
                         	</div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->feature_interior_plan_image->getLabel();  if($this->proForm->feature_interior_plan_image->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                	<?php	
										if($this->auth->getIdentity()->access_file_image_manager == '1')
										{
									?>
                                    
                                    <div class="upload-img">
                                    	<span class="button  ui-widget-content-1"><a href="javascript:  void(0);" class="upload_btn" rel="feature_interior_plan_image"><span class="icon upload"><?php echo $this->translator->translator('common_upload'); ?></span></a></span>
                                  		<div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_interior_plan_image->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    </div>
                                    
                                    <?php echo $this->proForm->feature_interior_plan_image; ?>
                                    <div class="input-errors" id="feature_interior_plan_image_err"></div>
                                    
                                    <?php
										}
										else
										{
									?>
                                    <div class="upload-img">
                                    	<div id="feature_interior_plan_image_block"><?php echo $this->proForm->feature_interior_plan_image; ?></div>
                                    </div>
									<div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_interior_plan_image->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="feature_interior_plan_image_err"><?php echo $this->escape($this->translator->translator("group_id_selected_err")); ?></div>
                                    <?php
										}
									?>
                                </div>
                         	</div>
                            
                            <div class="form-row">
                                <div class="label">
                                </div>
                    		
                                <div class="field">
                                	<span id="selected_file_feature_interior_plan_image"></span>
                                </div>
                         	</div>
                      	</div>
                        </fieldset>
                        
                        <fieldset class="fieldset">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_product_page_related_items'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->related_items->getLabel();  if($this->proForm->related_items->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php  echo $this->proForm->related_items;  ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->related_items->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="related_items_err"></div>
                                </div>
                            </div>
                     	</div>
                        </fieldset>
                        
                        <fieldset class="fieldset last">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_page_meta'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->meta_title->getLabel();  if($this->proForm->meta_title->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php  echo $this->proForm->meta_title; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->meta_title->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="meta_title_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->meta_keywords->getLabel();  if($this->proForm->meta_keywords->isRequired()){ ?><span class="required">*</span><?php }?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->meta_keywords; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->meta_keywords->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="meta_keywords_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->meta_desc->getLabel();  if($this->proForm->meta_desc->isRequired()){ ?><span class="required">*</span><?php }?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->meta_desc; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->meta_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="meta_desc_err"></div>
                                </div>
                            </div>
                     	</div>
                        </fieldset>
                   	</div>
                    
                    <div id="tabs-3">
                    	<fieldset class="fieldset">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_sec_feature'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->feature_facilities->getLabel();  if($this->proForm->feature_facilities->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <div class="hotels-features"><?php  echo $this->proForm->feature_facilities;  ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_facilities->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="feature_facilities_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <hr />
                                </div>
                    		
                                <div class="field">
                                	<hr />
                                </div>
                         	</div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->feature_sports_recreations->getLabel();  if($this->proForm->feature_sports_recreations->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <div class="hotels-features"><?php  echo $this->proForm->feature_sports_recreations;  ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_sports_recreations->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="feature_sports_recreations_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->feature_google_map->getLabel();  if($this->proForm->feature_google_map->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->feature_google_map; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_google_map->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink3"><a href="javascript:void(0);" onClick="loadTinyMCE('feature_google_map',3);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="feature_google_map_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->feature_additional->getLabel();  if($this->proForm->feature_additional->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->feature_additional; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_additional->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink4"><a href="javascript:void(0);" onClick="loadTinyMCE('feature_additional',4);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="feature_additional_err"></div>
                                </div>	
                            </div>
                     	</div>
                        </fieldset>
                        
                        <fieldset class="fieldset last">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_page_brochure'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->brochure_title->getLabel();  if($this->proForm->brochure_title->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->brochure_title;  ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->brochure_title->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="brochure_title_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->brochure_desc->getLabel();  if($this->proForm->brochure_desc->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->brochure_desc; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->brochure_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink6"><a href="javascript:void(0);" onClick="loadTinyMCE('brochure_desc',6);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif"  border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="brochure_desc_err"></div>
                                </div>	
                            </div>
                     	</div>
                        </fieldset>
                    </div>
                    
                    <div id="tabs-4">
                    	<fieldset class="fieldset">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_page_available'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->checkin_hour->getLabel();  if($this->proForm->checkin_hour->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php  echo $this->proForm->checkin_hour.'&nbsp;'.$this->proForm->checkin_min.'&nbsp;'.$this->proForm->checkin_time; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->checkin_hour->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="checkin_hour_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->checkout_hour->getLabel();  if($this->proForm->checkout_hour->isRequired()){ ?><span class="required">*</span><?php }?>
                                </div>
                                
                                <div class="field">
                                    <?php  echo $this->proForm->checkout_hour.'&nbsp;'.$this->proForm->checkout_min.'&nbsp;'.$this->proForm->checkout_time; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->checkout_hour->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="checkout_hour_err"></div>
                                </div>
                            </div>
                     	</div>
                        </fieldset>
                        
                        <fieldset class="fieldset">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_page_summary'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->feature_distance_from_airport->getLabel();  if($this->proForm->feature_distance_from_airport->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php  echo $this->proForm->feature_distance_from_airport.'&nbsp;'.$this->translator->translator('hotels_page_pre_unit');  ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_distance_from_airport->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="feature_distance_from_airport_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->feature_distance_from_city_market->getLabel();  if($this->proForm->feature_distance_from_city_market->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php  echo $this->proForm->feature_distance_from_city_market.'&nbsp;'.$this->translator->translator('hotels_page_pre_unit');  ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_distance_from_city_market->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="feature_distance_from_city_market_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->feature_pet->getLabel();  if($this->proForm->feature_pet->isRequired()){ ?><span class="required">*</span><?php }?>
                                </div>
                                
                                <div class="field">
                                    <?php  echo $this->proForm->feature_pet; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->feature_pet->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="feature_pet_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->payment_options->getLabel();  if($this->proForm->payment_options->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->payment_options; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->payment_options->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="payment_options_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_about_internet->getLabel();  if($this->proForm->hotels_about_internet->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_about_internet; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_about_internet->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_about_internet_err"></div>
                                </div>
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_about_parking->getLabel();  if($this->proForm->hotels_about_parking->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                                
                                <div class="field">
                                    <?php echo $this->proForm->hotels_about_parking; ?>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_about_parking->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <div class="input-errors" id="hotels_about_parking_err"></div>
                                </div>
                            </div> 
                    	</div>
                      	</fieldset>
                        
                        <fieldset class="fieldset">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_page_payment'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->payment_desc->getLabel();  if($this->proForm->payment_desc->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->payment_desc; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->payment_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink5"><a href="javascript:void(0);" onClick="loadTinyMCE('payment_desc',5);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="payment_desc_err"></div>
                                </div>	
                            </div>
                     	</div>
                        </fieldset>
                        
                        <fieldset class="fieldset last">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_profile_information'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_about_information->getLabel();  if($this->proForm->hotels_about_information->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_about_information; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_about_information->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink7"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_about_information',7);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_about_information_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_about_general->getLabel();  if($this->proForm->hotels_about_general->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_about_general; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_about_general->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink8"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_about_general',8);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_about_general_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_about_services->getLabel();  if($this->proForm->hotels_about_services->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_about_services; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_about_services->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink9"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_about_services',9);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_about_services_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_policy_surroundings->getLabel();  if($this->proForm->hotels_policy_surroundings->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_policy_surroundings; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_policy_surroundings->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink16"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_policy_surroundings',16);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_policy_surroundings_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_about_other->getLabel();  if($this->proForm->hotels_about_other->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_about_other; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_about_other->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink12"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_about_other',12);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_about_other_err"></div>
                                </div>	
                            </div>
                     	</div>
                        </fieldset>
                    </div>
                    
                    <div id="tabs-5">
                    	<fieldset class="fieldset last">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_page_policy_info'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_policy_policies->getLabel();  if($this->proForm->hotels_policy_policies->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_policy_policies; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_policy_policies->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink13"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_policy_policies',13);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_policy_policies_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_policy_terms_condition->getLabel();  if($this->proForm->hotels_policy_terms_condition->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_policy_terms_condition; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_policy_terms_condition->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink14"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_policy_terms_condition',14);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_policy_terms_condition_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->hotels_policy_privacy->getLabel();  if($this->proForm->hotels_policy_privacy->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->hotels_policy_privacy; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->hotels_policy_privacy->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink15"><a href="javascript:void(0);" onClick="loadTinyMCE('hotels_policy_privacy',15);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="hotels_policy_privacy_err"></div>
                                </div>	
                            </div>
                     	</div>
                        </fieldset>
                    </div>
                    
                    <div id="tabs-6">
                    	<fieldset class="fieldset last">
                		<legend class="legend"><?php echo $this->translator->translator('hotels_page_invoice_billing_info'); ?></legend>
                        <span class="top-go right-float"><a href="#topGo"><img src="application/modules/Administrator/layouts/scripts/images/tools/top.png" border="0" alt="<?php echo $this->translator->translator('common_go_top_title'); ?>" title="<?php echo $this->translator->translator('common_go_top_title'); ?>" /></a></span>
                       	<div class="form">
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->billing_user_places_order_email_enable->getLabel();  if($this->proForm->billing_user_places_order_email_enable->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->billing_user_places_order_email_enable; ?></div>
                                    <?php if($this->proForm->billing_user_places_order_email_enable->getAttrib('title')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_places_order_email_enable->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
                                    <div class="input-errors" id="billing_user_places_order_email_enable_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->billing_user_places_order_email_address->getLabel();  if($this->proForm->billing_user_places_order_email_address->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->billing_user_places_order_email_address; ?></div>
                                    <?php if($this->proForm->billing_user_places_order_email_address->getAttrib('title')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_places_order_email_address->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
                                    <div class="input-errors" id="billing_user_places_order_email_address_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->billing_user_pay_invoice_email_enable->getLabel();  if($this->proForm->billing_user_pay_invoice_email_enable->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->billing_user_pay_invoice_email_enable; ?></div>
                                    <?php if($this->proForm->billing_user_pay_invoice_email_enable->getAttrib('title')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_pay_invoice_email_enable->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
                                    <div class="input-errors" id="billing_user_pay_invoice_email_enable_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->billing_user_pay_invoice_email_address->getLabel();  if($this->proForm->billing_user_pay_invoice_email_address->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->billing_user_pay_invoice_email_address; ?></div>
                                    <?php if($this->proForm->billing_user_pay_invoice_email_address->getAttrib('title')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_pay_invoice_email_address->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
                                    <div class="input-errors" id="billing_user_pay_invoice_email_address_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->billing_user_cancel_order_email_enable->getLabel();  if($this->proForm->billing_user_cancel_order_email_enable->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->billing_user_cancel_order_email_enable; ?></div>
                                    <?php if($this->proForm->billing_user_cancel_order_email_enable->getAttrib('title')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_cancel_order_email_enable->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
                                    <div class="input-errors" id="billing_user_cancel_order_email_enable_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->billing_user_cancel_order_email_address->getLabel();  if($this->proForm->billing_user_cancel_order_email_address->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->billing_user_cancel_order_email_address; ?></div>
                                    <?php if($this->proForm->billing_user_cancel_order_email_address->getAttrib('title')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_user_cancel_order_email_address->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
                                    <div class="input-errors" id="billing_user_cancel_order_email_address_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->billing_order_payment_email_enable->getLabel();  if($this->proForm->billing_order_payment_email_enable->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->billing_order_payment_email_enable; ?></div>
                                    <?php if($this->proForm->billing_order_payment_email_enable->getAttrib('title')){ ?><div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_order_payment_email_enable->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div><?php } ?>
                                    <div class="input-errors" id="billing_order_payment_email_enable_err"></div>
                                </div>	
                            </div>
                            
                            <div class="form-row">
                                <div class="label">
                                    <?php echo $this->proForm->billing_item_desc->getLabel();  if($this->proForm->billing_item_desc->isRequired()){ ?><span class="required">*</span><?php } ?>
                                </div>
                    
                                <div class="field">
                                    <div class="left-float"><?php echo $this->proForm->billing_item_desc; ?></div>
                                    <div class="ui-widget ui-helper-clearfix info"><div class="ui-widget-header ui-corner-all ui-state-default" title="<?php echo $this->escape($this->proForm->billing_item_desc->getAttrib('title')); ?>"><p><span class="ui-icon ui-icon-info"></span></p></div></div>
                                    <span id="loaderLink17"><a href="javascript:void(0);" onClick="loadTinyMCE('billing_item_desc',17);"><img src="application/modules/Administrator/layouts/scripts/images/common/editors.gif" border="0" title="<?php echo $this->translator->translator('common_editor_open'); ?>" alt="<?php echo $this->translator->translator('common_editor_open'); ?>" /></a></span>
                                    <div class="input-errors" id="billing_item_desc_err"></div>
                                </div>	
                            </div>
                     	</div>
                        </fieldset>
                    </div>
                </div>
          	</div>
      	</form>
	</div>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Hotels','controller' => 'Backendpro', 'action'     => 'list' ,'group_id' => $param_group_id), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_hotels_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

<div id="floatingbar">
	<h1><?php echo $this->translator->translator('hotels_page_add_page_name'); ?></h1>
    
    <div class="button-container">
        <span class="button ui-widget-content-1"><a href="<?php echo $this->url( array('module' => 'Hotels','controller' => 'Backendpro', 'action'     => 'list' ,'group_id' => $param_group_id), 'adminrout',    true) ?>" class="back_btn_link"><span class="icon back"><?php echo $this->translator->translator('common_back'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript:  void(0);" class="reset_btn"><span class="icon reset"><?php echo $this->translator->translator('common_reset'); ?></span></a></span>
        <span class="button ui-widget-content-1"><a href="javascript: void(0);" class="add_hotels_btn"><span class="icon save"><?php echo $this->translator->translator('common_save'); ?></span></a></span>
    </div>
</div>

    <div id="dialog_msg" title="<?php echo $this->translator->translator('common_dialog_msg',$this->translator->translator('hotels_page_edit_page_name')); ?>">
    </div>
    <div id="dialog_container" style="display:none" title="<?php echo $this->translator->translator('common_processing_language'); ?>">
        <div id="progressbar" ></div>	
    </div>
    <div id="upload-form" title="<?php echo $this->translator->translator('hotels_page_page_dialog'); ?>">
        <div>
            <form id="popupForm" target="i-upload-form" method="post" action="" >
                <input type="hidden" name="table_name" value="hotels_group"/>
                <input type="hidden" name="primary_id_field" value="id"/>
                <input type="hidden" name="primary_id_field_value" value=""/>   
                <input type="hidden" name="primary_file_field" value=""/> 
                <input type="hidden" name="file_content"  value=""/>       
                <input type="hidden" name="file_path_field" value=""/>
                <input type="hidden" name="file_extension_field" value="file_type"/>
                <input type="hidden" name="file_max_size_field" value="file_size_max"/>
            </form>
            <iframe id="i-upload-form" name="i-upload-form" src="application/modules/Administrator/layouts/scripts/images/loader/manager_loader.gif" class="iframe-img-upload"></iframe>        
        </div>
        <div class="button-container">
            <span class="button ui-widget-content-1"><a href="javascript:void(0);" class="select_file_btn"><span class="icon insert"><?php echo $this->translator->translator('hotels_page_page_insert'); ?></span></a></span>
            <span class="button ui-widget-content-1"><a href="javascript:void(0);" class="close_dialog_btn"><span class="icon close"><?php echo $this->translator->translator('common_close'); ?></span></a></span>
        </div>
    </div>
<?php endif; ?>	
</div>