<!DOCTYPE html>
<?php $front_template = Zend_Registry::get('front_template'); $is_frontend = new Eicra_Model_DbTable_Frontend(); $license = new Zend_Session_Namespace('License'); $validation_data = $license->license_data;
$locale = Eicra_Global_Variable::getSession()->sess_lang;
$locale_arr = explode('_', $locale);
$locale_direction = Eicra_Global_Variable::getSession()->site_direction;
$global_conf = Zend_Registry::get('global_conf');
?> 
<html dir="<?php echo $locale_direction; ?>" lang="<?php echo $locale_arr[0]; ?>"> 
<head>
<meta charset="utf-8">
<base href="<?php echo $this->serverUrl().$this->baseUrl(); ?>/" /> 

<link rel="shortcut icon" href="<?php echo $global_conf['frontend_favicon']; ?>" type="image/x-icon" />

<?php  echo $this->headMeta(); ?>

<?php echo html_entity_decode($this->headTitle(), ENT_QUOTES ,"UTF-8"); ?>

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
<?php
$version = new Eicra_License_Version();
echo $this->partial('head/headscript.phtml');
$frontController = Zend_Controller_Front::getInstance();
$moduleName = strtolower($frontController->getRequest()->getModuleName());	
$controllerName = strtolower($frontController->getRequest()->getControllerName());
$actionName = strtolower($frontController->getRequest()->getActionName());
$add_url =  $this->url(array('module'=> 'Hotels','controller'=>'members', 'action'=>'add'), 'Members-Hotel-Add/*', true);
?>

</head>
<body>
<div id="wrapper">
	<!-- Header Start -->
	<?php echo $this->layout()->render('header'); ?>
	<!-- Header End -->
    
    <!-- Top Navigation Start-->
    <nav class="top-nav">
        <div class="container"><?php echo $this->partial('blocks/menu_header.phtml'); ?></div>
    </nav>
    <!-- Top Navigation End-->
    
    <!-- Body Start -->
    <section id="main-container">
   		<?php if($is_frontend->isFrontend()){ ?>
        <!-- Banner Start -->
        <div id="banner">
        	<div class="slideshow-container">
            	<?php //echo $this->partial('blocks/banner_slideshow.phtml'); ?>
                <img src="application/layouts/scripts/<?php echo $front_template['theme_folder']; ?>/images/banner.jpg">
            </div>
            <div class="search-container">
            	<?php echo $this->partial('blocks/hotels_count.phtml'); ?>
            	<?php echo $this->partial('blocks/hotels_home_banner_search.phtml'); ?>
            </div>
        </div>
        <!-- Banner End -->
        
        <!-- Left Sidebar Start-->
        <aside id="sidebar">
            <div class="add-btn"><span class="icon"></span><a href="<?php echo $add_url; ?>"><?php echo $this->translator->translator('hotels_front_page_home_add_btn_link','', '', $front_template['theme_folder']); ?></a></div>
            <?php echo $this->partial('blocks/hotels_sidebar_reviews.phtml'); ?>
            <?php $this->ad(190); ?><?php //echo $this->partial('blocks/ad_home_sidebar.phtml');  ?>
            <?php echo $this->partial('blocks/gallery_sidebar_featured.phtml'); ?>
            <?php echo $this->partial('blocks/why-book.phtml'); ?>
            <?php echo $this->partial('blocks/newsletter_sidebar.phtml'); ?>
            <?php echo $this->partial('blocks/sidebar_social.phtml'); ?>
        </aside>
        <!-- Left Sidebar End -->
        
        <!-- Content Start -->
        <article id="content">
            <?php echo $this->partial('blocks/hotels_home_content_popular.phtml'); ?>
            <?php echo $this->partial('blocks/hotels_home_businessType.phtml'); ?>
            <!-- Featured Tab Start -->
            <div id="usual" class="usual">
                <ul>
                    <li><a class="selected" href="#tab1"><?php echo $this->translator->translator('hotels_block_featured_list_title','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a class="" href="#tab2"><?php echo $this->translator->translator('hotels_block_latest_list_title','', '', $front_template['theme_folder']); ?></a></li>
                    <li><a class="" href="#tab3"><?php echo $this->translator->translator('tab_news_title','', '', $front_template['theme_folder']); ?></a></li>
                </ul>
            </div>
            <div class="usual-content">
                <div style="display:block;" id="tab1"><?php echo $this->partial('blocks/hotels_home_content_featured.phtml'); ?></div>
                <div style="display: none;" id="tab2"><?php echo $this->partial('blocks/hotels_home_content_recent.phtml'); ?></div>
                <div style="display: none;" id="tab3"><?php echo $this->partial('blocks/news_home_content_latest.phtml'); ?></div>
            </div>

            <script type="text/javascript">
                $("#usual ul").idTabs();
            </script>	
            <!-- Featured Tab End -->
        </article>
        <!-- Content End -->
        
        <div class="clear"></div>
		<?php echo $this->partial('blocks/ad_home_content_scrolling.phtml'); ?>        
        <?php 
			}
			else
			{
		?>
    
		<!-- Inner Layout Start -->
		<?php 
            $innter_page_content_width = 'style="width:100%"';
            if(!empty($moduleName) && $actionName != 'home')
            {
                switch($moduleName)
                {	
                    case 'vacationrentals':	
                    case 'hotels':
                    if($actionName != 'index' && !(strtolower($controllerName) == 'expedia' && $actionName == 'details'))
                    {
                        $innter_page_content_width = '';
        ?>
        <div id="sidebar-inner">        					
            <?php if( strtolower($controllerName) != 'expedia'){ echo $this->partial('blocks/'.$moduleName.'_inner_sidebar_search.phtml'); } ?>                  	
            <div class="left-ad">
            <?php echo $this->partial('blocks/ad_inner_leftsidebar.phtml'); ?>
            </div>
        </div>
		<?php
                }
            break;
                }
            }
        ?>
            
        <div id="content-inner" <?php echo $innter_page_content_width; ?>> 
            <?php echo $this->layout()->content ?>
        </div>
		<!-- Inner Layout End -->
    	<?php
			}
		?>
    </section>
    <!-- Body End -->
    
    <!-- Footer Start -->
    <?php echo $this->layout()->render('footer'); ?>
    <!-- Footer End --> 
</div>
<div class="go-top"><a href="#top" id="scroll-top"><?php echo $this->translator->translator('footer_top','', '', $front_template['theme_folder']); ?></a></div>
<?php echo $this->headScript()->setFile('application/layouts/scripts/'.$front_template['theme_folder'].'/vendor/scripts/js/scroll.js'); ?>
</body>
</html>
<?php echo $this->escape($global_conf['analytics_code']); ?>